### ISSUE TITLE
search.php - Escape html for `get_search_query()` in page title

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentyseventeen#1]
The title is pretty self explanatory. The search query must be wrapped in `esc_html()` for the page title of _search.php_

**Comment by ernilambar** [comment]
`get_search_query()` is already escaped. I believe escaping is not needed here. 
https://developer.wordpress.org/reference/functions/get_search_query/#source

**Comment by laurelfulford** [comment]
I jumped the gun and merged this as it matches what's used in Twenty Sixteen, but @ernilambar is right - `get_search_query()` is escaped with `esc_attr()`.

I've reverted and am closing, since it seems unneeded, but please reopen if this needs further discussion - thanks!
