### ISSUE TITLE
Device testing: Make a device testing plan

### ISSUE THREAD

**Issue by davidakennedy** [WordPress/twentyseventeen#10]
With this, let's decide:
- What devices should the theme be tested on?
- Form a plan to ensure that happens.

**Comment by ntwb** [comment]
There's a fairly comprehensive list of browser usage at http://caniuse.com/usage-table

Also WordPress #core uses Autoprefixer to dynamically create vendor prefixes based on the following devices: https://core.trac.wordpress.org/browser/trunk/Gruntfile.js#L27

``` js
'Android >= 2.1',
'Chrome >= 21',
'Edge >= 12',
'Explorer >= 7',
'Firefox >= 17',
'Opera >= 12.1',
'Safari >= 6.0'
```

**Comment by karmatosed** [comment]
I'm happy to come up with a device list and plan so assigning to myself in order to get this task done.

**Comment by karmatosed** [comment]
Device testing plan for devices:
- Android phone
- Android tablet
- iPhone 6
- iPhone 6 plus
- iPhone 5
- iPad mini
- iPad retina
- Amazon fire

Browsers we should test are the following:
- IE 9
- IE 10
- IE 11
- Safari latest
- Firefox latest
- Chrome latest
- Opera latest

I have made an issue for device and one for browser testing to sign off each.
https://github.com/WordPress/twentyseventeen/issues/389
https://github.com/WordPress/twentyseventeen/issues/388

**Comment by karmatosed** [comment]
Closing as we have a plan.
