### ISSUE TITLE
Display excerpt instead of full post in blog view

### ISSUE THREAD

**Issue by acosmin** [WordPress/twentyseventeen#100]
As the title says, display the excerpt when showing the blog view (maybe with a post thumbnail next to it). Showing full posts in this view only makes the height bigger and it doesn't really go well with "business" themes.

**Comment by melchoyce** [comment]
I think we said we'd do excerpts if a post has them, and otherwise, we'd show the full-post view. That gives users the most control without adding a separate option to toggle between the two. Does that sound right @laurelfulford?

**Comment by laurelfulford** [comment]
Yes - it seems like the most flexible way to handle it. I can see some users wanting to show just excerpts, but others wanting just full posts or even a mix of both -- this'll allow that :)

I'm going to close this, but please comment if you'd like to discuss further!
