### ISSUE TITLE
Big header image - disable in post / page views

### ISSUE THREAD

**Issue by asathoor** [WordPress/twentyseventeen#101]
When you click in order to read a post or a page you'll see the big header image and not the heading you're looking for. On smaller screens the heading is below the "fold". You have to scroll in order to read the post / page.

I suggest that the height of the big top image is reduced on pages or posts.

![xx17-post](https://cloud.githubusercontent.com/assets/6114751/18870321/5bf5a370-84b0-11e6-9cb5-b2392047ee80.png)

**Comment by jordesign** [comment]
Can we utilise viewport height units (vh) or or something to ensure that the  heading always appears onscreen - even on smaller screens?

**Comment by melchoyce** [comment]
Hi @asathoor, please see #4 for the design mockups. The larger header section is only included on the homepage.
