### ISSUE TITLE
Explore viewport units for responsive typography 

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#102]
Placeholder issue for now. I'll come back later and explain what I'm thinking.

**Comment by melchoyce** [comment]
Something like this:
- https://www.smashingmagazine.com/2016/05/fluid-typography/

Where we'd define a min font-size and a max font-size, but scale between those sizes using `vw`.

**Comment by joyously** [comment]
Just be sure to have a fallback for those browsers that don't handle it, like fairly recent Android and Opera.
http://caniuse.com/#search=viewport

**Comment by mor10** [comment]
My experience with responsive font sizes with be and vh has been sub-optimal. For font sizes I personally prefer good old em. vw introduces unnecessary complexity and what appears as strange repainting behavior when the browser is resized.

**Comment by celloexpressions** [comment]
I like the idea; not sure about the caveats though.

**Comment by melchoyce** [comment]
> vw introduces unnecessary complexity ...

It is more complex — but also potentially a better responsive experience. It came up in a couple CSSConf presentations ([Stop Thinking in Pixels](https://www.youtube.com/watch?v=XanhwddQ-PM&list=PLlgxAbM67lYJRnZlE8nLsQAXxa4pGXO3I&index=1), [Bauhaus in the Browser](https://www.youtube.com/watch?v=BaQl84nDBNY&list=PLlgxAbM67lYJRnZlE8nLsQAXxa4pGXO3I&index=8)) and seemed like a good enhancement.

> ...and what appears as strange repainting behavior when the browser is resized.

How often do people resize their browser, though?

**Comment by mor10** [comment]
People who use Windows resize their browsers a lot. Actually, I do that on
my Mac too when I need to position content on my monitor.

In medias res on my paranoid android

**Comment by raoulwegat** [comment]
> How often do people resize their browser, though?

I do quite often. But when I do I normally expect the content to move around a bit as it's re-sized, so I suppose people are used to that. The thing is, will it be disconcerting to users when the type changes size as they re-size their window?

**Comment by melchoyce** [comment]
Don't know that I'm going to have time to experiment with this, so I'm going to close.
