### ISSUE TITLE
Support post formats?

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/twentyseventeen#110]
As a business-style theme, should Twenty Seventeen support post formats?

Would be really interested in everyone's thoughts on this :)

**Comment by melchoyce** [comment]
I've been very indecisive about post formats. I designed some in case we needed them, but I'm not sure as a business theme how much use they'd get. That said, I'm sure plenty of people will end up using Twenty Seventeen for blogging as well. Interested in hearing what others have to say.

**Comment by bappi** [comment]
I think it should. And I completely agree with @melchoyce on "I'm sure plenty of people will end up using Twenty Seventeen for blogging as well"

We should consider it.

**Comment by SilentComics** [comment]
Yes, underused perhaps, but useful. It could be helpful for people who are learning theme design as well.

**Comment by jocastaneda** [comment]
@melchoyce are there available mockups for post formats?

Honestly, as it's been said and will be said there are people who will use it for other things other than business. Shoot, even in some businesses they have specific stylings for different areas so why couldn't post formatting be applied to that?

**Comment by melchoyce** [comment]
Here's the latest mock with post formats:

![post list](https://cloud.githubusercontent.com/assets/2846578/18931012/6221edd8-8598-11e6-9344-2fd337daae1b.jpg)

Features standard with/without feature images, image format, video format, aside, and quote. I'm missing audio, link, and gallery. I don't think chat or status are particularly useful (and honestly wish we'd deprecate them... but that's a separate issue), so I think we should exclude them.

**Comment by davidakennedy** [comment]
In general, I'm not the hugest fan of post formats. I find they add the most value when a theme takes advantage of the majority of them. However, I know users will use this new default themes for all sorts of amazing sites. So it should be flexible. I'm in favor of adding the most popular ones that @melchoyce has in her mocks.

**Comment by asathoor** [comment]
Business theme or no: even a business might use blog posts in their communication. Therefore we need a post format. So:
- Yes.

**Comment by celloexpressions** [comment]
Post formats make sense if the design provides compelling reasons to use post formats, and they aren't treated as an afterthought. The mockup above is borderline on this for me. Ways to make it more compelling might include:
- A way to feature certain formats (maybe on the front page, which the menus approach to the multi-part page would enable, see also the Twenty Fourteen ephemera widget)
- Broader distinctions between formats (maybe images should be full-width, like the front page, with the image format?)
- If plugins provide additional functionality, such as a playlist of all recent audio posts' audio as a widget (the featured audio plugin does something similar)

**Comment by seraphyn** [comment]
Of course there should be post formats.
You could call it a theme for enterprise, but I'm more than shure, that some of my customers need them.

**Comment by melchoyce** [comment]
> You could call it a theme for enterprise, but I'm more than shure, that some of my customers need them.

@seraphyn, can you explain why your customers need post formats? How do they generally use them?

**Comment by seraphyn** [comment]
@melchoyce for sure.
One of my customers produce and sell jewellery worldwide and use wordpress as a multilanguage magazin.

For this customer, we make atm a redesign of the magazin and they will use postformats to show some of they videos, links to other magazins about jewellery  and of course pictures of the trade fairs they where and show some new pieces of the manufacturing.
Sometimes it is just an image without much text etc. 

I think they use it like any others using post formats.

Post formats fit perfectly here and are a starting point to use them in a childtheme,  a full article won't fit really in this place 

Twentyseventeen works as a landing page perfectly, but it lacks a small piece of work in the use of a blog and magazin. For me twentyseventeen should be a starting point like the other themes delivered by WordPress and not just as a landing page with standard article for enterprise.

I know it is not as hard to implement post formats types, but there should be a starting point in the theme for further customize. I know there has been a lot of discussions about Post Formats.

**Comment by melchoyce** [comment]
Closing because the answer was "yes" and @laurelfulford added support.
