### ISSUE TITLE
Wrong picture size as featured image

### ISSUE THREAD

**Issue by seraphyn** [WordPress/twentyseventeen#120]
As a featured image 2000x1200 ist used  as well, but it is resized to 614x369.

A.e 
/uploads/2016/06/IMG_20160320_130911-2000x1200.jpg is resized in HTML or CSS from 2000x1200 to 614x369. Serving a scaled image could save 509.4KiB (90% reduction).

**Comment by bappi** [comment]
@seraphyn  can you please elaborate the problem? I don't see any issue like that

**Comment by seraphyn** [comment]
@B-07 Switched for a small moment my theme to the new one, regenerate the pictures and wrote the new article about the anker headphones with the upload of a new picture.
This one should be regenerate as a featured image.

Had a look at the sizes in the sourcecode and made a GTMetrix as a example:
[https://gtmetrix.com/reports/got-tty.org/UgrUZ6Q8](https://gtmetrix.com/reports/got-tty.org/UgrUZ6Q8)

As you see

> https://got-tty.org/wp-content/uploads/2016/09/Anker_SoundBuds-2000x1200.jpg is resized in HTML or CSS from 2000x1200 to 614x369. Serving a scaled image could save 317.5KiB (90% reduction).

( I know not optimized, but this is not the prob atm, it is the size height and wide)

**Comment by mor10** [comment]
Is this still an issue? I believe it was resolved when the full design was implemented.

**Comment by laurelfulford** [comment]
This looks like it's still an issue -- I missed it when implementing the design.

On the blog index and archive pages, the each post's featured image displays at a maximum of 628px wide at the tablet breakpoint (and a bit smaller at 580px on desktop). 

Right now these images are using the `twentyseventeen-featured-image` image size (2000px by 1200px); adding an additional smaller image size for these cases should fix.

**Comment by mor10** [comment]
Right. In that case a custom function should be built to ensure the `sizes` attribute is set to the displayed width rather than the full viewport width. Something simar was done in Twenty Sixteen.
