### ISSUE TITLE
Version number in file headers

### ISSUE THREAD

**Issue by bappi** [WordPress/twentyseventeen#122]
Just noticed a few files don't have version numbers in their header like `funtions.php` and all files in `/inc` directory. Are there any specific reason for that or it need to be added?

**Comment by grappler** [comment]
@B-07 Do you mean `@version` or `@since`? Have you seen https://github.com/WordPress/twentyseventeen/issues/72 and https://github.com/WordPress/twentyseventeen/pull/86?

**Comment by bappi** [comment]
`@version` I saw #72 but the files I mentioned don't have this. Should I submit a PR for this?

**Comment by grappler** [comment]
The reasoning given is

> The files in inc are included via get_template_directory so they are not meant to be overridden via child theme and the functions.php is not overridden but an addition - so for my intended use case it is not necessary to add version number for these files.

Quoted from https://github.com/WordPress/twentyseventeen/pull/86#issuecomment-250615524

**Comment by bappi** [comment]
Okay that makes sense... thanks (y)
