### ISSUE TITLE
Join #HacktoberFest?

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/twentyseventeen#126]
Just a friendly suggestion, this repo should create a new label called #HacktoberFest to join [HacktoberFest](https://hacktoberfest.digitalocean.com/). WordPress is one of the most active open source scripts. Just because it is not actively developed on GitHub, it doesn't get included in a lot of surveys and what not. This theme is being developed here, though, maybe we can attract more contributors :)

**Comment by carl-alberto** [comment]
@ahmadawais This sounds interesting, looking forward for this.

**Comment by melchoyce** [comment]
Hey, while I like the idea, we're probably moving off of GitHub in the next week or so — so I'm not sure we're a great candidate, given our timeline.

**Comment by ahmadawais** [comment]
@melchoyce Moving off of GitHub? Why? What did I miss?

**Comment by melchoyce** [comment]
We need to move it over to SVN when the core merge window closes. GitHub was a temporary solution to make the bulk of the work easier to keep track of.

**Comment by ahmadawais** [comment]
Sure!
