### ISSUE TITLE
Browser test in target browsers

### ISSUE THREAD

**Issue by davidakennedy** [WordPress/twentyseventeen#13]
There is some [soft guidelines here](https://github.com/WordPress/twentysixteen/issues/6#issuecomment-137778618) to start with as far as browsers go.

**Comment by ntwb** [comment]
The comment I just added in #10 could do with repeating here:

There's a fairly comprehensive list of browser usage at http://caniuse.com/usage-table

Also WordPress #core uses Autoprefixer to dynamically create vendor prefixes based on the following devices: https://core.trac.wordpress.org/browser/trunk/Gruntfile.js#L27

``` js
'Android >= 2.1',
'Chrome >= 21',
'Edge >= 12',
'Explorer >= 7',
'Firefox >= 17',
'Opera >= 12.1',
'Safari >= 6.0'
```

**Comment by melchoyce** [comment]
Closing in favor of #388.
