### ISSUE TITLE
Better gallery styling

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#133]
The current gallery styles are pretty overwhelming. Can we come up with something that feels more designed, to show off galleries in the default theme?

**Comment by jordesign** [comment]
FWIW - I'd be happy to be involved in this if it gets approved

**Comment by melchoyce** [comment]
Here's what it looks like now:

<img width="1240" alt="screen shot 2016-10-05 at 11 09 36 am" src="https://cloud.githubusercontent.com/assets/2846578/19119016/52cea6c4-8aec-11e6-87a8-1d365f6e3cce.png">

Definitely needs some more design love. @jordesign want to work on it?

**Comment by jordesign** [comment]
Thanks @melchoyce I'd definitely be keen :)  What would be the best way to start - do we want a visua mocked up - or just go straight to code?

**Comment by melchoyce** [comment]
@jordesign Whichever you're more comfortable with is fine :)

If you do a PR, be sure to add some before/after screenshots. Thanks!

**Comment by joyously** [comment]
And add captions on only some of the images, to make sure that looks right with/without.
May I suggest a bit of  box-shadow on the images?

**Comment by jordesign** [comment]
yeah - i'm not a fan of the underline on images (could just be a link style) - I'll work on something else

**Comment by melchoyce** [comment]
Yeah, pretty sure the underlines are just inherited link styles. 

You can see regular image caption styles here: https://cloudup.com/i12Io343Dr7

**Comment by jordesign** [comment]
Have just issued a PR #201  - is this the right place to reference that?

**Comment by joyously** [comment]
Does this issue cover both a plain gallery and a gallery post format?
I have a gallery post format post that only shows partial content on the home page when all other posts show full content. And then when I view that post singularly, it puts the featured image huge on top as the header image and then again at the beginning of the post.

**Comment by jordesign** [comment]
@joyously I didn't look at the post format specifically - just the plain gallery.
More than happy to take a look at it though - don't know if its appropriate for it to be tacked onto this task, or needs another one? 

The example you're mentioning what happens for you currently with twentyseventeen - or the behaviour of another theme somewhere?

**Comment by joyously** [comment]
My example was with twentyseventeen.

**Comment by jordesign** [comment]
@joyously Im not getting that behaviour by default for some reason - but it _is_ happening when a feature image is defined.

Might open that as a separate issue - and leave this one as is.
