### ISSUE TITLE
Update bundled header image

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#134]
There is currently a "suggested" header image, but it isn't used by default. Should there be a header image by default? Is it worth bundling an image if it isn't shown by default?

This image is also probably leftover from Lodestar; it doesn't fit in with Twenty Seventeen as well. It also doesn't display currently; guessing this is pending the header video work.

**Comment by davidakennedy** [comment]
@celloexpressions Right, this is primarily left over from Lodestar, and has been on my mental list...

I think we should have one, particularly if video headers happen, it could serve as a nice packaged fallback.

If we do have one, it needs to be registered properly so child themes can remove it, etc.

I'd be open to suggestions for a default header image. @melchoyce probably has some thoughts too.

**Comment by melchoyce** [comment]
Bundling a video could be rad, but I'd want it to be a super super small filesize so we're not causing any sort of bloat. Like, as small as any high-quality image we'd bundle instead.

**Comment by celloexpressions** [comment]
I like the idea of having the default image (and also maybe video) used by default, with users being able to turn it off or change to something custom.

Since this image will be used widely, it would be cool to create something custom for this theme (presumably a photograph and maybe also a video). Maybe if @melchoyce can propose some possible ideas, we can see if anyone in the community is willing to donate resources to select from?

**Comment by melchoyce** [comment]
Since we're gearing Twenty Seventeen towards businesses, it could make sense to use a video/photo that focus on that fact. 

For example, here are some agency websites that use video headers:
- http://bravepeople.co/
- http://demodern.com/
- http://bluestag.co.uk/
- https://union.co/
- http://www.bukwild.com/
- The video toward the bottom of http://www.uzik.com/ is also a good example

So maybe:
- Focused on a static element in the foreground of an office, for example a vase on a table or a desk, with out-of-focus people occasionally walking around or shifting in the background
- Sharp and clean photographs of offices (similar to [this](https://www.pexels.com/photo/conference-meeting-room-chairs-table-28756/), or [this](https://www.pexels.com/photo/office-table-windows-chairs-94578/), or [this](https://www.pexels.com/photo/man-desk-notebook-office-7060/)) — especially if the lower left is less busy.

**Comment by melchoyce** [comment]
Here's an example of a video that could work: https://videos.pexels.com/videos/blurry-video-of-people-working-774

**Comment by jordesign** [comment]
http://coverr.co/ would have some good examples

**Comment by celloexpressions** [comment]
I think the video examples there are closer to what we'd want than those images, which come off as a bit too cold for the default to me. A good example video header I came across is http://bora.co/studio/.

This is a hard question and there are a lot of things to consider:
- Due to the file size limitations, it may be necessary to have an image only by default. We need an image either way as the fallback if there is a video.
- A business theme should be able to be used by businesses in any industry; how does the default header enable businesses with wildly different purposes to see how the functionality could be useful for them?
- Regarding the above, I'm not sure whether office-focused visuals will resonate with a majority of the types of small businesses  who are likely to see this, setting up their own site with WordPress. If you were building a site for your business, would you lead with footage of people working in your office? The answer depends heavily on the industry,
- Including people or plants makes it feel more relatable than an empty interior shot. However, if people are visible, we need to consider that they may not be culturally relatable for global WordPress users.
- While something more generic would be easier for more people to relate to, the default header should convey meaning. This is challenging without a specific know use for the site (such as the visualization of the architecture firm's process in the site I linked above). But I think we can come up with something that suggests _something_ visually.
- In addition to visually-conveyed meaning, it would be nice if there were some meaning to the WordPress project hidden inside it. If we go the office route, maybe we could leverage footage from a WordCamp contributor day. Or maybe we see physical WordPress logos in the space depicted, or a site running Twenty Seventeen on any visible computer screens.
- The theme screenshot will largely be this image/video, with some text and maybe a logo over it and maybe also the menu.
- This will be the first thing that anyone installing a clean copy of WordPress sees on the front end of their site for the next year.
- Because this will be so visible so early in users' experience with WordPress, it needs to be approachable, inviting, and inspiring. Users should feel inspired to leverage their own content here or build on the default.

**Comment by joyously** [comment]
You give many good reasons to use a cartoon, or no video at all.

**Comment by davidakennedy** [comment]
If video headers make it to Core, they will likely not have the ability to set a default video, which means Twenty Seventeen should not bundle a video. If it did, it would be considered content, which is a no go in a theme.

The default header should be updated though.

**Comment by melchoyce** [comment]
Good to know, thanks for the update @davidakennedy 👍

**Comment by melchoyce** [comment]
Some ideas for a bundled image:

![screen shot 2016-10-14 at 12 55 33 am](https://cloud.githubusercontent.com/assets/2846578/19376122/f339d030-91a8-11e6-8cd3-e07c734af506.png)

![screen shot 2016-10-14 at 12 55 59 am](https://cloud.githubusercontent.com/assets/2846578/19376127/0563e9a8-91a9-11e6-950c-23b6562faa27.png)

![screen shot 2016-10-14 at 12 56 47 am](https://cloud.githubusercontent.com/assets/2846578/19376141/207db976-91a9-11e6-92e7-454bed214ea2.png)
(I like the layout on this one but not the color saturation and graininess)

**Comment by celloexpressions** [comment]
At first glance, I preferred the first one overall, visually. After some thought, I also realized that the first one is the closest to what we'd want because it implies less of a "tech" bias than the second two. Its meaning is somewhat broad, but it feels like it does have meaning, and being somewhat imperfect, it feels accessible. It generally responds well to the considerations I posted previously.

The visible wood grain and presence of plants in the first and third image work well alongside the "Twenty Seventeen brings your site to life" opening to the theme description. I might like slightly more focus on the wood in the first one, but the colors are just about right.

The first image is a bit busy on the left, especially with the header text and potentially a logo. I think flipping it horizontally would work really well. That also orients its content along a linear axis pointing up and to the right, implying positive forward progress.

**Comment by melchoyce** [comment]
![screen shot 2016-10-14 at 10 02 53 am](https://cloud.githubusercontent.com/assets/2846578/19390295/6b8a4d7a-91f5-11e6-80c6-73ff469d81c3.png)

**Comment by celloexpressions** [comment]
I think that's the one (assuming licensing is compatible). Let's get it in!

**Comment by melchoyce** [comment]
Yup, it's from Unsplash: https://unsplash.com/@englr?photo=bIhpiQA009k

Here's a high quality version of the image, flipped and cropped: https://cloudup.com/crpvxvfwAMT

**Comment by davidakennedy** [comment]
A++ on that image. Let's make sure we credit it in the readme.
