### ISSUE TITLE
Remove or improve custom background image support

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#135]
The background image is currently displayed directly behind text, which will not look good in most cases and is likely to cause color contrast issues since the text color barely has enough contrast against the default white backgrounds. 

Is there a compelling reason to have background image support here? Should the background image be shown elsewhere, without having text directly on top of it? Since this is a bundled theme, a lot of users will try a lot of different types of images here, and being directly behind the text is generally unexpected behavior. The only use I can think of for the current implementation is a very light textured background, but most users will not have appropriate images handy for this, and color contrast is an issue.

**Comment by davidakennedy** [comment]
Great point, @celloexpressions! With default themes, I always like to see them take advantage of as much of WordPress' default functionality as possible. It gives users more flexibility to get creative.

That said, that might require some design tweaks to the theme. I'm curious what @melchoyce thinks about this.

**Comment by melchoyce** [comment]
Yeah, background images don't work as well on full-width layouts. While I'm all for taking advantage of everything WordPress has to offer, I'm not sure this is a great theme for backgrounds.

Only thing I'd suggest to get it to work is to keep a 90-95% opaque solid color (like white) layered on top of the background image — but that takes away some presentation control from folks using the theme. Almost seems better at that point to exclude background images.

**Comment by celloexpressions** [comment]
Not every theme needs to (or should) support every core feature, especially if it provides a bad experience out of the box. Users shouldn't be able to make their site unreadable with the options in the customizer.

But, I agree that it would be nice to support it, especially since we're refreshing the feature in 4.7 with https://core.trac.wordpress.org/ticket/22058. We just need to find the right place for it.

**Comment by davidakennedy** [comment]
Yeah, it sounds like it's not a great fit for this theme, and I'm okay with that. I just wanted to have it considered. I would agree that I'd rather leave something out if most users may have a chance to make something not look like what they want.

Let's remove it.

**Comment by joshcummingsdesign** [comment]
Submitted pull request #265 for this issue.
