### ISSUE TITLE
Consider better audio, video, and playlist styling

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#137]
Audio and video players currently use the default styles. Past default themes have customized at least the colors somewhat; we should consider doing that here as well.

Audio (and presumably also video) playlists don't look very good right now. I think some added spacing would go a long way, as well as fixing the borders and potentially rethinking the focus styles inherited from other theme elements.

![twentyseventeen-audio-playlist](https://cloud.githubusercontent.com/assets/7875961/19100106/b8e85404-8a70-11e6-8dc5-8974ed0c5217.png)

**Comment by melchoyce** [comment]
Video playlist: 
<img width="616" alt="screen shot 2016-10-05 at 6 26 39 pm" src="https://cloud.githubusercontent.com/assets/2846578/19134009/53d104da-8b29-11e6-8197-575204806836.png">

**Comment by joyously** [comment]
Would you be opposed to using a 1px dotted border instead of a solid line? That way it is there to lead your eye across, but not so harshly.

**Comment by melchoyce** [comment]
Up for anything. If no one else grabs this in a couple days, I'll mock something up.
