### ISSUE TITLE
Remove 3rd party widget styles

### ISSUE THREAD

**Issue by josephfusco** [WordPress/twentyseventeen#138]
The default theme should not favor any third party plugins to improve how they look/offer support as it would be unfair to other plugins.

This seems to be a remnant from Lodestar: https://github.com/WordPress/twentyseventeen/blob/master/style.css#L1985-L2006

**Comment by celloexpressions** [comment]
+1 I noticed this today as well.

**Comment by Nikschavan** [comment]
+1, I will be happy to work on a PR for this.
