### ISSUE TITLE
Site navigation is causing unnecessary browser repaints

### ISSUE THREAD

**Issue by josephfusco** [WordPress/twentyseventeen#140]
The slide out behavior of the fixed navigation is causing what I would consider to be a noticeable drop in frames per second from a full screen paint. You may also notice some lag when initially scrolling down the page. This will be even more noticeable with people who come across this theme on outdated hardware.

IMO the fixed behavior is a little janky itself but that can be another issue.

<img width="929" alt="screen shot 2016-10-05 at 12 30 35 am" src="https://cloud.githubusercontent.com/assets/6676674/19101161/9c9f39e8-8a93-11e6-828a-df47b06c1ef3.png">

For more information on paints see [this write up on html5rocks](https://www.html5rocks.com/en/tutorials/speed/unnecessary-paints/).

I can tackle the PR for this but wanted to have an issue up first.

[See screencast (20MB No Audio)](https://www.dropbox.com/s/yfsw6e472y9hp61/twentyseventeen-paint-issue.mov?dl=0) (FPS should ideally be around 60FPS but while recording it was cut in half to 30FPS so ignore that)

**Comment by davidakennedy** [comment]
Thanks for the reporting this @josephfusco! I'm happy to have a pull request to help improve this.

**Comment by allancole** [comment]
> IMO the fixed behavior is a little janky itself but that can be another issue.

Agreed on this point mostly and I imagine refactoring that part of UI would solve the frame rate issue as well. Not 100% sure, though.

**Comment by josephfusco** [comment]
Keeping this on hold until PR #151 is merged as it fixes a lot of this.

**Comment by allancole** [comment]
Ahhh, good to know! I’m a little late to the party on this. Thanks!

**Comment by melchoyce** [comment]
Fixed in #151.
