### ISSUE TITLE
Duplicate section title

### ISSUE THREAD

**Issue by josephfusco** [WordPress/twentyseventeen#142]
<img width="491" alt="screen shot 2016-10-05 at 12 48 05 am" src="https://cloud.githubusercontent.com/assets/6676674/19101333/6c650382-8a95-11e6-97d1-fb072a147704.png">

See: https://github.com/WordPress/twentyseventeen/blob/master/style.css#L582-L588

**Comment by tsl143** [comment]
Hi Maintainers,

Kindly review https://github.com/WordPress/twentyseventeen/pull/148
