### ISSUE TITLE
Fix Table of Contents

### ISSUE THREAD

**Issue by josephfusco** [WordPress/twentyseventeen#143]
General clean up of the TOC and corresponding section & sub section titles. Some sections are either mislabeled, missing, or should not be there all together.

Example: [# Buttons is in the TOC](https://github.com/WordPress/twentyseventeen/blob/master/style.css#L26) but there is no marked section for it.

**Comment by davidakennedy** [comment]
Thanks for the issue @josephfusco. I'm open to changes now, or waiting on this as part of #12.
