### ISSUE TITLE
Customizer preview issue with site title.

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/twentyseventeen#145]
When we check display site title option then site title is not visible in customize. As shown in the video below.
Video Url: http://bsf.io/5g2yf

**Comment by BharatKaravadra** [comment]
This may be related... when adding an image logo to the site header, then unchecking the "Display Site Title and Tagline" to off, the title and tagline are not displayed which is correct.

However, when the display is checked again, the title does not appear and the tagline appears in black -- a different colour than the default.

See http://youtu.be/1OHnQnXdc3k

The title and description however appear OK on the user side.

**Comment by Swapnildhanrale** [comment]
Also for me, the header background image is not working. As shown in the screenshot below.
Screenshot Url: http://bsf.io/8gka-

**Comment by davidakennedy** [comment]
Thanks for the issue @Swapnildhanrale!
