### ISSUE TITLE
Positioning & Rendering of <!--more--> tag

### ISSUE THREAD

**Issue by BharatKaravadra** [WordPress/twentyseventeen#147]
1) When the  is inserted directly after the last character of a sentence using the WYSIWYG editor, the "Continue reading →" link appears at the end of the sentence in the archives view.

2) When the  is inserted on a new line it appears on a new line.

I am not sure of the first option above also should render the "Continue reading →" link on a new line, but I am submitting this as I have noticed on some WordPress installations that the first option also renders the "Continue reading → on a new line.

**Comment by melchoyce** [comment]
New line makes more sense to me — that way there's no chance of it awkwardly cutting off between words, or between the words and the arrow.

**Comment by joshcummingsdesign** [comment]
Created a pull request #172 that should resolve this
