### ISSUE TITLE
Too many menu items causes the theme to be unusable on desktop

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/twentyseventeen#150]
When a user has a lot of top level menu items, you no longer can see the content due top the stickyness of the menu.  My example test has 101 top level menu items

![screen shot 2016-10-05 at 4 59 15 pm](https://cloud.githubusercontent.com/assets/622599/19131364/1feedc02-8b1d-11e6-831a-2bf24df89d74.png)

![screen shot 2016-10-05 at 4 59 20 pm](https://cloud.githubusercontent.com/assets/622599/19131363/1feab460-8b1d-11e6-8470-d490957c62de.png)

**Comment by aaronjorbin** [comment]
[slack conversation discussing if this is a bug or a feature](https://wordpress.slack.com/archives/core-themes/p1475700798001869)

**Comment by davidakennedy** [comment]
As mentioned in Slack, a good way to approach this is perhaps not to have the menu be fixed if it has a certain number of items or reaches beyond two lines.

**Comment by joyously** [comment]
You might be interested in this:
http://lea.verou.me/2011/01/styling-children-based-on-their-number-with-css3/

**Comment by joshcummingsdesign** [comment]
Created a pull request #168 as a possible solution
