### ISSUE TITLE
Header background image is not working.

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/twentyseventeen#156]
The header background image is only working with the static home page and not working for another page. As shown in the screenshot below.
Screenshot Url: http://bsf.io/s1mpr

**Comment by Swapnildhanrale** [comment]
For better understanding please check the video below.
Video Url: http://bsf.io/1zpc2

**Comment by grappler** [comment]
Is this issue related to https://github.com/WordPress/twentyseventeen/issues/132?

**Comment by Swapnildhanrale** [comment]
Yes @grappler ...

**Comment by melchoyce** [comment]
Closing as duplicate.
