### ISSUE TITLE
Header text color issue.

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/twentyseventeen#157]
The header text color option is not saved in customizer as shown in the video below.Please check the video below.
Video Url: http://bsf.io/mvpor

**Comment by Swapnildhanrale** [comment]
@davidakennedy Where I can check the issue...?

**Comment by davidakennedy** [comment]
@Swapnildhanrale I have a new pull request now in #198. I thought this had a PR earlier, but that was another custom header related issue. Sorry for the confusion.
