### ISSUE TITLE
Last LI in footer widgets lacks padding

### ISSUE THREAD

**Issue by sixhours** [WordPress/twentyseventeen#158]
https://cloudup.com/i2Ld3-tGY8i

I was also unsure if the underlined links with underlined list items was an intentional design decision or a bug; that's a lot of lines.

**Comment by josephfusco** [comment]
@sixhours 

+1 on the lack of padding. It feels off.

I am not seeing underlined links in the sidebar though. Just the color change on :hover.

![screen shot 2016-10-06 at 10 37 07 am](https://cloud.githubusercontent.com/assets/6676674/19156836/360632d0-8bb1-11e6-9571-3c1fab101ea2.png)

**Comment by davidakennedy** [comment]
Some design iteration could happen here, most likely. Every widget wasn't mocked up. @melchoyce Want to take a look?

**Comment by enodekciw** [comment]
@josephfusco 
Only the links in footer are being underlined. It gets even worse with `<abbr>` on 'RSS'

![2017-widgets](https://cloud.githubusercontent.com/assets/2080743/19169418/16fab32c-8c1d-11e6-8ce1-abfbb1216f43.jpg)

**Comment by josephfusco** [comment]
Ah! Thanks for the clarification @enodekciw. 👍

**Comment by jordesign** [comment]
Added PR #235 to address the underline in footer items and also the visual clash of the abbr underline
