### ISSUE TITLE
"Featured" tag has a black bottom border

### ISSUE THREAD

**Issue by sixhours** [WordPress/twentyseventeen#159]
https://cloudup.com/iC2j5vrUvqL

This is also the tag I have set for Jetpack Featured Content, so that might have something to do with it.

**Comment by davidakennedy** [comment]
@sixhours Thanks for the issue! That's a `:visited` link style. So not really a bug, but some design iteration may be needed for widgets.

**Comment by melchoyce** [comment]
Let's remove the `:visited:` link style.
