### ISSUE TITLE
Submenu outline is very faint

### ISSUE THREAD

**Issue by sixhours** [WordPress/twentyseventeen#160]
This one's subjective, but I find the outline here hard to see. 

https://cloudup.com/i5oUKzXX6AY

**Comment by davidakennedy** [comment]
Thanks @sixhours, you mean the border... This one would be good for @melchoyce to comment on.

**Comment by melchoyce** [comment]
Yeah, let's bump that up to `#bbb` instead.

**Comment by ghost** [comment]
- Changed submenu border color from #eee => #ddd
- There was an issue with triangle color as well its position - I have fixed it too - http://bsf.io/41xbm

**Comment by laurelfulford** [comment]
Fixed - have merged in #178.
