### ISSUE TITLE
Post date, title, and content vertically misaligned

### ISSUE THREAD

**Issue by sixhours** [WordPress/twentyseventeen#162]
https://cloudup.com/ir9lJbm0BFR

There's a very slight indent on the post title; it may be the fonts used don't line up to the grid well, but this jumped out at me.

**Comment by akshayvinchurkar** [comment]
i add small margin on left side and its good to go

**Comment by melchoyce** [comment]
Hey @akshayvinchurkar, would you mind submitting your changes as a [pull request](https://help.github.com/articles/about-pull-requests/)?

**Comment by melchoyce** [comment]
Nevermind, for some reason they weren't linked. PR is #186.
