### ISSUE TITLE
Horizontal scroll on narrow screens in Customizer when using a Static Front Page.

### ISSUE THREAD

**Issue by sixhours** [WordPress/twentyseventeen#163]
https://cloudup.com/iWgKvz9M5lN

Steps to reproduce:
- Open the theme in the Customizer.
- Set a static front page.
- Narrow screen to 1278px or less.
- Don't scroll down; this only happens when the menu is _not_ stuck to the top.

Using Chrome 53, but it's happening in Firefox as well.

**Comment by ghost** [comment]
There were issues with menu scroll down arrow due to transform rotate property - http://take.ms/XylZ9

I have fixed this issue by adding line height: 1 to genericons. By default - for button tag line height 1.5 is applying & its causing issues to increase the width of scroll down arrow.

Now scrollbar is removed - http://take.ms/fFaN5

**Comment by melchoyce** [comment]
Would this be fixed by #206?

**Comment by ghost** [comment]
@melchoyce Above reported issue can fixed by this PR - https://github.com/WordPress/twentyseventeen/pull/253

Please close this issue as well as PR submitted by me - https://github.com/WordPress/twentyseventeen/pull/179

Thanks for pointing this!

**Comment by samikeijonen** [comment]
I can't reproduce this in #253. But I can see horizontal scroll when I have Query Monitor plugin active.

@sixhours can you double check that this is not the case?

**Comment by sixhours** [comment]
Nope, I don't have that plugin.

**Comment by samikeijonen** [comment]
Did you test it on #253?

**Comment by melchoyce** [comment]
I can't reproduce this. Maybe fixed by #206?

**Comment by laurelfulford** [comment]
I was able to reproduce this in the master branch. It looks like it's resolved in #253 for me.

**Comment by laurelfulford** [comment]
Fixed in #322.
