### ISSUE TITLE
Sticky menu vertical alignment with content

### ISSUE THREAD

**Issue by sixhours** [WordPress/twentyseventeen#165]
https://cloudup.com/iaitqWc-gER

On narrow screens (~1070px wide and below) the sticky menu's left and right margins differ from the content to the point where this stood out to me. It would be nice if the menu and content could line up vertically.

**Comment by akshayvinchurkar** [comment]
this is happening because of this rule

_,
*:before,
*:after {
    /_ Inherit box-sizing to make it easier to change the property for components that leverage other behavior; see http://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/ */
    box-sizing: inherit;
}

but css tricks shows that this is best practice i made a change in pull request

**Comment by akshayvinchurkar** [comment]
Because navbar and main container does not share same wrapper that's why this is happening.

**Comment by joshcummingsdesign** [comment]
#284 Should fix this
