### ISSUE TITLE
RSS widget could use more breathing room between lines

### ISSUE THREAD

**Issue by sixhours** [WordPress/twentyseventeen#166]
https://cloudup.com/ivcIxAc1FDX

Readability could be improved with some spacing between the post title, date, and content.

**Comment by leobaiano** [comment]
I did a test here including a margin of 10px between items. But my aesthetic sense is not so determined, see looks better please. 😄 

![screen shot 2016-10-06 at 1 53 56 pm](https://cloud.githubusercontent.com/assets/957257/19162055/ac61348c-8bcc-11e6-8c65-7e42691215e4.png)

**Comment by enodekciw** [comment]
Just submitted #175

This is how it looks with 0.75em margins on .rss-date and 0.75em bottom margin on .rssSummary
![2017-rss](https://cloud.githubusercontent.com/assets/2080743/19169086/8704fb84-8c1b-11e6-8c10-89f9c252e125.jpg)

**Comment by leobaiano** [comment]
How the issues of assignees system here?

**Comment by davidakennedy** [comment]
@leobaiano Welcome! If you see an issue you want to take on, just create a pull request and reference the issue number in it. It's first come, first serve. If you have any questions, you can ask in `core-themes` in the WordPress Slack. Thanks!

**Comment by melchoyce** [comment]
Mocked up a version of the widget that brings it closer to how posts look on static front pages:

![rss widget](https://cloud.githubusercontent.com/assets/2846578/19375495/bcb6143e-91a2-11e6-8242-24235c6e214a.jpg)

@enodekciw if you're interested in coding it up, easiest way to communicate styles is either by sending you the Sketch file, or through Zeplin. Let me know if you want to do Zeplin and DM me your email on WordPress Slack (I'm melchoyce there too) and I'll invite you to the project.

**Comment by laurelfulford** [comment]
Fixed in #175.
