### ISSUE TITLE
CSS Comments

### ISSUE THREAD

**Issue by marcustisater** [WordPress/twentyseventeen#170]
Follow up from #12. When I went through the stylesheet I noticed that there were a lot of comments, all very differently presented. Here is an example:

Comment inside an selector, also more then 80 characters long in one line:

```
*,
*:before,
*:after {
    /* Inherit box-sizing to make it easier to change the propert for components that leverage other behavior; see http://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice */
    box-sizing: inherit;
}
```

Comment written as an section but there were only one selector presented, also presented wrong.

```
/* Hide the menu on small screens when JavaScript is available.
 * It only works with JavaScript.
 */

.js .main-navigation ul {
    display: none;
}
```

Most of the comments are presented very differently and not accordingly to the WordPress CSS Coding Standards. It's also very difficult to compare sections vs subsections and specific comments for certain selectors. 

This is [how](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#commenting) you write comments according to the [WordPress CSS Comment Code Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css). I think we should follow these standards.

I think someone needs to double check if the table of contents match the comments in the stylesheet as well.

**Comment by marcustisater** [comment]
I would be happy to offer help 😄  but... I don't want to end up with coming back to resolving this issue again, I think we need to be stricter with the PR now as the stylesheets gets bigger and bigger.

**Comment by marcustisater** [comment]
#12

**Comment by davidakennedy** [comment]
@marcustisater Thanks for the issues. Having some regressions is probably my fault but bound to happen with the giant design-related pull request merged in a few days ago.

I don't envision too many more giant pull requests, so it should get easier.

That said, I think it's good to keep this kind of stuff to #12. That way, it's all in one place. Feel free to make a pull request and reference that issue.

I'm going to close this and add your thoughts there.
