### ISSUE TITLE
CSS Vendor prefixing

### ISSUE THREAD

**Issue by marcustisater** [WordPress/twentyseventeen#171]
I'm sorry if this is an inappropriate issue to create/ask.

How many versions back do we go with auto prefixing properties? It's a little bit fuzzy for me as I read through the [WordPress CSS Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#vendor-prefixes). Can someone explain this to me so I can go through our stylesheet to correct all the prefixes. Thanks!

**Comment by josephfusco** [comment]
@marcustisater I believe through IE9 as we should have a [separate stylesheet for IE8](https://github.com/WordPress/twentyseventeen/blob/master/assets/css/ie8.css). Twenty Sixteen also has an [IE7 specific stylesheet](https://github.com/WordPress/twentysixteen/blob/master/css/ie7.css) but maybe we have dropped that off as we are another year past that?

**Comment by marcustisater** [comment]
Thanks, I didn't go through the assets folder (explains a lot 😅 ). I'm not sure about IE7 but since it's not supported anymore I don't see why we should make another specific stylesheet for it.

**Comment by davidakennedy** [comment]
@marcustisater Thanks for the issue!

See #13 for some context. This would be also related to #12. IE 9 and up should be solid as well.

**Comment by marcustisater** [comment]
Sounds good, @ntwb PR solved my concern.

**Comment by davidakennedy** [comment]
Taken care of in #475.
