### ISSUE TITLE
Utilise get_theme_file_uri()

### ISSUE THREAD

**Issue by johnbillion** [WordPress/twentyseventeen#176]
In WordPress 4.7, the new [`get_theme_file_uri()` function](https://make.wordpress.org/core/2016/09/09/new-functions-hooks-and-behaviour-for-theme-developers-in-wordpress-4-7/) is being introduced. This greatly improves the child theming process.

Unless TwentySeventeen is going to be backwards compatibile with WordPress < 4.7, this function should be used when enqueuing CSS and JS files from the theme.

**Comment by davidakennedy** [comment]
@johnbillion I'm totally for this. It means we'll need a `back-compat.php`, but that's okay. I think default themes should try and show the latest and greatest WordPress has to offer, no matter the feature.

**Comment by joshcummingsdesign** [comment]
Opened PR #287 for this enhancement
