### ISSUE TITLE
Comment Box size on small devices

### ISSUE THREAD

**Issue by akshayvinchurkar** [WordPress/twentyseventeen#184]
![issue](https://cloud.githubusercontent.com/assets/10510889/19181260/76c46dae-8c89-11e6-89a0-af66289b6953.png)

**Comment by akshayvinchurkar** [comment]
actually that text-area has parent of p if i specify the size of p tag to 97% that would fix it shortly but this is not a good idea to hack it like this so file the issue

**Comment by enodekciw** [comment]
Cannot reproduce the issue.
Doesn't matter on what screen size I check it - looks good on both Chrome and Firefox.
