### ISSUE TITLE
Header on non-front pages

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#189]
Currently the header image (eventually video) is only shown on the front page. However, on inner pages, the header feels a bit plain/empty, especially when a logo is in use:

![twentyseventeen-inner-header](https://cloud.githubusercontent.com/assets/7875961/19192441/1cedd4ba-8c5b-11e6-85d6-ba88fa1765f1.png)

(note: that's also using custom colors from #116)

It feels a bit like wasted space, especially relative to the dramatic size of the featured image below. Could we float the logo when present on larger screens here? Is there a way to either condense the amount of space the header takes, or add visual interest here? It might be nice to have a smaller header image here on inner pages, but it might distract from the featured image below.

**Comment by davidakennedy** [comment]
This would be a good one to have @melchoyce weigh in on.

**Comment by melchoyce** [comment]
I was actually thinking about this when @laurelfulford and I first chatted about logo support, but I'm worried about how super wide logos would look next to the title/tagline. Debating which is the lesser of two evils here and kind of torn, since neither option is particularly great — but displaying a title/tagline is a user choice.

**Comment by celloexpressions** [comment]
If it's floated, the text would drop down if it's too long to fit, but maybe it would also make sense to give the logo a max height and width in this scenario to make it look better?

**Comment by melchoyce** [comment]
Is there some combination of CSS selectors that would let us scale down the logo if there's a title/tagline present, but let it default to its current max-width if the title/tagline are hidden?

**Comment by paaljoachim** [comment]
To me it sounds like there are specifics with header front page and header the rest of the site.
Giving the customizable option for the user to define header media - image or video front page. Then header rest of the site. Having controls that makes it obvious for the user that they first define the front page header and then right below define it for the site in general.

**Comment by paaljoachim** [comment]
Another usage of the non front page header images could be as featured images that show the title of the page/post. Something similar to this:

![full-width-featured-image-behind-title-wordpress](https://cloud.githubusercontent.com/assets/5323259/19257579/a660aeda-8f3e-11e6-9ebc-d683c463a5ea.jpg)

**Comment by celloexpressions** [comment]
@melchoyce mentioned wanting to address this before #119, so it needs to be in the core merge milestone.

**Comment by celloexpressions** [comment]
Superseded by #413.
