### ISSUE TITLE
Feature media content

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#190]
There were some mentions of possible featured media support in the initial meeting for the theme design. Can we explore what that might look like?

It's currently possible to get media from within `the_content` without adding featured media functionality to core. There is a [featured audio plugin](https://wordpress.org/plugins/featured-audio/) that the theme could support, potentially along other media-specific featured media plugins, or perhaps we can create a generic featured media plugin that the theme could support when it's present. Any of the plugins would be intended for eventual core consideration.

We could also do subtle things with the left sidebar space, for example. Wouldn't it be cool to automatically put together an audio playlist of audio within a post on posts with multiple audio players? Or if post formats are in use, if there's a video in the content of a video format post we could pull that out and display it in place of the featured image like the front page header image.

If we start with the design ideas for what ideally might be supported, we can look at what is feasible in the current timeframe without major core changes or excessive code in the theme.

**Comment by davidakennedy** [comment]
@celloexpressions I really like this idea, particularly because I like the idea of featured media on the whole.

That said, this would be low on the priority list for me in Twenty Seventeen, given some of the other things the theme is trying to accomplish – like video headers and multi-panel front page. Media, to me, is less of a focus for this default theme even though users will use it in all sorts of ways.

I'd be curious what @melchoyce and others think as well.

**Comment by melchoyce** [comment]
If it works in such a way that we don't need to make any new UI for it ([like this](https://cloudup.com/iKT15ljSQgH)) and doesn't detract attention from the stuff that needs to get in, I think it would be good. Worried about time, though.

**Comment by celloexpressions** [comment]
Yeah, I don't think the core part would work with the timing we have, but on the theme end we can still do things without UI, but getting the media from the content and potentially integrating that with post formats. In that case, setting a post format could essentially tell the theme to treat that format of content as "featured".

Do you have design ideas for the theme side of it, or exactly what we'd want to use it for?

**Comment by GaryBairead** [comment]
Do you mean something like the media grabber in Hybrid core? - https://github.com/justintadlock/hybrid-core/blob/master/inc/class-media-grabber.php

For example, if a user adds a Youtube video to the content of a _video post format_, the media grabber can extract that from the content area and display it in a different position defined by the theme author.

 The same can be done with audio or galleries.

**Comment by melchoyce** [comment]
The post format mockups kind of already do that: https://cloudup.com/ih0VLcldm_u

**Comment by celloexpressions** [comment]
I was thinking more about single pages with this issue, but if there aren't any major ideas beyond the current setup we can close this.

**Comment by melchoyce** [comment]
Yeah, going to close this one. Great idea, not a lot of time. Could be cool to see in Twenty Eighteen. :)
