### ISSUE TITLE
Social menu: no icon when service is not supported

### ISSUE THREAD

**Issue by mor10** [WordPress/twentyseventeen#191]
The social media menu should fall back to a generic icon when a random link is added. Right now it displays an empty link.

**Comment by davidakennedy** [comment]
Thanks for the issue @mor10!

It should – and a fallback should be in place if the theme moves to SVGs. Related: #60.

**Comment by mor10** [comment]
It's a simple fix, as shown in the PR: Just call a default icon until another is specified.

**Comment by laurelfulford** [comment]
Fixed in #322.
