### ISSUE TITLE
Restructure style.css to place media queries at component level

### ISSUE THREAD

**Issue by mor10** [WordPress/twentyseventeen#194]
In the current iteration all media queries are presented at the bottom of the stylesheet. This causes performance issues and makes it hard to maintain the style rules.

Browsers are implementing a new rendering engine that paints content as CSS is encountered rather than waiting for the whole stylesheet to load. By placing all the media queries at the bottom, users on slow connections will experience page repainting and layout realignment during load.

Current best practice is to place media queries at or close to their affected components. I propose restructuring style.css to follow this practice.

In the process, it would also be a good idea to restructure the rules to correspond with page load hierarchy -> header, main nav, content, footer, etc.

**Comment by mor10** [comment]
More on browsers painting CSS progressively during load:
https://jakearchibald.com/2016/link-in-body/

**Comment by davidakennedy** [comment]
@mor10 Thanks for the issue!

I'm inclined to agree here. Related: #12.

**Comment by mor10** [comment]
IMO this restructuring would not be piecemal and would require some sort of freeze on other PRs until it's complete, otherwise things will get chaotic

**Comment by ntwb** [comment]
The coding standards PR #169 is 99.9% complete, it could be merged now without the one outstanding change requested. I'd suggest merge that and then go for it here...

**Comment by marcustisater** [comment]
Sorry, it's my fault that #169 has been moving slow. Great point @mor10, I agree.

**Comment by ntwb** [comment]
No apologies needed @marcustisater 😄 Differing time zones doesn't make this any easier 🙃

**Comment by mor10** [comment]
@davidakennedy I wouldn't mind giving this a crack, but it should only be done once the majority of CSS-focussed PRs are merged, otherwise there will be a lot of broken PRs floating around. We could do a full pass either close to core merge or even after so that more people can have eyes on it and there is less risk of conflict. What say you?

**Comment by davidakennedy** [comment]
@mor10 Thanks for volunteering. Given where we're at right now, I'd rather not do this.

Both @laurelfulford and I agree with the changes in principle, but I'm worried that we don't have the time to make such sweeping changes and test before the merge deadline Wednesday. Time is better spent on formatting and testing.

I'm going to close this for now, but that said, if we get to Tuesday, everything is solid, and there's time – maybe this can be reconsidered.
