### ISSUE TITLE
Edge whitespace is too small on medium screens

### ISSUE THREAD

**Issue by mor10** [WordPress/twentyseventeen#195]
On medium width screens (between 1070 and 1160) icons and avatars shifted outside the grid are either too close to the edge of the viewport or being cut off by the viewport.

Sticky icon too close to the edge:
![sticky icon](https://cldup.com/n-vqFqDmq5.png)

Bullets and numbers too close to the edge:
![bullets and numbers](https://cldup.com/tQRvnPVa6w.png)

Commenter gravatars cut off on left edge:
![gravatars](https://cldup.com/xIi664y9nc.png)

**Comment by joyously** [comment]
The bullets and numbers are because `ul` is styled as outside instead of inside (I think it's in normalize). But it makes it so lists don't line up with all the other elements.
![bullets-outside](https://cloud.githubusercontent.com/assets/7957680/19206650/0a1bb87a-8cb0-11e6-98c4-ee92a6368b20.jpg)

**Comment by jordesign** [comment]
That style of hanging punctuation is typographically correct - so would be nice to keep _when it is possible_.

Maybe the change can just be made for smaller screens?

**Comment by joyously** [comment]
No doubt it's typographically correct, but it looks awful. My screenshot is from a desktop browser.

**Comment by melchoyce** [comment]
The post navigation ends up having the same issue. 

Looks like there's no padding on `.wrap` when it's wider than 67em — that media query should probably get moved up. I also think we could up the padding on `.wrap` from `2em` to `3em` when it is in effect.

**Comment by LittleBigThing** [comment]
I have just tried your suggestion @melchoyce (I think :-)).

I think it works well in combination with decreasing (actually increasing :-)) the left position of the counter on ordered lists from -1.5em to -1em. This puts the numbers on ordered lists a bit more to the right, aligned with the bullets of unordered lists actually. Example:

**Before**

<img width="296" alt="ordered-lists-before" src="https://cloud.githubusercontent.com/assets/5901923/19404425/2c722300-926e-11e6-84ba-055ba8abba81.png">

**After**

<img width="297" alt="ordered-lists-after" src="https://cloud.githubusercontent.com/assets/5901923/19404431/338a38b2-926e-11e6-9991-349a7abb407f.png">
