### ISSUE TITLE
Entry-footer and site-footer borders run into each other on posts with comments turned off.

### ISSUE THREAD

**Issue by allancole** [WordPress/twentyseventeen#196]
This is really minor but it looks like the border-bottom on `.entry-footer` is touching the border-top of the `.site-footer`. 

You can see the issue here: 
![image](https://cloud.githubusercontent.com/assets/709581/19202914/acf866a0-8ca2-11e6-9e86-9a4d702ab071.png)
(Again, it’s subtle so you might have to zoom in to see it 🔍 )

**Comment by hiddenpearls** [comment]
@allancole This actually appears on pages as well when comments form displayed.

**Comment by jordesign** [comment]
Added PR #235 for this issue
