### ISSUE TITLE
Discuss aggressive clearing

### ISSUE THREAD

**Issue by mor10** [WordPress/twentyseventeen#197]
In the last couple of default themes a lot of elements have been aggressively cleared using the old "clearfix" method. This is continued in Twenty Seventeen.

I would love to have a discussion about the need for clearing vs. other options, and whether clearing elements before is necessary. My worry is this clearing is a bit too aggressive.

Related: There is a new recommendation for clearing:

```
.clearfix:after {
    content:" ";
    display:block;
    clear:both;
}
```

Source: http://cssmojo.com/the-very-latest-clearfix-reloaded/

**Comment by joyously** [comment]
If the flex method wins out, there will be clearing only for the old browsers that don't do flex.

**Comment by melchoyce** [comment]
Yeah, the aggressive clearing also causes a lot of unnecessary CSS bloat — makes digging through inspector difficult sometimes.

**Comment by mor10** [comment]
I'll update the flex PR tomorrow to include the fallback for older
browsers. Once that's accepted we can do a scrub for clearing and see what
is required.

In medias res on my paranoid android

**Comment by davidakennedy** [comment]
Thanks @mor10! I'm happy to have a pull request for this, but it isn't a top priority to remove these unless Flexbox wins out.

**Comment by mor10** [comment]
I just fully updated and rebased the flex PR.

**Comment by davidakennedy** [comment]
Will probably leave this as is since it was decided to not use Flexbox.

Any improvements like this though can be discussed in the #12.
