### ISSUE TITLE
Menu disappears after scrolling then jumping back to top of page

### ISSUE THREAD

**Issue by joyously** [WordPress/twentyseventeen#199]
If you scroll down a little bit, the menu is fixed to the top. If you then hit the Home key or PgUp so that the page is all the way at the top in one keystroke, the menu is removed from the top but not added back where it should be, below the title. The result is no menu at all.
![no-menu](https://cloud.githubusercontent.com/assets/7957680/19206363/0243671c-8cae-11e6-87b4-d37f56cdc937.jpg)

**Comment by josephfusco** [comment]
This should be fixed once #151 is merged

**Comment by melchoyce** [comment]
Fixed in #151.
