### ISSUE TITLE
Add display of posts through grid

### ISSUE THREAD

**Issue by gustavors** [WordPress/twentyseventeen#20]
Great job, congratulations!
Suggestions:
- Add display of posts through grid
- Support the CPT Jetpack, portfolio and testimonials

**Comment by melchoyce** [comment]
Since these are two separate suggestions, would you mind splitting them out into two separate issues? I can close this one once you do.

**Comment by davidakennedy** [comment]
@gustavors Thanks for the suggestions!

Default themes typically do not support plugins. See #18 for more context.

I've changed the title of the issue to reflect your other suggestion. In order for it to be considered, can you add more detail about exactly what you mean. A screenshot/example would be great.

Thanks again for the feedback!

**Comment by melchoyce** [comment]
@gustavors: Closing this for now. If you have more details, please comment and we'll reopen.
