### ISSUE TITLE
Submenu of leftmost menu item is cut off

### ISSUE THREAD

**Issue by joyously** [WordPress/twentyseventeen#200]
Hovering on the leftmost menu item shows the submenu, however, that submenu is truncated on the left.
![menu-1st-missing](https://cloud.githubusercontent.com/assets/7957680/19206525/270b4208-8caf-11e6-8395-568cf36c7a00.jpg)

**Comment by josephfusco** [comment]
The same issue exists in Twenty Sixteen (see: https://github.com/WordPress/twentysixteen/issues/394) and was brought up a lot but never resolved. Would be great to include a fix here 👍

**Comment by joyously** [comment]
`.main-navigation ul ul li:hover > ul,
    .main-navigation ul ul li.focus > ul {
        left: 100%;
        right: auto;
    }
`
is the problem. It works with `{left: 0;}`, and probably needs a different fix for RTL.

Additionally, the submenus are quite wide, and it could be a problem on a submenu on the far right. It is set to `width: 15em` which is a lot if you take the number used in the media query (55em, 67em,79em) and divide by 15, that's how many menu items would fit across.

**Comment by melchoyce** [comment]
+1 to fixing this. It's bugged me quite a few times on Twenty Sixteen.

**Comment by jordesign** [comment]
How do we feel about this appearance?
Its tricky to align the little arrowhead on the menu with the down arrow in the top level item, 
so we'd likely need to just left-align the arrowhead to the text above.

![image](https://cloud.githubusercontent.com/assets/1842363/19226509/c4b6783e-8ef7-11e6-8c2c-3b4f2f78ac1d.png)

**Comment by davidakennedy** [comment]
Thanks for the report @joyously!

Seems reasonable @jordesign! PR welcome if you have it.

**Comment by jordesign** [comment]
PR #303 submitted
