### ISSUE TITLE
Feature Image Displays twice on 'Gallery' post format

### ISSUE THREAD

**Issue by jordesign** [WordPress/twentyseventeen#204]
When a feature image is selected for post using the 'Gallery' format - the image is displayed twice:
1). at the top in the normal feature position
2). as a full width image at the top of the gallery

![image](https://cloud.githubusercontent.com/assets/1842363/19209495/0cc30266-8d57-11e6-85f0-d665f78e519e.png)

This is _probably_ the correct behaviour - so I guess it isn't a bug - but just wanted to raise it for discussion as it ends up looking a bit unusual.

**Comment by enodekciw** [comment]
Same happens when post format is set to: audio OR gallery OR image OR video post format.
Do we really need same featured image shown twice?

**Comment by enodekciw** [comment]
Looking at the source code, seems that `components/post/content.php` had this issue solved by preventing that second featured image appearing on single post views (`is_single()`). 

#207 makes that behaviour consistent across all other post formats.

**Comment by laurelfulford** [comment]
Thanks for spotting this, @jordesign, and for the fix, @enodekciw! :)

I'm reopening the issue until the fix is merged.

**Comment by laurelfulford** [comment]
Fixed with #207.
