### ISSUE TITLE
Utilize srcset & sizes for featured image header

### ISSUE THREAD

**Issue by josephfusco** [WordPress/twentyseventeen#209]
I think this differs from than #120 so I have opened this up separately.

[WordPress 4.4 introduced responsive images](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/). While all images within `the_content()` are automatically handled, we should also apply this behavior to the  featured image header.

**Comment by celloexpressions** [comment]
This is probably somewhere where core should provide something to make it easier for themes to do this by default. Definitely important given the image sizes here.

**Comment by jordesign** [comment]
To my understanding core _should_ be doing this with feature images - but it tends to do it best automatically when it detects image sizes in the same ratio as that which is being declared - so we'd need image sizes of a smaller width, but still in proportion to the 2000x1200 of 'twentyseventeen-featured-image'.

**Comment by jordesign** [comment]
I've getting the srcset output - 
![image](https://cloud.githubusercontent.com/assets/1842363/19215691/a171dc22-8df0-11e6-95f5-16b456f45cb1.png)

The tricky thing with srcset is that it is let entirely to the browser to decide which image to download based on what it detects will be the best experience for the user. For example - I think Chrome will _always_ load the largest image size when it detects the site is on  local network. So you have to just pretty much add the srcset there, and then trust the browser.

**Comment by mor10** [comment]
The purpose of responsive images is to allow the  browser to use the most suitable image for the current viewport and resolution. We can add a filter to control the output like what was done in Twenty Sixteen, but the core output here is relatively unproblematic imo

**Comment by jordesign** [comment]
I concur.

**Comment by melchoyce** [comment]
Just to clarify — are we good? Or do we need to do something?

**Comment by mor10** [comment]
I don't think we need to do anything since he featured images are always
displayed in relation to the full width of the viewport.

In medias res on my paranoid android

**Comment by melchoyce** [comment]
Cool, going to close in that case. If this needs additional discussion, please open a new issue.
