### ISSUE TITLE
Incorrect menu location count

### ISSUE THREAD

**Issue by ernilambar** [WordPress/twentyseventeen#21]
In functions.php-
`This theme uses wp_nav_menu() in one location.`
Location should be two.

**Comment by davidakennedy** [comment]
@ernilambar Nice find! Want to submit a fix through a pull request? 😄

**Comment by ernilambar** [comment]
I have already submitted PR. https://github.com/WordPress/twentyseventeen/pull/22

**Comment by davidakennedy** [comment]
Thanks for the contribution @ernilambar!
