### ISSUE TITLE
Custom Post Type posts don't have meta output

### ISSUE THREAD

**Issue by joyously** [WordPress/twentyseventeen#215]
It seems to me that the date should be output, like a standard post, and if the user doesn't want it, CSS can be added to hide it. But it is much harder for a user to get the date output if they want it, if the theme doesn't do it.

**Comment by davidakennedy** [comment]
Thanks for the good suggestion @joyously!

The `archive.php` template here serves as a fallback for post types if those do not have a template of their own. If customization is needed, post types should provide their own templates in a child theme. A default theme really just needs to handle the default post types and provide sensible defaults for fallbacks, so I'm going to close this.

**Comment by joyously** [comment]
I think you are mistaken. The `archive.php` template is the fallback for list pages that do not have a template of their own. Each of the templates in this theme, such as `index.php`, `archive.php`, and `single.php` calls `get_template_part( 'components/post/content', get_post_format() );` which then checks whether it is a "post" type before outputting the top meta. All I'm asking is for that if statement to be removed so that all post types are handled. A default theme should be as generic as possible, but in this case it is being very specific.  There are many use cases for sites to define custom post types and not use a child theme.
