### ISSUE TITLE
Setting a baseline

### ISSUE THREAD

**Issue by gorgoglionemeister** [WordPress/twentyseventeen#217]
As in Twenty Sixteen, I think it's helpful **setting a baseline**. Some elements are already aligned vertically, but there isn't consistence all over the theme.

**Comment by melchoyce** [comment]
Can you clarify what you mean? I don't think a typographic baseline is super feasible on the web without an excessive amount of CSS (and something like https://sassline.com/). The theme uses duplicates of 15px between elements to keep spacing consistent.

**Comment by gorgoglionemeister** [comment]
Twenty Sixteen sets an imaginary 7px line. All of the heights (line-height, padding-top/bottom, margin-top/bottom, etc.), with some exceptions, are multiples of 7px (28px, 21px, etc.).

This allows to cut the number of horizontal spaces as well as an horizontal grid does with vertical spaces.

I don't think we need a framework like Sassline to do that.

Please, can you explain better what you mean with "duplicates of 15px"?

Lastly, it would interesting to get the opinion of the Twenty Sixteen author, @iamtakashi, on the question.

**Comment by iamtakashi** [comment]
On the web, it's hard to make all text sit on baseline grids in _the traditional way_ we find in print design. The tools like Sassline or Mega Type would help to achieve that, but it can also backfire for some elements like buttons.

In my opinion, the important thing is if the design feels repetitive to have a good rhythm and flow, not whether it follows a vertical rhythm strictly with baseline grids or not.

If there are elements that feel out of rhythm and flow, it should be reported and we should discuss about it on a case by case basis.

**Comment by gorgoglionemeister** [comment]
Thanks for your reply

**Comment by melchoyce** [comment]
> Please, can you explain better what you mean with "duplicates of 15px"?

All of the margin/padding is done in duplicates of 15px — so some elements have 15px between them: 15px, 30px, 60px, 90px, 120px, and 150px.

**Comment by laurelfulford** [comment]
It looks like no action is needed, so I'm going to close this one. If further discussion is needed - or if you'd like to report specific element that feel out of sync, like @iamtakashi suggested - please open a new issue. Thank you!
