### ISSUE TITLE
Date and title being so tight line height causes readability issues

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#219]
Due to the capitalisation and also tight line height, there are some legibility issues with the date and title. See here:

![2016-10-09 at 16 39](https://cloud.githubusercontent.com/assets/253067/19221730/b8966c42-8e40-11e6-872f-33b0ab3a91da.png)

I experienced this issue myself and do feel we need to correct it. It could just be a tiny increase like this: 

![2016-10-09 at 16 54](https://cloud.githubusercontent.com/assets/253067/19221747/077ce0fc-8e41-11e6-8e62-59719f12d408.png)

I am not creating a patch yet, as I want to also make sure the design integrity is kept and get an opinion. From a legibility view though we need to make this adjustment. It's a tiny change but important. I'd be inclined to go up to 0.75 over 0.5 but understand that it may be too far for the design integrity.

**Comment by davidakennedy** [comment]
@melchoyce What are your thoughts here?

**Comment by davidakennedy** [comment]
Thanks @karmatosed! On second thought, this would alter vertical rhythm quite a bit. While I agree the current positioning may not be perfect for everyone, every design will have small issues, so I'm going to close this.
