### ISSUE TITLE
Fixed menu has a jumping action that seems weird in Chrome

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#220]
I noticed this whilst testing and it probably is due to the effect of fixing, but it feels jarring. Here is what I experienced with the amazing jumping action of the fixed menu.

![twentyseventeen-fixjump](https://cloud.githubusercontent.com/assets/253067/19221775/9344106a-8e41-11e6-9c76-635bd3ca0aef.gif)

If there was some way we could make this smoother, it would be a huge visual hitch removed.

**Comment by josephfusco** [comment]
@karmatosed this should be fixed when #151 merges

**Comment by karmatosed** [comment]
@josephfusco ah cool, lets maybe keep this open and check depending on the outcome of the PR.

**Comment by joshcummingsdesign** [comment]
I'm wondering if this is also related to the fact that the menu fixed position doesn't start until after you scroll the height of the nav. In my mind, I would want it to be fixed when the nav reaches the top of the window so it looks like the window is pushing it down.

**Comment by josephfusco** [comment]
#151 has been merged which introduces new behavior for the nav. Please update your local copies and review again. We should be good to close this now.

**Comment by joshcummingsdesign** [comment]
Thanks @josephfusco :) I thought I did, but I was on another branch. Looks great!

**Comment by melchoyce** [comment]
Fixed in #151.
