### ISSUE TITLE
Widget item unequal padding disjointed visually

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#221]
I am not sure if this is meant to not be equal, hence putting for design label incase this is part of the design. On loading the theme fresh, it felt weird to see a row of these. Whilst this is a rarer case, the default visual of the theme is important.

![2016-10-09 at 16 59](https://cloud.githubusercontent.com/assets/253067/19221787/e0378442-8e41-11e6-8014-00c831477ede.png)

**Comment by josephfusco** [comment]
#158 might also be related

**Comment by karmatosed** [comment]
@josephfusco ah good find, thanks. That could be related as I'm seeing things on default theme with 1 item. @davidakennedy noting these may be related so I can close this if you think so.

**Comment by melchoyce** [comment]
Closing in favor of #158.
