### ISSUE TITLE
Hover link effect legibility issues

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#222]
I do love the idea of a background hover color, but unfortunately combined with the font and smaller sizes, there are some legibility issues. This shows an example:

![2016-10-09 at 17 01](https://cloud.githubusercontent.com/assets/253067/19221794/1876838a-8e42-11e6-9cf0-4e244ebf2e6b.png)

This is easier to read when the larger title fonts, as a result I would suggest if we're keeping it to remove the style on the smaller widgets and titles. I myself couldn't make this word out when hovered.

The big issue is where the white character blends with the background because of the color. This effect means some people will be unable to make the edges of the characters out. It causes visual issues with blurring into the white as a result.

**Comment by karmatosed** [comment]
Noting this also is an issue in the footer - I assume all smaller hovers as a result:

![2016-10-09 at 17 03](https://cloud.githubusercontent.com/assets/253067/19221802/5838a62e-8e42-11e6-85af-f76973d8cc59.png)

I also get it on 'continue reading' as a hard to read issue.

**Comment by celloexpressions** [comment]
If we added some padding around links that would help a lot. I'm not sure how feasible that would be though, without a lot of CSS refactoring.

**Comment by karmatosed** [comment]
@celloexpressions my concern with padding is you then have to think about the impact on non-hover. You can easily then have moving text, which for a lot of reading issues is happening to user anyway. Compounding that isn't great.

**Comment by celloexpressions** [comment]
Right, the padding would have to always be applied to avoid jumping, which may be difficult to do.

**Comment by jordesign** [comment]
You could add the padding and then have a negative margin?

`padding: 0 5px;
margin: 0 0 0 -5px;`

**Comment by karmatosed** [comment]
@jordesign the problem isn't just left/right, it's top and bottom also for characters that have line variations.

**Comment by folletto** [comment]
While it's a decision that is both a consequence and informs the style of hovers, we could explore using `outline` for this:

![screen shot 2016-10-12 at 12 39 45](https://cloud.githubusercontent.com/assets/4389/19308746/184e1ac4-9079-11e6-828f-090ced4a3d1e.png)

The above is done with a transition of `outline` that uses same timing and easing of the background on a linear background fade:

```
a { ... outline: 2px solid rgba( 118, 118, 118, 0.0 ); ... }
a:hover { ... outline-color: rgba( 118, 118, 118, 1.0 ); ... }
```

**Comment by melchoyce** [comment]
Related conversation happening in #240.

**Comment by karmatosed** [comment]
With consideration to the new styling, lets close this.
