### ISSUE TITLE
If no content in panel then it should just not show

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#223]
This will depend on if we can get the multi-panel front page into core. However, just incase we do not, I think we need to improve the UX a little for multi-panels using theme options.

Currently we assume that all panels should have content. I can see a valid case where people will not want to do this. We should therefore add that if no content is set to show, the panel doesn't. We may have to do something to work around first use of theme - it would be all blank otherwise. I do think it's sensible though and allows a bit more flexibility.

**Comment by celloexpressions** [comment]
For initial use, won't the static front page content still be shown at least?

Also noting that if it stays in the theme, we'll also need to update it to follow [core best practices](https://developer.wordpress.org/themes/advanced-topics/customizer-api/) for theme options in the customizer as well, so we need to plan time for making a variety of changes there if that happens.

**Comment by davidakennedy** [comment]
Thanks for the issue @karmatosed! If the panels have no content – the front page is just the front page. I'm not sure I see a problem. Maybe we don't highlight the front page content with the outline if the panels don't have content?

**Comment by karmatosed** [comment]
I think not highlighting fixes this.
