### ISSUE TITLE
Consider making panel border dashes and notices more WP colors

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#224]
This also will only need to be looked into if we have the theme based multi-panel, but it's worth considering. Currently we have this for the dashes and labels:

![2016-10-09 at 17 47](https://cloud.githubusercontent.com/assets/253067/19222101/9e38d5c6-8e48-11e6-9b43-eacf790523da.png)

I would first like to understand why they are purple, there may be something I'm missing. If there is no set reason, then I'd like to suggest we bring them more into WP and base on those colors.

**Comment by celloexpressions** [comment]
These colors/borders will need to be removed, actually, as they do not accurately represent what the site will look like when published, which is the purpose of live preview. It might be an option to show them only when the customize pane is open to the front page settings, but I'd prefer to eliminate entirely.

**Comment by davidakennedy** [comment]
Let's assume this stays in, regardless of what happens with Core features.

How can we provide the user with helpful hints as to what panel goes where? Is there a hard rule that help text can not exist in the live preview? I have seen themes display text only in the Customizer to help users know what goes where before. So I don't see a problem, and we could certainly alter the design to fit better with Core.

**Comment by celloexpressions** [comment]
We could add text (think like the edit content links) if we have to but it's not ideal. Visual solutions like borders should be avoided. Users new to the theme will think that the borders are a part of the design that will be published to their site, as they currently look like a design detail.

We'll also likely have visible edit icons in the customizer preview, which probably eliminates the need for anything specifically added by the theme.

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38408
