### ISSUE TITLE
Social icon support

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#227]
Since we're [switching to Font Awesome](https://github.com/WordPress/twentyseventeen/issues/65), we have much greater social icon support for the theme's social menu.

Here are the networks I think we should support:
- Facebook
- Twitter
- Instagram
- Pinterest
- Tumblr
- LinkedIn
- Google+
- YouTube
- Vimeo
- Soundcloud
- Vine
- Snapchat
- Reddit
- Flickr
- VK
- Goodreads
- deviantart
- Codepen
- GitHub
- Dribble
- Behance
- WordPress
- Medium
- Slideshare
- Yelp

Are there any other social networks in http://fontawesome.io/icons/#brand that Twenty Seventeen should support? For reference, these would be used in the Social Menu at the bottom of the theme:

<img width="1235" alt="screen shot 2016-10-09 at 6 11 15 pm" src="https://cloud.githubusercontent.com/assets/2846578/19224072/ce0d305a-8e4b-11e6-8153-88258082ecf3.png">

**Comment by samikeijonen** [comment]
@melchoyce: In commit e74d70d I added missing social icons.

But I didn't find Goodreads icon. Can you point that out for me?

This is related to PR #253.

**Comment by carolinan** [comment]
How about QQ?

**Comment by melchoyce** [comment]
@samikeijonen I must have imagined it, because I don't see it there either. Too bad. 

@carolinan I've never heard of QQ before, thanks for suggesting it. Does it let users create public profiles of some kind?

**Comment by melchoyce** [comment]
Fixed in https://github.com/WordPress/twentyseventeen/commit/353cca8c31ff48bc5d8b8745bc457d7f7c51d9d0

**Comment by amann-one** [comment]
Hi,
is it still possible to add another social icon?
If so, please add XING to your list!
https://www.xing.com is a business network platform from Germany (such as LinkedIn) which is very popular in Central Europe and has about 15 million members.

Thanks in advance,
Christoph

**Comment by melchoyce** [comment]
Hi @amannulm, development of Twenty Seventeen has moved to Trac. Can you make a new ticket here? https://core.trac.wordpress.org/ Thanks!

**Comment by gevargus** [comment]
Hi @melchoyce. Can you add "Houzz"?

**Comment by laurelfulford** [comment]
Hi @georgediril! Development of Twenty Seventeen has moved to Trac - you can now report any issues or enhancements requests here: https://core.trac.wordpress.org/ Thanks!
