### ISSUE TITLE
Prefixing theme mod handles

### ISSUE THREAD

**Issue by grappler** [WordPress/twentyseventeen#23]
The theme mod handles are prefixed e.g `get_theme_mod( 'twentyseventeen_footer_image' )`.

This has been discussed a few times in the Slack #themereview channel as all of the settings are saved separately for each theme. Prefixing would prevent conflicts with other plugins and core using the setting name.

This decision will affect how other themes set their setting names.

**Comment by ryelle** [comment]
@grappler The theme mods here are already prefixed, are you saying the prefixes should be removed? I would agree with that — theme mods are auto-prefixed when they're saved in the database (into the option `theme_mods_$theme_slug`), there shouldn't be any unexpected conflicts.

If you're saying they _should_ be prefixed, can you link to the discussion in themereview? I tried searching make/themes, but couldn't find anything.

**Comment by grappler** [comment]
@ryelle Sorry I was not clear. The themereview does not require it or recommend it. My vote would be to remove it.

**Comment by davidakennedy** [comment]
I'd agree that the theme mod handle prefixes should be removed.

**Comment by joshcummingsdesign** [comment]
Sent a pull request that should address this issue #149

**Comment by davidakennedy** [comment]
Thanks @joshcummingsdesign!
