### ISSUE TITLE
Customizable: Proudly powered by WordPress as well as copyright information

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentyseventeen#232]
What if we give the option to the user to adjust the "Proudly powered by WordPress" and well as copyright information or other text in this area. 

@clorith suggested we use 
"`&copy; $year $sitename` by default with a filter on it for childthemes and leave it at that to not add too many potentially confusing customizable elements."

Is this something that should be added to the Site Identity customizer area?

**Comment by enodekciw** [comment]
Actually, this got me thinking..

If you're using a child-theme, it shouldn't matter much if you'd need to add a filter, or just replace `child-theme/components/footer/site-info.php` to customize the site credits, but..

..what if you're not using a child theme, and just want to customize the site credits? At the moment, you can translate the URL and the actual string, however there's no way to get rid of the wrapping anchor itself. So you will always end up with `<a href="%s">%s</a>` no matter what. Basically, now you HAVE to have a link in your site credits. Wouldn't it be a good idea, to let translators also translate (_edit_) the markup of the translatable string? Codex even provides an [example for that](https://codex.wordpress.org/I18n_for_WordPress_Developers#HTML).

Maybe something [like this](https://github.com/enodekciw/twentyseventeen/commit/c2c27ca054fa2d65a43df6fb6f048e9cf4441ae7) would work? Or am I just overthinking things and trying to add an unnecessary layer of complexity?

**Comment by Clorith** [comment]
In a child theme it does matter, you may not want to change the whole footer, only that one text, a filter is super simple then and ensures any markup etc that may come from a future update is still valid.

It also ensures that it can be addressed via other means such as a plugin for those who just want a quick fix (a lot of people have their own quirks in a must-use plugin).

There's no problem in first passing it through a translation before applying the filter to it of course, but from a support perspective, we frequently see themes without any filters in these areas which would make a lot of lives easier.

**Comment by davidakennedy** [comment]
Thanks for another good suggestion @paaljoachim!

One of the reasons this area isn't opinionated is so users can add what they need via a child theme or by forking the theme. Either way, some users will want something different so it tries to keep it basic. If the copyright symbol goes in, just as many or maybe more users may want to remove it as add one. 😄 

So this will stay as it is.

**Comment by balbir007** [comment]
Much a debt of gratitude is in order for creating such an intriguing blog. I have favored your post specifically and has affected me. For more detail please visit 
http://www.multipackersmovers.in/packers-and-movers-in-delhi/
