### ISSUE TITLE
Control for hiding page titles?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentyseventeen#233]
It seems it is pretty common to hide the page title. It would be good to have a control someplace the user can check to hide page titles and if they want also post titles.

**Comment by paaljoachim** [comment]
Btw
https://wptavern.com/wordpress-com-introduces-content-options-customizer-panel-plans-to-include-in-jetpack

It would be great to do something like this also for Twenty Seventeen.

**Comment by davidakennedy** [comment]
Thanks for the good suggestion @paaljoachim. I'm not in favor of adding any theme options that are in the vein of altering the design.

Default themes should be as simple as possible, provide a clear design direction and be easy to setup. That gets harder to do with more options.

Also, if custom CSS gets into this release, this use case would be nice for that. But I do recognize every user shouldn't have to learn CSS to make their site the way they want it.
