### ISSUE TITLE
Enqueue script and style handles

### ISSUE THREAD

**Issue by grappler** [WordPress/twentyseventeen#24]
In the theme review team we encourage theme authors not to prefix third party scripts so to prevent the same scripts being loaded twice.

e.g. `wp_enqueue_script( 'twentyseventeen-html5' );` would be `wp_enqueue_script( 'twentyseventeen-html5' );`

Any scripts that are dependant on other scripts should be prefix with that scripts handle and the handle names should be all lowercase.

e.g. `wp_enqueue_script( 'scrollTo' );` would be `wp_enqueue_script( 'jquery-scrollto' );`

The script handles should also be related to the script file name and with a dash as the separator. e.g. `wp_enqueue_script( 'twentyseventeen_extra_js' );` would be `wp_enqueue_script( 'twentyseventeen-panel-customizer' );` and `wp_enqueue_script( 'twentyseventeen_customizer' );` would be `wp_enqueue_script( 'twentyseventeen-customizer' );`

**Comment by davidakennedy** [comment]
Hey @grappler! Thanks for the issue and pull request!

> In the theme review team we encourage theme authors not to prefix third party scripts so to prevent the same scripts being loaded twice.

I've never heard this before. I wouldn't be against it, but I personally think that "prefix everything" is easier to remember and practice. I assume the script being loaded twice would be from a plugin or child theme, yes? Do you all see this a lot on the theme review team? And is this written in the handbook? I didn't see it.

Thanks again!

**Comment by grappler** [comment]
>  I assume the script being loaded twice would be from a plugin or child theme, yes?

Yes

> Do you all see this a lot on the theme review team?

We are unable to know if scripts will be loaded twice when using another plugin but I have personally experienced this when building sites or plugins.

> And is this written in the handbook?

This is unfortunately not written in the handbook but I will try to get it documented by bringing it up in the meeting next week.

**Comment by WPDevHQ** [comment]
I second the proposal as this is also my understanding from TRT.

**Comment by davidakennedy** [comment]
@grappler I'd like to see an official recommendation from the Theme Review team. This is a pretty small change, but my thoughts right now are:
- It's easier to teach people to prefix everything.
- The chances of this saving someone are very small. What if a plugin dev calls it `htmljs`?
- What qualifies as third-party? Anything not written by theme author?

All that said, I am open to it, just on the fence because I'm not sure if will help the problem much. And it may confuse people.

**Comment by justintadlock** [comment]
We have an official recommendation now: https://make.wordpress.org/themes/2016/10/04/october-4th-team-meeting-notes/

**Comment by davidakennedy** [comment]
Thanks for working on this, and getting an official recommendation @grappler and @justintadlock!
