### ISSUE TITLE
Sticky footer - when there is very little content.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentyseventeen#244]
The reason to have a fixed footer is when there is very little content on a page that pulls the footer upward. Keeping it fixed on the bottom of the page would then be helpful.

![footer-reveal-example](https://cloud.githubusercontent.com/assets/5323259/19256682/4e24f476-8f37-11e6-88d8-96e13a0fdb49.png)

I took the image from here: http://wpexplorer-themes.com/total/docs/fixed-footer/

**Comment by josephfusco** [comment]
While they seem the same I think a _sticky footer_ would be more appropriate rather than a _fixed footer_. Maybe that is what is meant here :)

Good write up about the sticky footer behavior: https://css-tricks.com/couple-takes-sticky-footer/

**Comment by paaljoachim** [comment]
I did a test and added a brown color to the color background of the site-footer. Then checked the page that has very little content. Then added a color background to the body background. The footer has a space below where the content color background is seen.

![screen shot 2016-10-12 at 18 39 49](https://cloud.githubusercontent.com/assets/5323259/19330255/505d7a72-90ab-11e6-9565-80b151115c99.png)

I am looking into the sticky footer code at css tricks.  I have not been able to get it to work yet.

**Comment by davidakennedy** [comment]
Thanks for the idea @paaljoachim!

I like this pattern in some cases for content heavy sites. But I think for Twenty Seventeen, things could get tricky paired with its sticky menu. It's just not a good fit with the current design.

**Comment by paaljoachim** [comment]
Adding a color through CSS to the site-footer (as seen above as the brown-red color) when there is very little content the site-content color shows through below the footer (as seen above in muddy green color).

**Comment by paaljoachim** [comment]
Here is some code that actually works pretty well.
http://testing-newdefaulttheme-twentyseventeen.qsandbox.com/very-little-content/

#page {
position: relative;
-ms-word-wrap: break-word;
word-wrap: break-word;

/\* Sticky footer code*/
display: flex;
min-height: 96.3vh;
flex-direction: column;
}

.site-content {
padding: 2.5em 0 0;

/\* Sticky footer code*/
flex: 1;
}

Based on:
https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

**Comment by paaljoachim** [comment]
Btw here is the sticky footer working:
http://fragmentsofawalk.com/very-little-page-content/
