### ISSUE TITLE
Easily upload your own avatar.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentyseventeen#249]
This is probably the most political incorrect issue and will very likely be closed as not relevant but my thought is that we are creating a theme that people in general can easily use right out of the box.

Including a code snippet that includes a browse/upload field in the user profile screen where the user can include their own avatar without having to signup at gravatar.com would be helpful.

**Comment by josephfusco** [comment]
This feels more like something core should handle

**Comment by helen** [comment]
This is not even remotely theme territory. See https://core.trac.wordpress.org/ticket/16020

**Comment by joyously** [comment]
There are a lot of plugins for that. It's nothing to do with the theme.

**Comment by cdog** [comment]
This seems more appropriate to core. I would like to see any updates on that ticket.
