### ISSUE TITLE
 Undefined variable: categories

### ISSUE THREAD

**Issue by valeriu** [WordPress/twentyseventeen#25]
NOTICE: `wp-content/themes/twentyseventeen/inc/template-tags.php:51` - Undefined variable: **categories**

**Comment by davidakennedy** [comment]
@valeriu Thanks for the issue! Can you explain in steps how you produced this notice? What page/post where you on, etc.? Did the post have categories and tags?

Some more details would be helpful. 😄

**Comment by grappler** [comment]
@davidakennedy The problem should be visible in the code. The variable `$categories` is only defined if `get_the_category_list( $separate_meta )` and `twentyseventeen_categorized_blog()` are defined true.

So you will see an error if the whole blog has only one category.

**Comment by valeriu** [comment]
Thanks @grappler 

@davidakennedy The NOTICE  appear at any post who has less than 2 selected categories.

**Comment by davidakennedy** [comment]
Thanks for the clarification all!

Thanks for creating the issue and submitting a pull request @valeriu!
