### ISSUE TITLE
Front page edit button styling issue

### ISSUE THREAD

**Issue by maheshwaghmare** [WordPress/twentyseventeen#250]
**Front Page**
Front page `edit` button not look same as on other page / post edit links.
<img src="https://cldup.com/BRyum8FV97-3000x3000.png" />

---

**Other Page / Post `edit` button**
<img src="https://cldup.com/YUDLYtkShp-3000x3000.png" />

---

**Expected for Front Page**
<img src="https://cldup.com/tUQVjB373T-3000x3000.png" />

**Comment by melchoyce** [comment]
So, I actually think we should remove the edit button in interior pages and instead show "edit" underneath the page title, like we do on the homepage. Posts, since they have meta, can stay the same. cc @laurelfulford
