### ISSUE TITLE
Captioned images with no alignment get misaligned

### ISSUE THREAD

**Issue by mor10** [WordPress/twentyseventeen#256]
When a captioned image is added with alignment set to `none`, the default style rules for the `figure` element set in Normalize cause the image to shift to the right. When the image is the width of the displayed area, it is shifted to the right edge and appears misaligned.

Current `figure` rule looks like this:

```
figure {
    margin: 1em 40px;
}
```

Narrow screen:
![small screen](https://cldup.com/R63oZm5k0g.png)

Wide screen with sidebar:
![wide screen with sidebar](https://cldup.com/Qlip7zm5z9.png)

My suggestion is to change the `figure` reset in Normalize to `margin: 1em 0;` because the indentation makes little sense in the context of a WordPress theme.

**Comment by jordesign** [comment]
I'd be happy with that change.
Lets just mak sure the top/bottom margin fits with whatever vertical rhythm we end up using.

**Comment by mor10** [comment]
Are there any fringe issues I'm not aware of here?

**Comment by mor10** [comment]
Upon closer inspection this issue also affects left and right aligned images with captions. The fix in the PR resolves the issue.

This is what the alignments look like _before_ the fix in the PR:
![misaligned images](https://cldup.com/r6zRKJ30RO.png)

**Comment by jordesign** [comment]
Do we need to worry about the right margin on left-ailgned items (and vice versa) ?

**Comment by enodekciw** [comment]
In my opinion, you should not change default `normalize.css` styles directly. I mean, I'd prefer overwriting them with more specific CSS selector, something like `.entry-content figure` or so, since `figure` looks a bit too generic and might cause some unforeseen issues. 

Also, bumping `normalize.css` in future will be way easier if no custom tweaks are made to it :)

**Comment by mor10** [comment]
@jordesign: it fixes an issue with captioned images. Uncaptioned images are unaffected.

@enodekciw IMO Normalize is wrong here (and resets like this are problematic as a whole), and adding a custom fix is a waste of code.  There is nowhere in this design where a 40px margin on the left and right of a figure makes sense.

I do see your point about updates to Normalize, but adding a new rule is the opposite of DRY development.

**Comment by josephfusco** [comment]
+1 on editing normalize in this case. I think it would be good to change the section title to just normalize, and mention "based on normalize.css" with the link.

**Comment by mor10** [comment]
I can change the PR if that is the majority opinion, but I want to make sure everyone's clear on this. If that's the fix, we are keeping a superfluous rule in the stylesheet solely to preserve the integrity of a third party library that has been copied and pasted in.

**Comment by mor10** [comment]
@enodekciw I've experimented with adding specificity to the rule to override Normalize. This causes a problem in the cascade that results in left- and right-aligned images losing their margins (which is done using the `.alignleft` and `.alignright` rules). If more specificity is added to override the Normalize rule, more specificity will have to be added to the alignment rules as well. That's not great.

An alternative is to add a second clean `figure` rule, but that is bad practice. 

If there is a way around this I am all ears. I may be too tired to think of it right now.

**Comment by samikeijonen** [comment]
+1. This was done also [in _s](https://github.com/Automattic/_s/commit/7d0846eb2da58d7c06693623ed608fcdf1dcfb21#diff-da232d78aa810382f2dcdceae308ff8e) for same reasons.

**Comment by josephfusco** [comment]
> +1 on editing normalize in this case. I think it would be good to change the section title to just normalize, and mention "based on normalize.css" with the link.

To clarify my earlier comment, I meant the section normalize not normalize.css. Currently normalize IS normalize.css and nothing else.

I was under the impression that projects like _s do not just have a normalize.css release pasted in, but rather use a hybrid approach borrowing styles from normalize reset & blueprint, and then just crediting normalize for borrowing items, but titled the section normalize.

After some research on the matter it looks like _s now uses normalize.css directly and overrides those styles when needed like @samikeijonen just pointed out.

**However**, Twenty Sixteen does not follow recent _s in this case and instead edits this directly [as can be seen here](https://github.com/WordPress/twentysixteen/blob/master/style.css#L145-L147).

So do we edit this directly and redo the normalize section header to reflect that this is now just based off of normalize like Twenty Sixteen does, ([see commented section title](https://github.com/WordPress/twentysixteen/blob/master/style.css#L54-L59)) or override it later like _s while maintaining normalize as normalize.css?

**Comment by mor10** [comment]
@josephfusco I would go the Twenty Sixteen route: We have to provide best-practice examples here, and repeating the same rules twice solely to preserve the original structure of borrowed code is the opposite of that.

**Comment by melchoyce** [comment]
Have previous default themes updated their Normalize/Resets in the past? @iamtakashi / @ianstewart / @karmatosed do any of you know?

If we're not in the habit of updating them post-launch, then I'm cool with us changing it directly for Twenty Seventeen.

**Comment by karmatosed** [comment]
I'm not sure we ever updated our normailze/resets in the past. Personally, I try and leave them cast in stone from release, purely for ease and legacy.

**Comment by mor10** [comment]
Can someone make a final call on this? I'll update the PR if necessary so we can get it sorted.

**Comment by melchoyce** [comment]
Let's edit Normalize directly.

**Comment by mor10** [comment]
Question: Should I update the comment above Normalize to something like this to make it clear it is not verbatim?

```
/*--------------------------------------------------------------
# Normalizing styles based on Normalize v5.0.0
@link https://github.com/necolas/normalize.css
--------------------------------------------------------------*/
```

If not, the PR is good to go as is.

**Comment by josephfusco** [comment]
@mor10 that looks good.
