### ISSUE TITLE
State of third party resources in the readme

### ISSUE THREAD

**Issue by grappler** [WordPress/twentyseventeen#26]
The following third party resources have not been mentioned in the readme
- [ ] jquery.scrollTo.js
- [ ] header.jpg
- [ ] Fork of Lodestar

**Comment by davidakennedy** [comment]
Thanks for the issue!

We will list the source and license of all third-party resources. I left some of some of those details out for now since they may change. But I'm going to leave this open as a reminder to check it later.

**Comment by celloexpressions** [comment]
Was Lodestar released or copyrighted yet? I'm not sure whether or not it's appropriate to reference it if that was used more out of convenience than for particular reasons, but we'd need more of the background explained there. Twenty Fourteen was also a fork, but it's original theme was published and distributed prior to being forked and the design was quite similar, so its reference to the original theme and copyright in the readme makes sense.

**Comment by josephfusco** [comment]
~~@grappler I edited your initial comment here to include photo credit for the bundled header image.~~

~~Mentioned in: #134~~

Wow I need coffee. Nevermind.

**Comment by josephfusco** [comment]
Wow I need coffee. Nevermind.

**Comment by josephfusco** [comment]
Looks like this was fixed in 84476cb7146ce425dbd2c2c9a74fdc32411e420d
