### ISSUE TITLE
Some post formats missing categories, tags, and edit links

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/twentyseventeen#260]
The audio, gallery, image, and video post formats are missing the tags, categories and edit links on single post views. 

The content-*.php files for these formats need the `twentyseventeen_entry_footer()` at the bottom, wrapped in an `is_single()` check, like content.php:

```
<?php if ( is_single() ) : ?>
    <footer class="entry-footer">
        <?php twentyseventeen_entry_footer(); ?>
    </footer><!-- .entry-footer -->
<?php endif; ?>
```

**Comment by enodekciw** [comment]
Has PR: #261

**Comment by joyously** [comment]
similar to #215
