### ISSUE TITLE
Feature request: Page-level control of one/two columns

### ISSUE THREAD

**Issue by mor10** [WordPress/twentyseventeen#267]
Currently the choice of displaying pages with one or two column layout is done at a sitewide level affecting all pages. I would argue this feature should be extended to page-level control, probably through an override via custom page templates. With two available layout options it seems heavy handed to force all pages to fit one of the two options. 

In my own practice I would use two different layouts to indicate two different types of pages. For example, all about and info pages would be one-column and all legal and technical pages would be two-column.

**Comment by davidakennedy** [comment]
Thanks @mor10! Similarly to #268, I'm not opposed to this, but also think it's okay to be opinionated and provide a design direction than more options. Thoughts @melchoyce?

**Comment by mor10** [comment]
For the custom sidebar issue (#268), I agree. For the one/two column layout issue, I think providing page-level control is vital, in large part because of how this setting is configured:

When an administrator is working in the Customizer and changes the setting, they are seeing the change only on the page they are currently looking at. There is nothing in the current setup that informs them this change affects all pages. As a result I can see an administrator diligently going through each of their pages and changing the setting thinking they are controlling the layouts of each of the pages individually. Then when they go to the front end they are confused because all the page layouts are the same.

In lieu of a custom page template a better solution may be to tie the layout theme mod setting to individual pages (don't know if that's even possible, but from a logical standpoint this seems more rational). 

If this is an absolute no-go, I would stress the need for updating the description text in the Customizer function to clearly state this layout change applies to all pages, not just the current one being viewed.

**Comment by melchoyce** [comment]
I'm really opposed to adding page templates. I think they're overall a bad experience in WordPress, and it seems confusing to me that we'd use them to override a Customizer setting.

> If this is an absolute no-go, I would stress the need for updating the description text in the Customizer function to clearly state this layout change applies to all pages, not just the current one being viewed.

This makes sense to me.

**Comment by melchoyce** [comment]
Closing this in favor of #461.
