### ISSUE TITLE
Feature request: Dedicated page sidebar

### ISSUE THREAD

**Issue by mor10** [WordPress/twentyseventeen#268]
I propose adding an additional optional sidebar are that appears only on pages. This is in line with what I see on a lot of business sites - a custom sidebar that provides navigation and contextual links for pages only - and would provide an additional level of customization.

A further enhancement would be some way of deciding whether the sidebar is displayed on a page-by-page basis.

**Comment by davidakennedy** [comment]
I'm not opposed to this, but I wouldn't want to add a page template for it because simplicity is better. It's okay for themes to be opinionated and not hit every possible use case. It's really a design decision, I think, because it would alter how pages look in a big way.

Thoughts @melchoyce?

**Comment by melchoyce** [comment]
I think if businesses really need this, they can create a child theme or use a plugin. Let's keep pages simple.

**Comment by mor10** [comment]
I have no strong opinions on this, it is merely a suggestion. Feel free to close it out.

**Comment by Martien** [comment]
Just got my hands on 2017, and I must say that I miss the option to show a sidebar on pages. I want my visitors give the option to select from a (few) other pages when they are on a page. In fact, I have a set of pages that form both a whole and a shallow hierarchy. With 2017, it seems, this can only be done with a child theme (too complicated) or by converting the pages into posts.

BTW, I have never thoroughly understood the reasoning behind pages and posts being different.
