### ISSUE TITLE
Mismatch in selectors/code for captioned images

### ISSUE THREAD

**Issue by joyously** [WordPress/twentyseventeen#269]
It looks like the stylesheet has some standard selectors in it, but the code is not using those classes as styled.
There are styles for `.wp-caption, .gallery-caption` and `.wp-caption img[class*="wp-image-"]` and `.wp-caption .wp-caption-text`.  
Running WordPress 4.6.1, I made sure I didn't have any plugins affecting gallery output, and see that the code for a gallery does not use the class `wp-caption`.  It looks like 
`<figure class='gallery-item'>`
`<div class='gallery-icon landscape'>`
`<a ...><img class="attachment-thumbnail size-thumbnail" ... /></a>`
`</div>`
`<figcaption class='wp-caption-text gallery-caption' id='gallery-1-967'>`
`</figcaption></figure>`

The code for a captioned image in a post does use `wp-caption`. It looks like:
`<figure id="attachment_967" class="wp-caption">`
`<img class="size-thumbnail wp-image-967" ... />`
`<figcaption class="wp-caption-text"> </figcaption></figure>`

So `.wp-caption` is a figure and `.gallery-caption` is a figcaption, yet they are both selectors in a rule for styling text. Then a separate rule for `.gallery-caption` to be display:block (strange when it is contained by an inline-block figure).
The selector `.wp-caption img[class*="wp-image-"]` is very specific and styles the image with auto side margins. It seems to work.
The `.wp-caption .wp-caption-text` rule is just for margins, which only apply because the figcaption is declared as display:block. It seems like the rule for `.gallery-caption` would be bundled with this one.

**Comment by davidakennedy** [comment]
Hey @joyously! Thanks for this issue!

I've double-checked, and I can't find any issues with captioned images in the theme.

Gallery uses `gallery-caption`. Regular captioned images use `wp-caption`, which I see in your markup example. And `.wp-caption .wp-caption-text` comes into play as well.

See: https://github.com/WordPress/twentyseventeen/blob/master/style.css#L2246-L2264

There have been some recent additions to gallery styles as well.

If you see any specific visual issues with the images/captions, create another issue. Screenshots help! 😄

**Comment by joyously** [comment]
Yeah, I think there was actually a minor update to the gallery styles in that big gallery PR because of this issue, but it might not have gotten referenced.
