### ISSUE TITLE
Remove deprecated constant HEADER_TEXTCOLOR

### ISSUE THREAD

**Issue by grappler** [WordPress/twentyseventeen#27]
The constant `HEADER_TEXTCOLOR` was deprecated in WP 3.4.

> Constants are lame. Don't reference them. This is just for backward compatibility.

from /wp-includes/theme.php#L1645

We are adding a check to the new Theme Check to not allow deprecated constants. WPTRT/WordPress-Coding-Standards#30

Related: https://github.com/Automattic/_s/pull/991

**Comment by davidakennedy** [comment]
This looks good to me – thanks for the issue and pull request!
