### ISSUE TITLE
iframe in paragraph with alignleft causes horizontal scrollbar

### ISSUE THREAD

**Issue by joyously** [WordPress/twentyseventeen#270]
I have a page with an oEmbed of
http://www.youtube.com/v/LwlLC2PUrH8

When it is rendered, it is an iframe in a paragraph tag. Using Firebug, I added `class="alignleft"` to the p tag, and the video got larger, with the excess to the right, causing a horizontal scrollbar.
I think this is not a rare type of markup, even though I didn't enter it that way in the beginning.

**Comment by josephfusco** [comment]
There is no support for aligning oEmbeds in core yet. See tickets:

https://core.trac.wordpress.org/ticket/31688
https://core.trac.wordpress.org/ticket/32920

Going to close this but feel free to continue discussion.

**Comment by joyously** [comment]
Did you even read the whole thing?
If I don't use an oEmbed, but actually type in editor a p with alignleft containing an iframe video, I get a problem. This screenshot shows the normal oEmbed and then the problem code I typed into the editor. Note the scrollbar at the bottom.
![aligned-iframe](https://cloud.githubusercontent.com/assets/7957680/19328568/dedbb276-9099-11e6-91a9-cf5323148157.jpg)

**Comment by joyously** [comment]
The problem is caused by floating the parent of the iframe that has a width attribute. The iframe has a max-width of 100%, so without the float, it doesn't get any bigger than that. As soon as the parent is floated though, the parent is as wide as its children, so the width attribute wins. This happens with an image also, so it's not just an iframe.

**Comment by josephfusco** [comment]
Yes, I read the whole thing :)

From my understanding though alignment classes generated from core are only intended for images & captions?

**Comment by joyously** [comment]
You can't stop users from using classes that a theme is required to supply.

**Comment by joyously** [comment]
The fix could be using `overflow: hidden` on one of the many containers in the hierarchy. Isn't that one of the theme review points (no overflow)? I think it used to be, but I don't find it in the new theme review pages.
