### ISSUE TITLE
Images with captions have a lot of extra space on the left

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#272]
They look like:

<img width="635" alt="screen shot 2016-10-12 at 8 24 27 pm" src="https://cloud.githubusercontent.com/assets/2846578/19332522/ca920a92-90ba-11e6-9c83-59725658a0b5.png">

They should look like:

<img width="644" alt="screen shot 2016-10-12 at 8 24 41 pm" src="https://cloud.githubusercontent.com/assets/2846578/19332523/d4ee2fa2-90ba-11e6-91c1-6af72e61525a.png">

**Comment by mor10** [comment]
See #256 

A PR has already been submitted.

**Comment by melchoyce** [comment]
Thanks @mor10. Closing as duplicate.
