### ISSUE TITLE
"Scroll down" arrow in homepage menu is misaligned

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#273]
The "scroll down" arrow in the menu is 10px too low:

![screen shot 2016-10-12 at 9 21 04 pm](https://cloud.githubusercontent.com/assets/2846578/19333216/efa4bc42-90c1-11e6-94d4-7f3b489378fe.png)

It should be vertically centered within the menu.

**Comment by akshayvinchurkar** [comment]
#278 request will fixed this issue

**Comment by davidakennedy** [comment]
Fixed here: https://github.com/WordPress/twentyseventeen/commit/71430139d7bb1046a30b628b4f2094461274e1ef
