### ISSUE TITLE
Customize Audit

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#279]
Default themes should follow the [best practices](https://developer.wordpress.org/themes/advanced-topics/customizer-api/) for the customizer, leverage its latest features, and lead by example in the code and inline documentation.

There are numerous (mostly minor) problems that I've noticed so far. To minimize reworks, I'm planning to do an audit of all of the customizer-oriented code in the theme _after it merges into core_. I'll create a core ticket for that when the time comes, but also adding as an issue here now for tracking.

**Comment by grappler** [comment]
I think it is better to get the changes in before it merges into core. I think the maintainers can make a note of the problems and make sure they don't crop into future pull requests.

On a side note it would be interesting if these things could be checked with an automated system like WPCS.

**Comment by celloexpressions** [comment]
I can review before core merge, but not before the front page sections and header video pieces are resolved, as the front page stuff in particular would need major changes if it stays in the theme. I'm a lot more comfortable with SVN, so I can also actually make a patch for it at that point if needed. Either way, I'll swing back here once the front page is worked out, or when someone wants me to "go" on this.

**Comment by karmatosed** [comment]
I am closing this as we've merged, not as a 'we won't do', but as a 'it would happen over on trac'. If anything comes up and we need a trac ticket, then one can be made.
