### ISSUE TITLE
menu-scroll-down scrolls too far

### ISSUE THREAD

**Issue by joshcummingsdesign** [WordPress/twentyseventeen#280]
The menu scroll down scrolls passed the beginning of the content making it hard to read. It's set to the class '#primary', but maybe we can make it so it scrolls to where the bottom of the nav meets the top of the content.

![demo](https://cloud.githubusercontent.com/assets/11913201/19338712/9eddf456-90d3-11e6-96e2-8a3880f05990.gif)

**Comment by joshcummingsdesign** [comment]
Proposed fix in #283

**Comment by melchoyce** [comment]
Looks like this might be a duplicate of #274?

**Comment by joshcummingsdesign** [comment]
duplicate of #274

**Comment by davidakennedy** [comment]
Closing this out in favor of earlier PR. Thanks @joshcummingsdesign!
