### ISSUE TITLE
Featured image missing on front page

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#289]
You can set a featured image on the front page, but it isn't displayed anywhere. This is confusing UX and possible "loss" of content when switching an existing site to Twenty Seventeen. The image should still be displayed somewhere on the front end if it's set. It doesn't need to be hugely prominent, but should be there somewhere.

**Comment by melchoyce** [comment]
Maybe this should be handled like it is on interior pages, with the featured image showing up underneath the navigation?

**Comment by celloexpressions** [comment]
Showing it in the standard position for a single post seems like a logical approach, and shouldn't be difficult to implement.

**Comment by karmatosed** [comment]
Moved this over to trac: https://core.trac.wordpress.org/ticket/38402
