### ISSUE TITLE
Add Travis CI testing

### ISSUE THREAD

**Issue by grappler** [WordPress/twentyseventeen#29]
We had Travis CI testing TwentySixteen https://github.com/WordPress/twentysixteen/issues/49

We can most likely use the file from TwentySixteen https://github.com/WordPress/twentysixteen/blob/bf55b8fe3b3b8a3b208b80e65217016908f3d6fc/.travis.yml

**Comment by davidakennedy** [comment]
I'd be open to this if anyone wants to submit a pull request for it.

**Comment by davidakennedy** [comment]
Thanks @grappler and @josephfusco for this issue and pull request!
