### ISSUE TITLE
Blog as front page has incorrect layout when no sidebar

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/twentyseventeen#292]
When there's no sidebar, the blog index's layout is incorrect when it's set to be the front page:

![Image](https://cldup.com/TS_hw7zlTV-3000x3000.png)

There is no page title, and the content width is too wide.

It should look like this, with the title on the left:

![Image](https://cldup.com/iURRg1qPwn.thumb.jpg)

It displays as expected when the blog index is not set as the front page.

**Comment by mor10** [comment]
I thiiiiink this has been resolved in my flex PR (have to check).

**Comment by laurelfulford** [comment]
^ Got ahead of myself there :) It's just something that needs to be fixed for one of the issues in #288.

**Comment by laurelfulford** [comment]
It looks like the page title does not output when the blog index is set to the front page, in both the master and the flex PR:

https://github.com/WordPress/twentyseventeen/blob/master/index.php#L21-L24

**Comment by laurelfulford** [comment]
I've added a PR just to figure out what needs to change in the theme to fix this, code-wise, and also to have a reference for what will need to be changed to complete #288.

**Comment by laurelfulford** [comment]
I was confused - this isn't actually required for #288, but it does need to be fixed 🙂
