### ISSUE TITLE
Social Menu icons runs into footer border when there are no widgets

### ISSUE THREAD

**Issue by ryelle** [WordPress/twentyseventeen#304]
The social menu touches the footer's top border when there are no footer widgets set:

![screen shot 2016-10-13 at 9 04 24 pm](https://cloud.githubusercontent.com/assets/541093/19372307/af127b02-9188-11e6-82d2-e46538218bc9.png)

**Comment by mor10** [comment]
This is addressed in the flex PR. If the PR is not accepted another one needs to be created to address the issue

**Comment by yogasukma** [comment]
Hi, i made update locally by added margin-top: 10px, is it good?

i personally think the site info also need go down a little. 

![screen shot 2016-10-16 at 12 18 20 pm](https://cloud.githubusercontent.com/assets/1949957/19415188/b329ce20-939a-11e6-81db-ce27c4f4d991.png)

**Comment by laurelfulford** [comment]
Thanks @ysupr!

I think we want to make sure both the social icons and site information line up, even after more space is added.

I added a PR where some of the padding for the footer widgets is moved to the .wrap, so it'll still be there above the social icons when there are no footers.

@melchoyce Please let me know if there should be more or less space above the icons - thanks!: https://cloudup.com/cXnkuQjIwRd
