### ISSUE TITLE
Thumbnail images being scaled larger

### ISSUE THREAD

**Issue by jordesign** [WordPress/twentyseventeen#305]
In a recent update all images were set to width:inherit; which makes them the width of the parent container. From line 2263...

```
img {
    height: auto; /* Make sure images are scaled correctly. */
    width: inherit;  /* Make images fill their parent's space. Solves IE8. */
    max-width: 100%; /* Adhere to container width. */
}

```

A result of this is that when a thumbnail is inserted - it is scaled up to fill the container (and looks awful in the process).
![image](https://cloud.githubusercontent.com/assets/1842363/19376811/d277e952-922c-11e6-8777-43c23a727df6.png)

Can we revisit this? It strikes me the physical dimensions of the image should be a limit.
Wouldn't max-width:100%; do the same thing?

**Comment by joyously** [comment]
No, you want width:auto, which is the default, but specifying it explicitly fixes IE8.

**Comment by mapk** [comment]
I'm not seeing this issue. My thumbnails are showing up just fine with the `width: inherit;` attribute set. These are images within a post.

![thumbnails](https://cloud.githubusercontent.com/assets/617986/19405596/240a7c16-922e-11e6-9117-4d55fb106d23.png)

**Comment by jordesign** [comment]
I'm noticing it specifically on galleries - where the parent has a width set, so the image inherits it

**Comment by laurelfulford** [comment]
I'm seeing it too, on single posts that have smaller featured images. They're getting stretched to fit the full width of the window.

**Comment by laurelfulford** [comment]
@jordesign I tried moving the IE8 specific style to the IE8 stylesheet in #338 - this fixed the issue I was seeing. Does it fix what you're seeing in the galleries?

**Comment by jordesign** [comment]
Looks good to me - thanks @laurelfulford

**Comment by laurelfulford** [comment]
@jordesign Cool - thanks for checking!
