### ISSUE TITLE
twentyseventeen_posted_on has an unused variable

### ISSUE THREAD

**Issue by davidmosterd** [WordPress/twentyseventeen#309]
In template-tags.php (currently line 19) in the function `twentyseventeen_posted_on` there is a variable declared called `$separate_meta` but it seems unused. Has this something todo with the localised string or can it be removed? If the latter, I can (would love too) submit a PR.

**Comment by laurelfulford** [comment]
Good catch, @davidmosterd!

It looks like this was accidentally left behind when that function was updated. It should be safe to remove.

**Comment by laurelfulford** [comment]
Fixed in #325 and closing - thanks @davidmosterd!
