### ISSUE TITLE
Remove global $twentyseventeencounter

### ISSUE THREAD

**Issue by grappler** [WordPress/twentyseventeen#31]
Remove the `global $twentyseventeencounter;` as it is not being used anywhere. According to the inline comment `//Used in content-frontpage.php` it is used in `content-frontpage.php` but that file does not exist.

I could not find any other references to the global other than in `front-page.php`

**Comment by LittleBigThing** [comment]
The `global $twentyseventeencounter` is also used in `components/page/content-front-page-panels.php` to get the correct `theme_mod`, add a panel id, ...

**Comment by laurelfulford** [comment]
Thanks for spotting this!

As mentioned, `global $twentyseventeencounter` is used in `components/page/content-front-page-panels.php` to get the correct `theme_mod`, but the comment is wrong, which is confusing. It should be updated to point to the correct file.
