### ISSUE TITLE
Hide meta borders when meta is empty logged out

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#314]
If you're logged out and viewing a post without meta, you still see the borders coming from the empty `<footer class="entry-footer">`:

<img width="818" alt="screen shot 2016-10-14 at 12 54 48 pm" src="https://cloud.githubusercontent.com/assets/2846578/19395814/96738c78-920d-11e6-9ee6-bc375702eec9.png">

You shouldn't be able to see those borders.

**Comment by joyously** [comment]
Why is the meta empty? Not showing comment indicators or taxonomies?
This is related to a question I have about why are there no Edit links on the blog index page?

**Comment by melchoyce** [comment]
It's empty because this post doesn't have any taxonomies associated with it, and the theme hides categories if "uncategorized" is selected (which is brilliant, IMO). Comment indicators don't show up in the taxonomy area. 

The same thing seems to happen on pages, which don't have any meta anyway: 

<img width="1085" alt="screen shot 2016-10-14 at 2 04 10 pm" src="https://cloud.githubusercontent.com/assets/2846578/19397761/22ecdcdc-9217-11e6-92b6-c2e84cac1755.png">

> This is related to a question I have about why are there no Edit links on the blog index page?

Probably because I forgot to design them. @laurelfulford what are your thoughts here?

**Comment by laurelfulford** [comment]
@melchoyce ... and I forgot to ask about them during the build :) I think they could be helpful on the blog index view, if there's a location you think will make sense.

**Comment by melchoyce** [comment]
How about next to the date, like comments?

<img width="592" alt="screen shot 2016-10-14 at 2 57 58 pm" src="https://cloud.githubusercontent.com/assets/2846578/19399256/a845a150-921e-11e6-93d8-97c530d8f462.png">
