### ISSUE TITLE
#page level word-wrap: break-word causes issues

### ISSUE THREAD

**Issue by mor10** [WordPress/twentyseventeen#316]
When there are left/right aligned images in a post or page, the `word-wrap: break-word` rule defined on the `#page` ID causes words to be broken down into their individual letters. This is not ideal.

IMO `break-word` should only be applied to titles (if at all).

![broken words](https://cldup.com/Hx-rwtDsjH.png)

**Comment by melchoyce** [comment]
Ignore that reference... copied the wrong number.

I'm 100% for this change — can someone make a PR?

**Comment by samikeijonen** [comment]
I'd also test this for a very long word in the title and in the content. So that long word doesn't break the layout.

I have never actually done this but could align left/right on images take action only on larger screen sizes?

**Comment by mapk** [comment]
In response to @samikeijonen's question above about making the images themselves work differently... Adding 

```
img.alignleft,
img.alignright {
  float: none;
  margin: 0;
}
```

and then in the media query for 30em

```
img.alightleft {
  float: left;
  margin-right: 1.5em;
}
img.alignright {
  float: right;
  margin-left: 1.5em;
}
```

Seems to work and doesn't affect the text at all so we don't need to worry about long headlines. 

It's my first attempt to contribute to a theme, @melchoyce, so I'm not sure on the rules... like is this even feasible (correct approach)? I have a PR ready to go if so.

**Comment by samikeijonen** [comment]
@mapk that's the code what I was thinking. Thanks for clarifying that.

**Comment by melchoyce** [comment]
@mapk I think so! Go ahead and submit your PR and we'll take a look :)
