### ISSUE TITLE
Comment by post author SVG

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/twentyseventeen#319]
There is still missing SVG icon in "comment by post author". I'd like to add this icon directly to HTML but not sure if that's possible. It would require some sort of `is_comment_and_post_author` function and perhaps also custom `callback` function.

Or use JS for this like we possible need for quote post format icon.

This issue is also note and reminder for myself.

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38403
