### ISSUE TITLE
Disregard Featured Image on Front Page

### ISSUE THREAD

**Issue by WPDevHQ** [WordPress/twentyseventeen#32]
When a page is set as the front page and contains the featured image we end up with what feels like a double header. The ideal would be to omit the featured image on the front.

![doubleheaders](https://cloud.githubusercontent.com/assets/16872407/18408357/63ecf738-7725-11e6-900c-17673f207f62.png)

**Comment by WPDevHQ** [comment]
OK disregard this disregard proposal as I've just noticed that the reason was the designated FrontPage page had no content

**Comment by melchoyce** [comment]
The design is also changing from what's shown here, so I'm going to close this for now.
