### ISSUE TITLE
Hidden article tags on home page

### ISSUE THREAD

**Issue by ElectricFeet** [WordPress/twentyseventeen#339]
Great theme! Very impressed. Thanks 👍 

I'm playing around with it to see its potential and note that when a front-page panel is unused, the resulting html has (for example):

```
<article id="panel3" class="panel-placeholder panel twentyseventeen-panel twentyseventeen-panel3">
<span class="twentyseventeen-panel-title">Panel 3 Placeholder</span>
```

with 

```
article.panel-placeholder {
    display: none;
}

.twentyseventeen-front-page.twentyseventeen-customizer #primary article.panel-placeholder {
    border: 0;
}
```

in the CSS.

Is this correct in terms of best practice? Could the php take care of not outputting this html rather than relying on CSS?

**Comment by ElectricFeet** [comment]
Just noted that this is similar to issue #223

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38404
