### ISSUE TITLE
Potentially misaligned footer text

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#340]
I see the following and wonder if the footer link is misaligned?

![2016-10-15 at 14 18](https://cloud.githubusercontent.com/assets/253067/19410369/6fcdadf8-92e2-11e6-9764-1fe45efb0e90.png)

**Comment by melchoyce** [comment]
@karmatosed, can you make a screenshot of the whole page?

**Comment by karmatosed** [comment]
Sure, here you go:

![screencapture-local-wordpress-trunk-dev-1476543293971](https://cloud.githubusercontent.com/assets/253067/19410938/c47b2b20-92ef-11e6-99fb-163c38eeebe5.png)

**Comment by karmatosed** [comment]
Whilst investigating it seems that site-info has a margin -6%.

![2016-10-15 at 15 56](https://cloud.githubusercontent.com/assets/253067/19410956/fa3ff448-92ef-11e6-9194-3fd16329dba8.png)

**Comment by melchoyce** [comment]
Ah, seems to be related to how it's positioned when there isn't a social menu. Thanks :)

**Comment by yogasukma** [comment]
Sorry for not confirmed before, but I create pull request about this before https://github.com/WordPress/twentyseventeen/issues/342 is there anything I need to provided?

**Comment by melchoyce** [comment]
Hi @ysupr, can you add two screenshots: one of the site after your PR is applied without a social menu, and one of the site after your PR is applied with a social menu?

**Comment by yogasukma** [comment]
Ah, it seems it became another issue. 

this is applied PR without social menu
![screen shot 2016-10-15 at 11 25 58 pm](https://cloud.githubusercontent.com/assets/1949957/19411161/ddf1a432-932e-11e6-8091-23e86efc7f1e.png)

and this is after adding social menu
![screen shot 2016-10-15 at 11 27 44 pm](https://cloud.githubusercontent.com/assets/1949957/19411164/f17da38e-932e-11e6-9981-6eeb7091afcb.png)

i tried to revert the theme before applied PR but still, social menu look not good (just adding more margin in left into site info)

**Comment by yogasukma** [comment]
By new issue I mention above are, 
1. After adding the icon, site info seems forced to be centered by adding margin-left 6%. Since it percentage, I am not sure it will be center on every screen width. 
2. And the social icon hit the footer line above it

**Comment by laurelfulford** [comment]
The second one is a known issue, and has been reported here: #304 🙂
