### ISSUE TITLE
RTL fixes needed for SVG update

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/twentyseventeen#344]
Creating a ticket for some SVG + RTL issues mentioned [here](https://github.com/WordPress/twentyseventeen/pull/253#issuecomment-253379147) from #253:
- Doubled arrows in menu

![Image](https://cldup.com/aLeUVe7rBh.thumb.jpg)
- Post meta icons misaligned

![Image](https://cldup.com/787a2ciwRs.thumb.jpg)
- Comment reply icon in wrong spot

![Image](https://cldup.com/lQuG0WFoES.thumb.jpg)
- Post navigation - some Genericon cruft, and arrows need to be moved/rotated so they're pointing outwards:

![Image](https://cldup.com/2vqIBA_0VJ.png)
- Edited to add: Sticky post icon on wrong side:

![Image](https://cldup.com/-tkN_-SYTu-3000x3000.png)
- Menu icon on mobile screens:

![image](https://cloud.githubusercontent.com/assets/177561/19412168/c2230800-92c4-11e6-93af-ba3dfa79c880.png)

**Comment by samikeijonen** [comment]
Thanks @laurelfulford for checking RTL. I haven't have time to check them at all.

I try to solve remaining SVG issues (non CSS related) during Sunday. So anybody who have time feel free to create PRs for this.

**Comment by laurelfulford** [comment]
I can tackle this one @samikeijonen! I just belatedly realized I forgot to move these issues to a new spot 🙂

**Comment by samikeijonen** [comment]
Cool, thanks!

**Comment by laurelfulford** [comment]
All the reported issues should be fixed in #356.
