### ISSUE TITLE
Smaller logo size

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#345]
I uploaded the WordPress logo that I downloaded straight from .org, and it looked like this:
![twentyseventeen-logo-height-current](https://cloud.githubusercontent.com/assets/7875961/19411924/837f476c-92bf-11e6-9197-b68b5aff525d.PNG)

Most business logos used here probably shouldn't be cropped, but that's the only tool within WordPress for resizing a logo. We should probably set a smaller "recommended" logo height, at least. It's currently 500x500px. Maybe drop the height to 250px? That looks like this for a square logo:
![twentyseventeen-logo-height-250](https://cloud.githubusercontent.com/assets/7875961/19411930/9f13f284-92bf-11e6-8df8-20a4537c6877.PNG)

Note that this is in CSS, but should also be in the custom logo theme support call (I haven't checked the code there).

**Comment by joyously** [comment]
Why would the theme specify any size? It should just be the size that is uploaded.

**Comment by jordesign** [comment]
Do we need to think about allowing for HiDPi/responsive images for the logo as well?

**Comment by melchoyce** [comment]
I think this is a bug — I uploaded a 250px x 250px image and it shows up like this:

<img width="1255" alt="screen shot 2016-10-16 at 1 21 19 pm" src="https://cloud.githubusercontent.com/assets/2846578/19419343/74937608-93a3-11e6-977c-893317d11551.png">

Plus, the CSS specifies a max-width/height of 500px, which is somehow being ignored here:

`@media screen and (min-width: 48em)
.twentyseventeen-front-page:not(.no-header-image) .custom-logo-link img, .home.blog:not(.no-header-image) .custom-logo-link img {
    max-height: 500px;
    max-width: 500px;
}`

**Comment by melchoyce** [comment]
cc @davidakennedy @laurelfulford ^

**Comment by melchoyce** [comment]
> Do we need to think about allowing for HiDPi/responsive images for the logo as well?

I think this is a bug in how core itself handles images in the Customizer?

**Comment by jordesign** [comment]
Would it be overkill to add a range control to let the user set the width in css?

**Comment by celloexpressions** [comment]
The custom logo control will crop the image to the size the user specifies in the customizer, and resize it to the theme's dimensions. The theme should specify the desired size of the logo in the add theme support, as core will try to match that size as closely as possible. Flex width and height allow arbitrary aspect ratios, but one dimension will try to match the width and height numbers in the theme (potentially upsizing images).

Core will eventually add support for responsive logos, but for now, the theme-support size should be the largest that we'd want it to display. Then, we can scale it down further in css if necessary in some contexts.

**Comment by melchoyce** [comment]
> > Do we need to think about allowing for HiDPi/responsive images for the logo as well?
> 
> I think this is a bug in how core itself handles images in the Customizer?

Just for reference: https://core.trac.wordpress.org/ticket/36191
