### ISSUE TITLE
Add theme support for customize selective refresh widgets

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#346]
Literally every new theme needs to have this one line:

```
add_theme_support( 'customize_selective_refresh_widgets' );
```

Apparently that's missing from whatever base this theme was started from, so add it there right away also. Then, adjust as needed for any JS-based widget layouts like masonry (see Twenty Thirteen for an example). The UX improvement of this change is massive.

**Comment by samikeijonen** [comment]
There is a ticket waiting for this in [_s](https://github.com/Automattic/_s/issues/994) too. But no feedback so far.

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38400
