### ISSUE TITLE
Improve front page "panels" to follow core best practices

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#348]
Here's the start of what we'd need to do to make the current approach appropriate for a bundled theme in terms of the [official customize API](https://developer.wordpress.org/themes/advanced-topics/customizer-api/) guidelines and ideal UX:
- Remove the panel. Themes are strongly discouraged from using panels, especially when they're generic "theme options", and sections should always have multiple controls when possible. All of the controls in the panel belong in a single section.
- Consider moving the layout control to a separate section, or if it stays in theme options, consider adding at least one other related option so we have multiple controls in this section. Or, remove this control entirely. It seems like the two-column layout is signature of this theme, so it seems a bit odd to have an option to turn it off.
- If the layout control stays, it needs to update with postMessage, by toggling a body class.
- Consider moving the front page content controls to the static front page section.
- Replace the arbitrary number of panels with a dynamic approach. In the customizer, this could be done with a single `dropdown-pages` control (which will soon be able to create pages), and a minimal custom control in the theme that shows the selected items and allows them to be removed. This would be stored as an array of featured page ids, similar to the proposed core approach. For simplicity in the theme, reordering wouldn't be supported, but we'd get a lot of the UX ideas developed for core carried over.
- Remove the borders around sections - they prevent users from seeing the design as it will be published.
- Implement selective refresh for the front page content, which will bring visual edit icons as well.

Once we get into it we'll likely have more issues come up, and some of those things can potentially be skipped, but this is a rough list of what we need to work through if it stays in the theme. We should not merge the theme into core with the current solution as-is because it violates the best practices with panels that we're trying really hard to encourage themes to follow.

**Comment by davidakennedy** [comment]
Thanks for bringing this up @celloexpressions!

These are all good ideas, and I agree with many. It will depend on time as to how much we can knock out before merge.

> Remove the panel. Themes are strongly discouraged from using panels, especially when they're generic "theme options", and sections should always have multiple controls when possible. All of the controls in the panel belong in a single section.

This shouldn't be too hard to do, and I don't think it will impact the experience there at all.

> Consider moving the layout control to a separate section, or if it stays in theme options, consider adding at least one other related option so we have multiple controls in this section. Or, remove this control entirely. It seems like the two-column layout is signature of this theme, so it seems a bit odd to have an option to turn it off.

I'd be against removing it or putting it in a different area. This seems far better than using page templates to tweak a layout. And many users will want this type of functionality – especially for a business theme.

> If the layout control stays, it needs to update with postMessage, by toggling a body class.

A good enhancement idea for the future.

> Replace the arbitrary number of panels with a dynamic approach. In the customizer, this could be done with a single dropdown-pages control (which will soon be able to create pages), and a minimal custom control in the theme that shows the selected items and allows them to be removed. This would be stored as an array of featured page ids, similar to the proposed core approach. For simplicity in the theme, reordering wouldn't be supported, but we'd get a lot of the UX ideas developed for core carried over.

A good idea, but that's largely what [#37974](https://core.trac.wordpress.org/ticket/37974) is trying to solve, and I think the solution is better explored as part of Core.

> Remove the borders around sections - they prevent users from seeing the design as it will be published.

We could possibly iterate here, and do have an issue for it. #224

> Implement selective refresh for the front page content, which will bring visual edit icons as well.

I'm hoping to get this done before merge.

**Comment by celloexpressions** [comment]
For the layout control, we'd want it to be in a separate section probably, since it's contextual differently from the other controls. Twenty Eleven has a layout section, actually. "Theme options" could work for the layout control, but doesn't make sense for the front page content.

I'll open a separate issue for `postMessage` for the layout. That needs to be in 1.0 but can happen after merge.

With #307, we can probably have an arbitrary number with minimal technical challenges, or at least make the number filterable. A minimal custom control in the theme would be appropriate without getting into the complexity of the core proposal, but isn't necessarily a requirement or even necessary to having an arbitrary number of items.

**Comment by karmatosed** [comment]
I think in this case 'Theme Options' does make sense and keeping the panel as a result works. Could this be better? Yes it could. However, we shouldn't just make the change without user testing that impact - remember we have user testing to back up this method being used.

There is some good work going on with the multi-panel, whatever direction we take the ball is rolling on thoughts and prototyping there.

My vote is UX wise and UI wise we keep Twenty Seventeen as we have now and do not at this last minute change that.

**Comment by davidakennedy** [comment]
@karmatosed brings up some good points. I would be nervous about making changes at this point.

What's in the theme now has been in since the initial commit and has always been the fallback plan for the front page should multi-panels not happen in Core this release. It's important that we don't make any rash decisions.

I do think work can be done on moving to selective refresh, using postMessage on the layout control and iterating on the borders.

**Comment by celloexpressions** [comment]
Bundled themes should not blatantly ignore the core recommended best practices, period. There is no need whatsoever for a panel with several sections that have one control in each. That's the definition of the purpose of a section - a UI container for controls (plural). Quoting directly from the official documentation (linked above):

> **Themes should not register their own panels in most cases**. Sections do not need to be nested under a panel, and each section should generally contain multiple controls. 

Additionally, the current usage violates the intended purpose of panels. "Theme Options" is essentially meaningless as a context. I know that's the .com standard for sections added by themes, but prior default themes have several examples of custom sections that state their purpose specifically. And panels should never be generic:

> More than simply grouping sections of controls, panels are designed to provide distinct contexts for the Customizer, such as Customizing Widgets, Menus, or perhaps in the future, editing posts.

Since the layout and front page controls aren't ever shown at the same time, for discoverability it would be better for these to live in different sections where the whole section is contextual if necessary. Users would still only see one of the section at a time, but the section better reflects its contents, and the fact that different options are available in different views. Think about the "Featured Content" section in Twenty Fourteen and the "Layout" section in Twenty Eleven. How are these options different conceptually from those?

 You continue to claim there's user testing for this approach and that we shouldn't change because of it. That's great, but unless it's made public, it's hard to judge how it applies to core or a default theme. Having individual controls in a single section vs. multiple sections shouldn't cause confusion in terms of user testing - it's about UI consistency with how core works. And in fact, you show the same UI in a more succinct layout that better reflects how core sections work. In terms of core, this approach has only been around for about a month, and it's received very little feedback because of the focus on a core solution.

Selective refresh should also be added for all new settings because of its many benefits, and I'm also now updating the documentation to formally recommend that approach.

Any changes here are only last minute because no one has really dug into the current approach in the theme yet due to the ongoing work on an alternative solution. That's an indication that we're short on time for this theme in general, but not an excuse for lowering our standards. I've had the recommendations here ready since the initial commit of the theme, but held them to avoid distractions while the core solution was worked through.

**Comment by karmatosed** [comment]
Moved to trac here: https://core.trac.wordpress.org/ticket/38399 - also suggested this gets split on trac into separate tickets as easier to get head around.
