### ISSUE TITLE
Consider styling ::selection

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#352]
A lot of users have a habit of selecting text as they read content (myself included). This tends to look pretty bad with the default OS/browser text selection colors. How would we feel about styling it with the theme? I'm thinking maybe the `#666` color, keyed to the color scheme, as the background-color, with `#fff` as the text color:
![twentyseventeen-selected-text-666](https://cloud.githubusercontent.com/assets/7875961/19412211/bf04cad6-92c5-11e6-91b9-d72298c68fdd.PNG)

**Comment by karmatosed** [comment]
Your highlight treatment brings up a lot of the readability issues with the hover treatment - it would be great to not add it in another place. https://github.com/WordPress/twentyseventeen/issues/222

**Comment by celloexpressions** [comment]
The only part that changes over the browser default is the color, so I don't know that those issues apply as much here, since they're fairly universal. If we're concerned about that, we'd need to fix it for `::selection` regardless of styling the colors, but I'd be okay with fixing the colors only. For reference, I currently get this:
![twentyseventeen-selected-text-default](https://cloud.githubusercontent.com/assets/7875961/19412308/fbbed5b4-92c7-11e6-905f-95bbe5d0e4ed.PNG)

**Comment by karmatosed** [comment]
The color is the issue. For example most accessible cases of selection use a highlight color over the darker tones. Actually leaving it up to the browser and user preference isn't a bad thing sometimes.

We should be super careful of not having something similar to hover for example - although we may be changing that. One thing I tend to do a lot is use a yellow highlight for selection - this works really well for a lot of users.

**Comment by melchoyce** [comment]
Since we don't have a strong color palette to draw from, I'm thinking in this case we should leave the styling to browsers.

**Comment by davidakennedy** [comment]
I would agree on leaving this because of the monochromatic nature of the theme.
