### ISSUE TITLE
'Edit %s' is not good for msgid. It is too difficult to translate to some language (for example,  to Japanese).

### ISSUE THREAD

**Issue by tg29359** [WordPress/twentyseventeen#382]
'Edit %s' is not good for msgid. 
The msgid must be something like `'Edit<span class="screen-reader-text"> "%s"</span>'`.

Why?

%s is text for screen reader.
The text is invisible for persons using visual web browser.
In some language, there must be something like preposition between 'Edit' and %s.
For example, in some language, 'Edit %s' may be translated to 'Edeata voneata %s' .
'Edeata' means 'Edit', and 'voneata' means something like preposition.
But in the same language, 'Edit' (without %s') may be translated to only 'Edeata' without 'voneata'.

In Japanese, 'Edit %s' is usally translated to '%s を 編集'.
'編集' means translation for 'Edit', and 'を' means something like preposition.
But 'Edit' (without %s) is usally translated to only '編集', without 'を' that  is something like preposition.

Thus. Japanese readers using visual web browser will see on the screen 'を 編集' without %s.
It will be very strange for Japanese that 'を' appears without %s.

From these reasons, in Twenty Sixteen, msgid 'Edit %s' has been changed to`'Edit<span class="screen-reader-text"> "%s"</span>'`. and it was translated to `'<span class="screen-reader-text">"%s"を</span>編集'` in Japanese. The span is the text for screen-reader, and the persons using visual reader don't see 'を' (something like preposition) without %s.

The same change will be needed about Twenty Seventeen.

**Comment by laurelfulford** [comment]
Closing - fixed in #399.
