### ISSUE TITLE
Failed opening required 'color-patterns.php'

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/twentyseventeen#384]
Loading `color-patterns.php` failes when using `require_once( 'color-patterns.php' );`. I can see this error in the Customizer.

**Comment by celloexpressions** [comment]
Do you have this file in your copy of Twenty Seventeen? It was added recently.

**Comment by samikeijonen** [comment]
Yes in inc folder. I can check when back on computer.

**Comment by celloexpressions** [comment]
Fix in https://github.com/WordPress/twentyseventeen/commit/4ba0a7cd5fe324074e767082f7494fa256719238, I'm guessing.
