### ISSUE TITLE
Potentially make the pin icon for sticky posts smaller

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#386]
I maybe think it should match the line height over what we have:

![2016-10-16 at 15 08](https://cloud.githubusercontent.com/assets/253067/19417985/91ff88b2-93b2-11e6-802d-5390b5cf03a8.png)

**Comment by melchoyce** [comment]
Agreed. Easier to do now that it's an SVG. :)

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38407
