### ISSUE TITLE
Nexus 6P : Arrow and Pin icon adjustments

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#387]
These seem to be too close on smaller devices, I discovered this on Nexus 6P.

![2016-10-16 at 15 19](https://cloud.githubusercontent.com/assets/253067/19418062/29102f44-93b4-11e6-85ea-c31391a03fc5.png)

**Comment by alaczek** [comment]
Same thing happens to the sticky post pin on iPhone 5S:

![image](https://cloud.githubusercontent.com/assets/4550351/19465040/bfb01678-954c-11e6-98d6-93853a5ea972.png)

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38406
