### ISSUE TITLE
Browser testing thread issue

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#388]
As each browser is tested please note here - anyone can help with this the following browsers at minimum we need to test:
- [x] - IE 9
- [x] - IE 10
- [x] - IE 11
- [x] - Safari latest
- [x] - Firefox latest
- [x] - Chrome latest
- [x] - Opera latest

**Comment by joyously** [comment]
And mobile browsers?

**Comment by celloexpressions** [comment]
List is missing Edge (the replacement for IE). I'll test there in a bit.

**Comment by celloexpressions** [comment]
Edge looks like no issues that aren't present on other browsers.

**Comment by karmatosed** [comment]
@joyously we have another ticket for mobile.

**Comment by karmatosed** [comment]
Closing as complete also we are now on trac and have more testers.
