### ISSUE TITLE
Device testing issue thread

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#389]
Here are the devices we are testing, as you test note and we can then cross off each device.
- [x] - Android phone
- [x] - Android tablet
- [x] - iPhone 6
- [x] - iPhone 6 plus
- [x] - iPhone 5
- [x] - iPad mini
- [x] - iPad retina air or normal size
- [x] -Amazon fire

**Comment by karmatosed** [comment]
Nexus 6P: issues logged from this so did not pass 100%.

https://github.com/WordPress/twentyseventeen/issues/387

**Comment by karmatosed** [comment]
Amazon Fire tested and no new issues.

**Comment by karmatosed** [comment]
Android tablet I tested was Galaxy Note 2 and found a rendering issue.

https://github.com/WordPress/twentyseventeen/issues/392

**Comment by karmatosed** [comment]
iPhone 6 tested and no new issues

**Comment by karmatosed** [comment]
iPhone 6 plus tested and no new issues

**Comment by celloexpressions** [comment]
Tested in Edge 38 on Windows Phone 10 and found one issue: #393. However, I believe that this issue will affect all small-screen touch devices. Otherwise, looks good.

**Comment by samikeijonen** [comment]
Is there live demo site where I could test with my device?

**Comment by karmatosed** [comment]
@samikeijonen there is not, you have to set up on hosting or test via local tunnel yourself at this point.

**Comment by alaczek** [comment]
iPhone 5s tested, 4 issues found: #454, #453, #449, #387

**Comment by alaczek** [comment]
iPad mini 2 retina tested, two issues found: #450, #449 

@karmatosed which device did you have in mind for iPad retina? Could we count my testing on iPad mini 2 retina towards that?

**Comment by karmatosed** [comment]
@alaczek I think we should potentially have a non mini iPad but your testing still counts for iPad Mini.

**Comment by karmatosed** [comment]
Closing as complete.
