### ISSUE TITLE
Customizer panel number naming

### ISSUE THREAD

**Issue by grappler** [WordPress/twentyseventeen#39]
What is the reason to have the panels numbered as `twentyseventeen_panel1` with the numbers sticking to the last work instead of using an underscore to separate the number to make it easier to read e.g. `twentyseventeen_panel_1`?

**Comment by laurelfulford** [comment]
Good call! I agree that separating the number with an underscore would make these easier to read. There isn't a reason to keep them stuck together.

**Comment by celloexpressions** [comment]
I'll note here that this code should probably be restructured if anyway if we keep it like this, but it's likely to be changed based on the core discussions anyway.
