### ISSUE TITLE
List styles hang over edge outside of content

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#390]
This could be a design decision, but worth checking.

![2016-10-16 at 15 30](https://cloud.githubusercontent.com/assets/253067/19418127/a39a1dfa-93b5-11e6-836c-73e33af8573d.png)

**Comment by joyously** [comment]
I mentioned this somewhere....can't find it. I was told it was typography.

**Comment by celloexpressions** [comment]
This seems fine as a design decision, but causes issues on mobile. Should probably adjust it there.

**Comment by melchoyce** [comment]
This is a design decision, so I'm going to close. Spacing on mobile discussed in #195.
