### ISSUE TITLE
Mobile menu parent items require double tap

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentyseventeen#393]
Because of the code in place to make sub-menus accessible on larger screens, the first tap on a parent menu item on mobile does nothing. It should either open the submenu (duplicating the action of tapping the dropdown arrow) or navigate to the top-level item on the first tap. However, it's important that the current behavior be maintained on larger screens. I'd suggest adding a conditional for the screen size in the JS that handles this.

Testing in Edge 38 on Windows Phone 10.

**Comment by davidakennedy** [comment]
Thanks @celloexpressions! Worth noting that Twenty Sixteen has this issue as well.

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38397
