### ISSUE TITLE
Clean style guide

### ISSUE THREAD

**Issue by noplanman** [WordPress/twentyseventeen#400]
Browsing through the code and fixing various typos in the documentation/comments, I saw that there are different "styles" of code in different places, it's not all the same.

A few examples:
- Empty first and last lines within functions. ([yes](https://github.com/WordPress/twentyseventeen/blob/c947bc852ebfa71a894d56e09a3dd8a9e08edd67/inc/icon-functions.php#L13) vs. [no](https://github.com/WordPress/twentyseventeen/blob/c947bc852ebfa71a894d56e09a3dd8a9e08edd67/inc/back-compat.php#L21))
- Empty line before `return`. ([yes](https://github.com/WordPress/twentyseventeen/blob/48b3f21ad6d13cb906c6e83fb9e1a1e98285537c/functions.php#L311) vs. [no](https://github.com/WordPress/twentyseventeen/blob/48b3f21ad6d13cb906c6e83fb9e1a1e98285537c/functions.php#L332))
- Inline PHP code aligned with `<?php` tag vs non-aligned. ([yes](https://github.com/WordPress/twentyseventeen/blob/3492881c7dcec6b2d83994e1839605e2d190553d/footer.php#L21) vs. [no](https://github.com/WordPress/twentyseventeen/blob/bbe44a78e88180d098aac7fe1c3cd5300e1263d0/single.php#L19))
- etc.

(Links are just to illustrate what I mean)

Being a purist who loves clean and "pure" code, I'd offer to clean it all up.

But before I start, would this even be appreciated?

**Comment by davidakennedy** [comment]
@noplanman Go for it. This is on my last as a thing to do tomorrow and Tuesday. But if you can get it going that would be great. Thank you!

**Comment by noplanman** [comment]
Ok, will make two PRs, one for the documentation part (#402), one for the code (#416).

Is that ok for you? Just trying to find a way that will make the merge easier and keep conflicts as low as possible.

**Comment by davidakennedy** [comment]
@noplanman That's reasonable. 😄

**Comment by davidakennedy** [comment]
@noplanman By the way, follow WordPress coding standards.

**Comment by noplanman** [comment]
@davidakennedy Of course 😉

**Comment by noplanman** [comment]
There are some things that aren't explicitly stated in the WP coding standards, which seem to be up to the developer to decide.

Namely:
- Empty space before a `return` statement.
- String concatenation. (`$str = $str . " plus."` vs `$str .= " plus."`
- Indentation of inline PHP blocks.

Regarding the inline PHP block indentation, the coding standards page has a small code snippet, but I don't know if it's just an example to illustrate something else or if it also defines how the indentation should be done.

Here the snippet (from [here](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/)):

``` php
<?php if ( have_posts() ) : ?>
    <div class="hfeed">
        <?php while ( have_posts() ) : the_post(); ?>
            <article id="post-<?php the_ID() ?>" class="<?php post_class() ?>">
                <!-- ... -->
            </article>
        <?php endwhile; ?>
    </div>
<?php endif; ?>
```

Shall I do it like this, so that each `<?php` has it's own indent level?
I feel this is a very personal preference, as there are so many different ways of doing this.

**Comment by davidakennedy** [comment]
Both merged! Nice work @noplanman!

**Comment by noplanman** [comment]
You're so welcome 😊 

Any idea when the theme will be released into the wild?

Will brush over the code again before that.
