### ISSUE TITLE
Use consistent syntax for control structures

### ISSUE THREAD

**Issue by grappler** [WordPress/twentyseventeen#41]
The alternative syntax for control structures (e.g. `if/endif`, `while/endwhile`) in used in a number of places where the code is pure PHP and not switching between PHP and HTML.

We should switch to using braces/brackets in these places.

https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style

**Comment by davidakennedy** [comment]
Looks good, @grappler – thank you!
