### ISSUE TITLE
Simplify header between front-page and interior pages

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#413]
After watching a couple conversations unfold across issues, and my own testing, I’ve come to realize that removing the header image on interior pages is a mistake. 

I think we should still show a collapsed header on interior pages, but include a sliver of the header image, along with the gradient overlay. This simplifies a number of issues:
- It fixes #225, and the eliminates any confusion around the header text color picker.
- It makes it easier to add a logo and have it look good on your homepage and your interior pages. Currently a lighter logo might look good on the homepage, but a dark logo looks better on interior pages. Now, the contrast will be the same so the same logo looks good in both locations.

@ryelle is working on a PR. (#414)

**Comment by davidakennedy** [comment]
Addressed in #481.
