### ISSUE TITLE
Let people make empty menus

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#425]
If I'm making a one-page website, I'll often unassign the menu so it disappears. Sometimes this works in themes (woohoo!) and sometimes it doesn't (sad).

I'm thinking that if a menu isn't assigned, we should hide the menubar, rather than showing all of your site's pages by default.

@laurelfulford / @davidakennedy what are your thoughts here?

**Comment by laurelfulford** [comment]
Ah, that's a good point about a one page website not necessarily needing a menu. I'd be fine with there being no fallback menu, to make it easier for users to leave one out.

**Comment by slaFFik** [comment]
There is a possibility to do that. But the end result looks ugly.
Create a menu, uncheck "Automatically add new top-level pages to this menu" checkbox, assign it to "Top" menu location and DO NOT add pages/links/whatever to that menu.

Here is how it will look like:

![image](https://cloud.githubusercontent.com/assets/282234/19453308/5e05b1c4-94bd-11e6-8e69-898e23ab9919.png)

**Comment by celloexpressions** [comment]
The menu fallback should probably be removed, and the styling should also be updated to handle an empty menu as the above screenshot shows.

**Comment by melchoyce** [comment]
Ideally that would be fixed, so the whole bar would disappear. :)

**Comment by samikeijonen** [comment]
+1. I'd say in 99.9% of sites there is need for custom menu or not menu at all.

**Comment by enodekciw** [comment]
If you decide to get rid of wp_nav_menu fallback, PR #458 should resolve this.

**Comment by davidakennedy** [comment]
I'm for this, as I think it allows more flexibility for users. I just want to make sure nothing is missed. Will review the pull request.

**Comment by laurelfulford** [comment]
Merged #458 to fix - thanks @enodekciw!
