### ISSUE TITLE
When "One Column" is set, home page should also be one column

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#439]
When you set "One Column" in the Customizer:

<img width="296" alt="screen shot 2016-10-17 at 9 50 23 pm" src="https://cloud.githubusercontent.com/assets/2846578/19461581/c1c86ada-94b3-11e6-82d3-57f79d883dd1.png">

...I think it should apply to your homepage too, so all of your pages are one column. This goes for both a static page homepage, and a posts-on-front homepage. (This means we should also show that Customizer option when you're on the homepage, probably underneath the Panels sub-panels).

**Comment by alaczek** [comment]
I second that! I was very confused when the number of columns option disappeared on me on the front page.
