### ISSUE TITLE
Demo at wp-themes.com

### ISSUE THREAD

**Issue by superpoincare** [WordPress/twentyseventeen#44]
Will be great if there's a demo like https://wp-themes.com/twentytwelve/

**Comment by melchoyce** [comment]
Sounds like this happens automatically once a theme is uploaded to WordPress.org. I'm going to close this for now but please re-open if I'm wrong and there's something manual we'll need to do later.

**Comment by BharatKaravadra** [comment]
Hello vijayaraghavanramanan and all,
I have created a demo at the link below. It had the '"Hello world!" post and the "Sample Page" and I am adding more content as we go.
It's [https://tryit.tv/twentyseventeen/]

**Comment by BharatKaravadra** [comment]
A demo page with HTML elements is now at the link below. Let me know if anything else should be added.
https://tryit.tv/twentyseventeen/html-elements/
