### ISSUE TITLE
Basic HTML elements styling

### ISSUE THREAD

**Issue by alaczek** [WordPress/twentyseventeen#440]
I was looking at the default test data, and saw that tables don't seem to have any noticeable styling:

![image](https://cloud.githubusercontent.com/assets/4550351/19461870/0884405e-9534-11e6-8c7e-96ee1ba537b4.png)

The order list styling felt a bit off to me as well - my instinct would be to have a dot after each number.

![image](https://cloud.githubusercontent.com/assets/4550351/19461862/edacd94e-9533-11e6-91d7-4c3052399936.png)

Blockquotes - should `<cite>` element be displayed in a new line and maybe styled a bit differently?

![image](https://cloud.githubusercontent.com/assets/4550351/19461891/374e620c-9534-11e6-9b9e-89a773b5ce5e.png)

I wasn't sure if those were purposeful design decisions or not.

**Comment by melchoyce** [comment]
Tables: #444
OLs: #441 
Blockquote Cites: #443 

Thanks for finding these, @alaczek!

**Comment by davidakennedy** [comment]
Merged all three.
