### ISSUE TITLE
"Scroll down" arrow misaligned

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#446]
Looks like it's gotten misaligned again within the past couple days:

<img width="1251" alt="screen shot 2016-10-17 at 11 26 54 pm" src="https://cloud.githubusercontent.com/assets/2846578/19463341/39623a14-94c1-11e6-91a9-9ac97e368db8.png">

**Comment by melchoyce** [comment]
Can we use flexbox for this? :)

**Comment by akshayvinchurkar** [comment]
i think i fixed this issue
