### ISSUE TITLE
iPad mini, iPhone 5: Search form and button rendering issues

### ISSUE THREAD

**Issue by alaczek** [WordPress/twentyseventeen#449]
- **on iPad mini 2 retina:**
  ![image](https://cloud.githubusercontent.com/assets/4550351/19464433/f48bd274-9547-11e6-9ae3-9d8f9f65c7dc.png)
- **on iPhone 5S:**
  ![image](https://cloud.githubusercontent.com/assets/4550351/19464498/7ad8542e-9548-11e6-8a74-15a9a4d3c44a.png)

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38396
