### ISSUE TITLE
Font Loading Optimizations

### ISSUE THREAD

**Issue by superpoincare** [WordPress/twentyseventeen#45]
Unlike other fonts such as Open Sans for Twenty Twelve which has nuances such as unicode-range and looks best to load from Google, I think Twenty Seventeen can load fonts from the theme files or from s.w.org. This is because the Google fonts used in Twenty Seventeen have minimal characters, unlike Open Sans. 

In addition, the @font-face can be inlined in the HTML so that it is fetched sooner than going a few round-trips with fetching the css, waiting for the CSSOM to be ready. 

Another optimization is to make preload declaration for woff2 and use the font-face API (javascript) for browsers with no preload support to load a few styles so that the fetching can happen instead of lazy loading fonts. 

Hosting the files with the theme, as compared to hosting at s.w.org has more benefits: the advantage of being pushed - i.e., HTTP2 server push can be used. 

Some ideas for font-loading optimization.

**Comment by davidakennedy** [comment]
Hey @vijayaraghavanramanan! Thank you for the thoughts here! A few questions come to mind:
- What would the gain be on load times?
- What does this mean for different hosting environments? Any side effects?
- What would this mean for child themes?

I'm not very familiar with these techniques so I'd like to talk about them a bit more. Examples, articles, etc. would be great.

**Comment by superpoincare** [comment]
Hi @davidakennedy 

Two articles come to mind: 

Ilya Grigorik's [Web font optimization](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=en)

Zach Leat's [Comprehensive Guide to Webfont Loading Strategies](https://www.zachleat.com/web/comprehensive-webfonts/)

Both articles go into how different strategies improve load times. 

Currently, bundled themes mostly use Google fonts and what happens is that the css blocks page rendering and then waits for CSSOM to be build to decide which fonts to download.

So the strategy would be to preload fonts using [link rel="preload"](https://www.w3.org/TR/preload/) and also use [font-display](https://plus.google.com/+IlyaGrigorik/posts/a3Yn3jB4wjA)

For browsers that do not have preload support, fonts can be fetched in advance by using the font-loading API (first link). 

I don't have numbers but improvement can be as high as 1s or even more. 

I don't think it will have an effect on hosting environments unless fonts are self hosted. If the fonts are say hosted on s.w.org, this will have zero effect on the website hosting server as these optimizations are just links, css and javascript. If the fonts are however self-hosted, then it might put some load on the server as they need to be downloaded from that. 

I am not sure what you had in mind when asking about child themes but I think since Wordpress now has wp_resource_hints and wp_add_inline_script they can easily be dequeued in child themes if the theme user decides to do something else.

**Comment by davidakennedy** [comment]
Thanks for the links and thoughts @vijayaraghavanramanan!

After reading over some of this, here's where I'm at:
- Browser support for many of these methods looks poor for the most part.
- It seems like the implementation would need to change drastically, and I'm not sure how realistic that is at this point, especially if we're uncertain of the exact gains.
- It feels like this would require more code that is harder to understand for many people. I want Twenty Seventeen to be as fast as possible, but I also want the code to be lean. It's less art and science and more craft. So a balance.

Right now, I'm leaning toward leaving it as it is, but I'm open to seeing an implementation of one or some of these methods. I'd also be open to doing something future-friendly. Meaning, if a browser supports it, it works, and if not, nothing is harmed and the current implementation wouldn't need to change drastically.

I'm going to leave this open for now so others can add any thoughts or experiment.

**Comment by melchoyce** [comment]
Since there hasn't been any movement on this issue in over two weeks, I'm going to close it out. If anyone has any more thoughts, please feel free to open a new ticket. :)
