### ISSUE TITLE
iPad mini: Images on the front page badly pixelated

### ISSUE THREAD

**Issue by alaczek** [WordPress/twentyseventeen#450]
On iPad mini 2 retina in landscape mode both custom header image and panel images appear to be enlarged and badly pixelated:
![image](https://cloud.githubusercontent.com/assets/4550351/19464532/cc75e8aa-9548-11e6-9b37-1372d638361c.png)

![image](https://cloud.githubusercontent.com/assets/4550351/19464535/d0a07954-9548-11e6-9a68-4a35dc02ef34.png)

In portrait mode images display correctly:
![image](https://cloud.githubusercontent.com/assets/4550351/19464542/e407c6f0-9548-11e6-9488-37c329ff3478.png)

Original size of featured image above is 2400x1600.

Featured images on single posts/pages look good as well.

**Comment by laurelfulford** [comment]
Looks like this is related to `background-attachment: fixed`. 

Altering the breakpoint for where this is 'turned off' should help.

**Comment by karmatosed** [comment]
Moved over to trac: https://core.trac.wordpress.org/ticket/38395
