### ISSUE TITLE
Colors: Header background, gallery images and captions, widget images, tables missing

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#452]
Interior page headers:
<img width="1240" alt="screen shot 2016-10-18 at 12 47 50 am" src="https://cloud.githubusercontent.com/assets/2846578/19464764/ece64f20-94cc-11e6-8aa5-d47229dad261.png">

Galleries:
<img width="748" alt="screen shot 2016-10-18 at 12 48 01 am" src="https://cloud.githubusercontent.com/assets/2846578/19464761/ecdb6b14-94cc-11e6-88d0-a6d5dd08963c.png">

Widget image (linked):
<img width="556" alt="screen shot 2016-10-18 at 12 48 33 am" src="https://cloud.githubusercontent.com/assets/2846578/19464763/ece52a0a-94cc-11e6-98e6-7243cb7e5d93.png">

Tables only just got merged: 
<img width="747" alt="screen shot 2016-10-18 at 12 48 11 am" src="https://cloud.githubusercontent.com/assets/2846578/19464762/ece47a7e-94cc-11e6-8c7e-be83a04d9ab4.png">

**Comment by celloexpressions** [comment]
I can grab these with my style.css-to-colors re-sync on Thursday (after merge).

**Comment by karmatosed** [comment]
Moved to trac and assigned to you @celloexpressions as mentioned you'd tackle this, thanks.

https://core.trac.wordpress.org/ticket/38389
