### ISSUE TITLE
iPhone 5s: Logo cut-off when using default custom header image

### ISSUE THREAD

**Issue by alaczek** [WordPress/twentyseventeen#453]
On iPhone 5s in portrait mode the logo is cut-off, if used together with custom header image:

![image](https://cloud.githubusercontent.com/assets/4550351/19464840/2e28b206-954b-11e6-8d16-dad563386f80.png)

Logo displays correctly when in landscape mode or if I remove the header image.

![image](https://cloud.githubusercontent.com/assets/4550351/19464830/1949747e-954b-11e6-8da1-14b0296f1a5e.png)

The size of the logo image used is 300x300px.

**Comment by laurelfulford** [comment]
Was incidentally fixed in #481; closing!
