### ISSUE TITLE
iPhone 5s: Next/previous arrow awkwardly pushed below posts navigation

### ISSUE THREAD

**Issue by alaczek** [WordPress/twentyseventeen#454]
The next/previous arrow in posts navigation can get awkwardly pushed below the page-numbers in portrait mode:

![image](https://cloud.githubusercontent.com/assets/4550351/19464935/168fdbb4-954c-11e6-8514-989c067edbf1.png)

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38394
