### ISSUE TITLE
Update wording of theme description in screenshot

### ISSUE THREAD

**Issue by josephfusco** [WordPress/twentyseventeen#464]
Related to #463 

Instead of

> Bringing your business site to life

should we do

> Bringing your business' site to life

? The first being literally a **business site**, while the latter is a **site** for your business.

**Comment by melchoyce** [comment]
@celloexpressions, what was your original intent with the tagline? I grabbed it from your earlier screenshot idea.

I don't feel strongly one way or the other, so happy to change it :)

**Comment by melchoyce** [comment]
[Cello says](https://wordpress.slack.com/archives/core-themes/p1476810188003256):

> I agree with changing the tagline since it's clearer that it's referring to the site.

I'll update the image and push up a new PR.

**Comment by laurelfulford** [comment]
Fixed in #468.
