### ISSUE TITLE
Display 'scroll down' arrow alternative when there is no menu

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/twentyseventeen#472]
From [this comment](https://github.com/WordPress/twentyseventeen/pull/458#issuecomment-254592939) by @melchoyce:

> I'm wondering if there’s any way we could make the scrollability more obvious, maybe by adding a down arrow over the header image so there’s some indication that you can scroll more. Or not taking up the whole viewport, so a little bit of the page background peeks through at the bottom.

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38392
