### ISSUE TITLE
Background colour for header

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/twentyseventeen#482]
When #481 is merged, the header background colour should be updated to work with a default white header font.

**Comment by celloexpressions** [comment]
Won't the custom color (and its white default) still only be applied when there's a header image (or video) set? The current design could probably be preserved for the no-image case if desired.

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38391

**Comment by JennyShi776** [comment]
We are able to reproduce the bug, when changed the header font to white, then the background colour became almost invisible. Potential solutions:  1. working with the background colour changed it to darker colours in contrast to the white header font (it may not be user friendly in particular for beginners or 2. add an option of background colour (so users can choose different colours as suggested by default) into the theme.

**Comment by karmatosed** [comment]
Hi @JennyShi776 development for Twenty Seventeen is now taking place on trac. If possible could you add your comment there? Here is where that ticket can be found:

https://core.trac.wordpress.org/ticket/38391

**Comment by JennyShi776** [comment]
Thank you Karmatosed, brilliant work. Magic. The added function of the Header Text Color works well. Love it thanks.
