### ISSUE TITLE
Page comments need border/spacing

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#483]
From #470:

We need to add a border/spacing to pages that have comments:

<img width="1013" alt="36bf3808-9579-11e6-991c-67a7d88e0031" src="https://cloud.githubusercontent.com/assets/2846578/19504545/1d742164-9589-11e6-98b5-1c177d437cb3.png">

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38388
