### ISSUE TITLE
Social menu SVG icons on Safari 10

### ISSUE THREAD

**Issue by afercia** [WordPress/twentyseventeen#485]
Not sure if it's just me but quickly checking the social menu svg icons, here's how they appear for me on Safari 10:

![screen shot 2016-10-19 at 08 57 42](https://cloud.githubusercontent.com/assets/1682452/19508681/cb3c0ef0-95da-11e6-9ace-40badc0823aa.png)

On Chrome they look OK:

![screen shot 2016-10-19 at 08 57 32](https://cloud.githubusercontent.com/assets/1682452/19508680/cb3a82d8-95da-11e6-8796-41499759e885.png)

**Comment by afercia** [comment]
Also, the focus style on the social menu icons is based on color only. Would need an additional indicator since color only is not enough for accessibility.

**Comment by samikeijonen** [comment]
I see the similar "flash" in Chrome on Windows but then back to normal. I don't see it on my own theme so I suspect it's CSS related.

> Also, the focus style on the social menu icons is based on color only. Would need an additional indicator since color only is not enough for accessibility.

I'd add outline (thin dotted for example) for social links also.

**Comment by samikeijonen** [comment]
I see the similar "flash" in Chrome on Windows but then back to normal. I don't see it on my own theme so I suspect it's CSS related.

> Also, the focus style on the social menu icons is based on color only. Would need an additional indicator since color only is not enough for accessibility.

I'd add outline (thin dotted for example) for social links also.

**Comment by samikeijonen** [comment]
I see the similar "flash" in Chrome on Windows but then back to normal. I don't see it on my own theme so I suspect it's CSS related.

> Also, the focus style on the social menu icons is based on color only. Would need an additional indicator since color only is not enough for accessibility.

I'd add outline (thin dotted for example) for social links also.

**Comment by samikeijonen** [comment]
I see the similar "flash" in Chrome on Windows but then back to normal. I don't see it on my own theme so I suspect it's CSS related.

> Also, the focus style on the social menu icons is based on color only. Would need an additional indicator since color only is not enough for accessibility.

I'd add outline (thin dotted for example) for social links also.

**Comment by samikeijonen** [comment]
I see the similar "flash" in Chrome on Windows but then back to normal. I don't see it on my own theme so I suspect it's CSS related.

> Also, the focus style on the social menu icons is based on color only. Would need an additional indicator since color only is not enough for accessibility.

I'd add outline (thin dotted for example) for social links also.

**Comment by samikeijonen** [comment]
I see the similar "flash" in Chrome on Windows but then back to normal. I don't see it on my own theme so I suspect it's CSS related.

> Also, the focus style on the social menu icons is based on color only. Would need an additional indicator since color only is not enough for accessibility.

I'd add outline (thin dotted for example) for social links also.

**Comment by davidakennedy** [comment]
@afercia Did you have JavaScript off?

We run a test for SVGs in JS – and if it fails, we show the screen reader text fallback there and hide the SVG... Looks like something choked.

I can't reproduce this in Safari 10.

**Comment by afercia** [comment]
> Did you have JavaScript off?
> Ugh, my bad. Sorry 😁
