### ISSUE TITLE
Keyboard navigation on Safari 10

### ISSUE THREAD

**Issue by afercia** [WordPress/twentyseventeen#486]
Not sure if it's just me but keyboard navigation on Safari 10 has some weird behaviour:
- can't open a main navigation menu drop down (works on Chrome)
- can't complete navigation of a page (any page): at some point while tabbing the tab order starts again from the root and it's impossible for me to even reach the sidebar

**Comment by samikeijonen** [comment]
> at some point while tabbing the tab order starts again from the root and it's impossible for me to even reach the sidebar

Is that point always the same point or random one?

**Comment by afercia** [comment]
Seems there are multiple points here this happen. A first one is the menu drop-down, when a navigation menu has sub-items. A second one, after tabbing on a post published date and author name (before the post title).

**Comment by davidakennedy** [comment]
Thanks @afercia! I can reproduce and this is really weird. I don't see it happening in Chrome or Firefox. I also don't see any JS errors in the console.

I'll dig in and see what's going on.

**Comment by afercia** [comment]
@davidakennedy I'm afraid it's because the SVGs, highly suspect the `use xlink` thing. Disabled JS, disabled CSS, and it still happens when tabbing on focusable elements close to each SVG:

![screen shot 2016-10-19 at 17 14 17](https://cloud.githubusercontent.com/assets/1682452/19525277/bfb47fea-9620-11e6-9e04-28856f0619b5.png)

To quickly double check, just made `twentyseventeen_get_svg()` return an empty string and the bugs disappears.

**Comment by afercia** [comment]
Seems we're not alone...
https://github.com/facebook/react/issues/7852

**Comment by samikeijonen** [comment]
That's a weird bug in Safari. Hope it will be fixed very soon.

**Comment by karmatosed** [comment]
Reported in trac: https://core.trac.wordpress.org/ticket/38387
