### ISSUE TITLE
Replace inline control structure in `twentyseventeen_content_image_sizes_attr()`

### ISSUE THREAD

**Issue by ocean90** [WordPress/twentyseventeen#494]
See https://github.com/WordPress/twentyseventeen/blob/5b5e4e86c2b8343863d7633758987da93c2bf2e8/functions.php#L317-L323.

To improve code readability the lines 317 and 321 should be changed to a proper `if ( ) {}` block. Also, per WordPress' coding standards, [yoda conditons should only be used for ==, !=, ===, and !==](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#yoda-conditions).

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38384
