### ISSUE TITLE
Incorrect use of `_x()` in `twentyseventeen_posted_on()`

### ISSUE THREAD

**Issue by ocean90** [WordPress/twentyseventeen#495]
https://github.com/WordPress/twentyseventeen/blob/5b5e4e86c2b8343863d7633758987da93c2bf2e8/inc/template-tags.php#L20

`_x()` is used to differ two similar strings with different meanings. Translators comments are used to describe placeholders.

**Comment by ocean90** [comment]
Same for `twentyseventeen_time_link()`, see https://github.com/WordPress/twentyseventeen/blob/a15f8d1ed4003007b8e25330dc787cda7b7a32f7/inc/template-tags.php#L48.

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38383
