### ISSUE TITLE
Theme Options in customizer do not appear when you have too many pages

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/twentyseventeen#496]
To replicate:  Create a few hundred thousand pages.  The customizer takes a very long time to load and theme options panel is not rendered at all.  Front page also fatal errors in the preview (even though it loads fine for me normally.

`[Wed Oct 19 15:44:59.308691 2016] [:error] [pid 21322] [client 108.30.103.76:57048] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 48 bytes) in /srv/www/ilovewhite.space/public_html/src/wp-includes/cache.php on line 672, referer: http://ilovewhite.space/wp-admin/customize.php?return=%2Fwp-admin%2Fedit.php%3Fpost_type%3Dpage`

**Comment by celloexpressions** [comment]
This is a core bug. The dropdown-pages control needs to be refactored to use something like Select2, but unfortunately that particular library isn't an option due to its inaccessibility. The Customize Posts plugin has some experiments here.

**Comment by davidakennedy** [comment]
Maybe an issue with `wp_dropdown_pages()` as well? I'm not sure this is a theme bug.

**Comment by karmatosed** [comment]
I'm going to close this potentially as a core bug as moving everything to trac. That said, if I am closing wrongly please open and issue on trac as that's where all Twenty Seventeen tickets are living now.
