### ISSUE TITLE
Filters are not documented

### ISSUE THREAD

**Issue by ocean90** [WordPress/twentyseventeen#497]
Twenty Fifteen has 5 filters and 4 are documented, Twenty Sixteen has 8 filters and 6 are documented.
Twenty Seventeen has 4 filters and none are documented. 🙂

See https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38382
