### ISSUE TITLE
Comments: Improve highlighting of post authors

### ISSUE THREAD

**Issue by ocean90** [WordPress/twentyseventeen#498]
See https://wordpress.slack.com/archives/core-themes/p1476895277003400

<img width="263" alt="twentyseventeen-post-author" src="https://cloud.githubusercontent.com/assets/617637/19528398/2944946c-962c-11e6-9c0c-55f4da2721e9.png">

@melchoyce mentioned that there should be an icon.

**Comment by davidakennedy** [comment]
Already an issue here: #319. Closing.
