### ISSUE TITLE
Code, escaping and security review

### ISSUE THREAD

**Issue by davidakennedy** [WordPress/twentyseventeen#5]
Make sure everything that needs to be escaped is escaped and that the theme follows security best practices. It should also follow WordPress coding standards.

**Comment by davidakennedy** [comment]
@aaroncampbell performed a general code review. He brought two minor issues up, highlighted here:

https://wordpress.slack.com/archives/core-themes/p1476744628003193

> I didn't get to go through the whole thing line for line yet, but I did make it through quite a bit. So far I'm not seeing anything very major. I don't like using the `﻿⁠⁠⁠⁠740 <= $width && $sizes = 'something';﻿⁠⁠⁠⁠` syntax because it's non-standard and we don't use it anywhere else. Also, ﻿⁠⁠⁠⁠`switch_theme()`﻿⁠⁠⁠⁠ doesn't need the second parameter anymore (looks like this has been pulled from theme to theme for a while). Nothing that I would consider to be merge-blocking.

He'll continue to review, but:

> I'm comfortable for merge. We can still do a bit of this kind of fixing post-merge if needed.

I'll create issues for the above.

**Comment by davidakennedy** [comment]
The one remaining issue highlighted needs to move to Trac.

**Comment by karmatosed** [comment]
I think we should perhaps get a ticket per view on trac over a general review ticket now? As it's in merge. Tentatively closing.

**Comment by aaroncampbell** [comment]
Sorry, I didn't see this so I don't know if it was already moved to Trac. I created https://core.trac.wordpress.org/ticket/38422 with a patch for the coding style issue that I had pointed out.
