### ISSUE TITLE
anchor link

### ISSUE THREAD

**Issue by moserdominik** [WordPress/twentyseventeen#501]
Hello

Could it be an addictional feature to have an option for anchor links in menu?

E.g. https://test.com/#contact

Your sincerely,
Dominik

**Comment by davidakennedy** [comment]
Hello @moserdominik! This repository is closed now. All active development for Twenty Seventeen happens on WordPress Trac:  http://core.trac.wordpress.org/ Please request features there.

Anchor links can be accomplished with a custom menu in Twenty Seventeen, so what you want is possible already. 😄  See: https://codex.wordpress.org/WordPress_Menu_User_Guide
