### ISSUE TITLE
Visible Menu link on the mobile site without menu links

### ISSUE THREAD

**Issue by moserdominik** [WordPress/twentyseventeen#502]
Hello

If I don't have a menu link in my menu, the menu section on the normal page is disable or small.

On the mobile page the menu link is without a function visible (it should not be visible too).

Your sincerely,
Dominik

**Comment by davidakennedy** [comment]
Hello @moserdominik! This repository is closed now. All active development for Twenty Seventeen happens on WordPress Trac: http://core.trac.wordpress.org/ Please request features there.

The menu only shows if you have created a custom menu and assigned it to the menu area. On smaller screens, it's hidden behind a menu toggle to save space.

If you think you found a bug, create a ticket on Trac. Also, it's helpful if you're more specific and give steps to reproduce the problem.

Thank you!
