### ISSUE TITLE
Add clear deprecation notice

### ISSUE THREAD

**Issue by ghost** [WordPress/twentyseventeen#505]
https://core.trac.wordpress.org/ticket/40471

For users landing from GitHub search, this repo leaves little indication it is not the master. There is a note at the top of the repo indicating such, but it's easy to miss. Please update README for clarity.

Here's an example of clear deprecation in a README:

<img width="918" alt="screen shot 2017-04-17 at 5 09 05 pm" src="https://cloud.githubusercontent.com/assets/440298/25084741/bd1de08e-2390-11e7-83f4-dcdd1f1eca61.png">

Also, as mentioned in the related TRAC ticket, it would be nice to also provide a quick means for individuals to access the source code (e.g. via cURL) since that's what I've been doing with this source to fix mistakes when I derp in the _Appearance Editor_ in WordPress while customizing:

```bash
curl -O https://raw.githubusercontent.com/WordPress/twentyseventeen/master/funcntions.php
```

**Comment by ntwb** [comment]
It is already documented in the issue template here when creating issues that development has moved from GitHub to Trac:

```md
Development of Twenty Seventeen has now moved from GitHub to Trac.

Please cancel creating this issue and [search Trac for an existing ticket](https://core.trac.wordpress.org/query?status=accepted&status=assigned&status=new&status=reopened&status=reviewing&component=Bundled+Theme&milestone=4.7&col=id&col=summary&col=status&col=owner&col=type&col=priority&col=milestone&order=priority) or [create a new ticket](https://core.trac.wordpress.org/newticket?component=Bundled%20Theme) and patch on Trac

Thank you for taking the time to contribute to Twenty Seventeen!
```

**Comment by ghost** [comment]
@ntwb I don't believe you read my description.

**Comment by lukecav** [comment]
The example you referenced was very clear for **This Project Is Deprecated** wording.

Example
https://github.com/jhabdas/react-native-webpack-starter-kit/blob/master/README.md

Current README.md
https://github.com/WordPress/twentyseventeen/blob/master/README.md

**Comment by ntwb** [comment]
Twenty Seventeen is **not** deprecated, development has moved from GitHub to Trac

The code mirrored here on GitHub may not be as up to date as the primary SVN repo but it is not deprecated.

**Comment by ghost** [comment]
Just change the wording. The spirit of the issue remains the same.

**Comment by ghost** [comment]
I'm sure many will be curious to know how to curl code since you're using a different DCVS as well, not covered in the responses here. I've opened another issue for you.

**Comment by lukecav** [comment]
>## This project is not being actively developed on GitHub anymore

> Initial development for Twenty Seventeen happened on GitHub. Please do not create issues or send pull requests. Submit patches to WordPress Core https://make.wordpress.org/core/components/themes/ instead.
