### ISSUE TITLE
Please read this

### ISSUE THREAD

**Issue by ghost** [WordPress/twentyseventeen#506]
https://core.trac.wordpress.org/ticket/40471

For users landing from GitHub search, this repo leaves little indication it is not the master. There is a note at the top of the repo indicating such, but it's easy to miss. Please update README for clarity.

Here's an example of clear <del>deprecation</del> <ins>notice</ins> in a README:

<img width="918" alt="screen shot 2017-04-17 at 5 09 05 pm" src="https://cloud.githubusercontent.com/assets/440298/25084741/bd1de08e-2390-11e7-83f4-dcdd1f1eca61.png">

Also, as mentioned in the related TRAC ticket, it would be nice to also provide a quick means for individuals to access the source code (e.g. via cURL) since that's what I've been doing with this source to fix mistakes when I derp in the _Appearance Editor_ in WordPress while customizing:

```bash
curl -O https://raw.githubusercontent.com/WordPress/twentyseventeen/master/funcntions.php
```

**Comment by lukecav** [comment]
Example.
https://github.com/lukecav/twentyseventeen/blob/master/README.md

**Comment by davidakennedy** [comment]
Added a notice to the README.md file.
