### ISSUE TITLE
Undefined variable: post

### ISSUE THREAD

**Issue by WPDevHQ** [WordPress/twentyseventeen#56]
These notices are not visible as the are hidden behind the header image and only noticed them after removing the image.

Notice: Undefined variable: post in F:\Users\Zulf\Desktop\UniServerZ\www\seventeen\wp-content\themes\twentyseventeen-master\inc\extras.php on line 39

Notice: Trying to get property of non-object in F:\Users\Zulf\Desktop\UniServerZ\www\seventeen\wp-content\themes\twentyseventeen-master\inc\extras.php on line 39

Edit: Adding `global $post;` fixes this but I'm not sure if that is the ideal solution.

**Comment by BharatKaravadra** [comment]
I just removed the header image in WP Admin >  Appearance > Customise > Header Image, using the "Hide Image" button and cannot see the error in the browser nor the source.

Is it appearing everywhere or on a specific post or page?

**Comment by WPDevHQ** [comment]
Do you have your `WP_DEBUG` defined as `true` in wp-confing.php?

**Comment by grappler** [comment]
A better solution would be remove the variable.

**Comment by davidakennedy** [comment]
Great catch @WPDevHQ and thanks to @grappler for work on the pull request. It looks good.
