### ISSUE TITLE
Single Post & Page: Option To Display Title In Header

### ISSUE THREAD

**Issue by BharatKaravadra** [WordPress/twentyseventeen#57]
It seems a bit strange that the featured image of a post or page, if set, appears in the header with the site title and description.

It may be better on there being a featured image if there was an option to switch of the title where it appears above the content, and for it to appear in the header as the bold white text,

**Comment by WPDevHQ** [comment]
I believe in the final design the featured image will not be used to populate the header on single posts and inner pages.

**Comment by melchoyce** [comment]
@WPDevHQ is correct, this isn't how it's going to work in the updated design: https://cloudup.com/cR_df4xfeeG
