### ISSUE TITLE
Better support for non-latin font fallbacks

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#59]
One thing Twenty Sixteen really wanted to do but ran out of time to do was really rock-solid support for non-latin alphabets. I’d love, love if any polyglots and i18n folks could help us figure out a way to make that happen! 

https://github.com/impallari/Libre-Franklin has super great language support, but as far as I can tell, it's limited to latin alphabets.

In an ideal world, if characters aren't supported by Libre Franklin, we'd be able to specify an alternate default font for those languages that looks great.

Off the top of my head, I’d REALLY love Twenty Seventeen to have good font fallbacks for Cyrillic, Arabic, Vietnamese, Thai, Japanese, and Chinese. If there are other languages with non-latin alphabets you think need to be included, please chime in.

---

_9/30 Edit_

List of alphabets we want to try support:
- [x] Cyrillic ( #364 )
- [x] Greek ( #366 )
- [x] Hebrew ( #294 )
- [x] Arabic ( #398 )
- [ ] Vietnamese ( [See Comment](https://github.com/WordPress/twentyseventeen/issues/59#issuecomment-254065128) )
- [x] Thai ( #93 )
- [x] Japanese ( #155 )
- [x] Korean ( #286 )
- [x] Chinese ( #359 )
- [x] Devanagari ( #403 )
- [x] Gujarati ( #404 )

**Comment by grappler** [comment]
There is also Hindi and Korean which have a different script. I suppose Urdu and Persian are covered with the Arabic script.

**Comment by superpoincare** [comment]
> If there are other languages with non-latin alphabets you think need to be included, please chime in.

Greek. 

A lot of sites which use mathematical expressions/equations need it. Mathy people use Greek alphabets as symbols.

**Comment by acosmin** [comment]
Maybe we can add two or three fonts as a select option (for both body text and headings) in the Customizer and add styles for each of those fonts, like line-height, word/letter spacing.

**Comment by petyaraykovska** [comment]
Mel, thanks so much for the early consideration of this. 

Based on http://wordpress.org/about/stats and the overall stats for world languages (some of which have just been completed or are close to 100% for WordPress, so adoption should raise from 4.7 on), here are some of the languages/scripts that are not on the list that I think should be supported or have a fall back font. 
- **Hebrew**
- **Greek**
- Hindi, Marathi, Nepali, some of the other languages of India that are actively worked on right now use **Devanagari script** 

Thank you, let me know if I can help with anything else - happy to help with testing all these when the time comes.

**Comment by BharatKaravadra** [comment]
The Gujarati language of India should be considered and seem to use **Gujarati script.**

I speak but do not read or write Gujarati, but should be able to find someone to help if required.

**Comment by superpoincare** [comment]
@melchoyce 

Is this something that might interest you?

https://www.google.com/get/noto/

> When text is rendered by a computer, sometimes characters are displayed as “tofu”. They are little boxes to indicate your device doesn’t have a font to display the text.
> 
> Google has been developing a font family called Noto, which aims to support all languages with a harmonious look and feel. Noto is Google’s answer to tofu. The name noto is to convey the idea that Google’s goal is to see “no more tofu”. Noto has multiple styles and weights, and is freely available to all. The comprehensive set of fonts and tools used in our development is available in our GitHub repositories.

**Comment by melchoyce** [comment]
@petyaraykovska Do you know if polyglots team have any developers who might be interested in exploring the best way to tackle this problem from a technical standpoint?

**Comment by petyaraykovska** [comment]
@melchoyce There are several people that might be able to help, given they have availability. I'll reach out.

**Comment by slaFFik** [comment]
Also please consider Cyrillic.

**Comment by nukaga** [comment]
Japanese font

```
font-family: "Yu Gothic", YuGothic, "Hiragino angle Gore-Pro", "Hiragino Kaku Gothic Pro", "Meiryo", Meiryo;
  font-weight: 500;
```

YuGothic is Beautiful font. But Windows 8.1 only becomes thinner. So font-weight: 500; you will need.
If you are distributed each language, we want you to adopt the YuGothic.

**Comment by nukaga** [comment]
Sorry,
Japanese font 

```
font-family: "游ゴシック", "Yu Gothic", YuGothic, 'ヒラギノ角ゴ Pro W3', "Hiragino Kaku Gothic Pro", "メイリオ", Meiryo, sans-serif;
font-weight: 500;
```

I tried the Japanese of Twenty Seventeen.
I think this will be good.

**Comment by naokomc** [comment]
Seconding what Petya said. Mel, thanks for bringing this up! 

To add a little more information to @nukaga's comment - if you are going to be specifying Japanese fonts based on the UI language of the frontend, we think including Yu Gothinc (which is the same as 游ゴシック) is a good idea. If we do this though, we also need `font-weight: 500` to avoid an issue with Win 8.1.

However, if the application is _not_ language speicific, here is an alternative which doesn't tneed the `font-weight` speicification.

`font-family: "ヒラギノ角ゴ Pro W3", "Hiragino Kaku Gothic Pro", "メイリオ", Meiryo, sans-serif;`

**Comment by woraperth** [comment]
Hello, I just test Twenty Seventeen for Thai content. Font size and line-height looks great, but letter-spacing on headings could be removed to make it more suitable for Thai language :)

This is the screenshot of current Twenty Seventeen: http://file.designil.com/19Ub2
This is the screenshot of Twenty Seventeen after removing letter-spacing: http://file.designil.com/K3dz

Please take it into consideration :)

**Comment by melchoyce** [comment]
Thinking about implementation...

What I'd really like to do is figure out from WordPress core itself what Site Language a user has set, and then load separate fonts for those languages. However, that could be weird if someone is using WordPress in a different language, but writing in English. I'm not sure how often that happens? Would love some input here.

The other idea I have (which isn't ideal since it's a manual process) is to have a theme setting that lets you select language, and then we load a different font stack (probably using system fonts) based on your language selection. This is probably the easiest way to approach better i18n support. 

Does anyone have any other technical suggestions for implementing this? I admit my ideas are very much limited by my own development experience and WordPress knowledge.

**Comment by samikeijonen** [comment]
I'd ping @justintadlock for ideas on technical suggestions on this one.

**Comment by justintadlock** [comment]
I've been trying some different things with non-Latin (and just non-English in general) languages.  It depends on the theme, but some of the things I've done:
- I have a script that allows far more specific stylesheets than core's locale style.
- In my latest theme that uses Google Fonts, I have some fallbacks to their Noto Sans fonts.  This is filterable.
- I've got several scripts that just extend theme functionality based on locale.  Just depends on what we're looking for.

It'd be particularly easy to set up language-based font stacks and grab the locale.  Match up the locale to the font stack.  Then, allow people to filter.

How things are implemented really comes down, at least to me, to whether you're going with system fonts or Google Fonts.

Then, it comes down to where you define the CSS:
- Add to `wp_head`.
- Locale-specific stylesheets.
- Drop everything into `style.css`.

I usually design my themes with a non-Latin foreign language enabled from early on so that I don't forget that English-first users are just a small part of my audience.  If you take that approach with theme building, solutions will happen naturally.

**Comment by joyously** [comment]
Couldn't it be as simple as this?

```
html {font-family: /*whatever the default font stack is */}
html[lang=nl-be] {font-family: /*whatever the font stack for Dutch is */}
html[lang=ka-ge] {font-family: /*whatever the font stack for Georgian is */}
html[lang=hi-in] {font-family: /*whatever the font stack for Hindi is */}
html[lang=he-il] {font-family: /*whatever the font stack for Hebrew is */}
```

etc. for all the languages that need something besides the default font stack.

**Comment by melchoyce** [comment]
I had no idea you could specify `lang` in CSS and honestly that is super, super cool.

**Comment by joyously** [comment]
You can use HTML attributes as selectors. Just make sure that the lang attribute is output on the html tag, which is typical.

**Comment by woraperth** [comment]
I suggest adding an option to select language of the content (apart from language of admin backend). Because most of the time many people I know use English backend because they are used to it, and write content in another language :)

**Comment by grappler** [comment]
You will need a plugin for this. Either to set the admin language to English or save the post language. This is either plugin or core territory.

Related discussions:
https://github.com/glueckpress/wordpress-post-language
https://make.wordpress.org/core/2015/06/29/wordcamp-europe-2015-multilingual-discussion/

**Comment by woraperth** [comment]
Thank you @grappler ! That's neat.
Then something like html[lang=xxx] which @joyously mentioned would be sufficient :)

**Comment by superpoincare** [comment]
Is this server side?

The only simple way as far as I know about having as much language support as possible is via CSS unicode-range. 

There are some issues with browser support as browsers such as Safari 9 and Edge will download fonts even if not needed. 

Another way: Typekit uses javascript to figure out all the unicode glyphs needed in a page and then downloads custom font files.

**Comment by ntwb** [comment]
See also the `:lang` CSS pseudo-class: https://developer.mozilla.org/en-US/docs/Web/CSS/:lang

**Comment by waviaei** [comment]
I don't think it will be as simple as:

> html {font-family: /_whatever the default font stack is */}
> html[lang=nl-be] {font-family: /_whatever the font stack for Dutch is */}
> ...

At least in Japanese, you will need to finely adjust line-height, font-size, font-weight, etc. I am sure there are other languages out there where simply specifying different font-family is not a good-enough solution. You can, of course, code everything, but that means we will be loading lots of language specific styles that might not be needed at all.

_EDIT_
Some discussions has been happening on Japanese Slack. I am sure @nukaga or @naokomc will report some feedbacks of that :-)

**Comment by woraperth** [comment]
@ntwb I second that. The browser support is great. :D

@waviaei I agree. I think we can add the code like @imnok did here:
https://github.com/imnok/twentyseventeen/commit/47e6964717122026d1b3c723d4142ecd1b55b44d

**Comment by superpoincare** [comment]
Is there a demo for this?

**Comment by melchoyce** [comment]
> Is there a demo for this?

Not yet. The theme development is still in its v1 stage, and I also still need to research non-latin font stacks we can use. (Thanks @nukaga and @naokomc for suggesting a Japanese font stack!)

**Comment by superpoincare** [comment]
Hi @melchoyce 

By demo, I meant to ask: something like a code on codepen or jsbin or a site with a different theme or even a different CMS. 

One has to take into account browsers' behaviour. So for example Safari just implemented downloading only the font files needed for a page in version 10 (with unicode-range in css @font-face). Safari 9 would download all fonts with unicode-range.

**Comment by melchoyce** [comment]
Ah, that I'm not sure about.

**Comment by josephfusco** [comment]
@vijayaraghavanramanan Do you mind providing links please

**Comment by superpoincare** [comment]
Hi @josephfusco,

Yeah: [Safari 10](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html). See "Text features"

Mozilla's [site](https://developer.mozilla.org/en/docs/Web/CSS/@font-face/unicode-range) on unicode-range. See endnote.

**Comment by davidakennedy** [comment]
I'd be open to making this happen from an implementation standpoint. I think it's possible and I want this theme to be awesome out of the box for as many as possible.

Sounds like we have a good starting list here: https://github.com/WordPress/twentyseventeen/issues/59#issuecomment-246169307 Can we get a good final list?

@melchoyce Then, you can finalize a set of font stacks.

I think we can do a lot with enqueuing different fonts based on a user's language selection in Core, and pairing that with small CSS files with tweaks.

**Comment by nukaga** [comment]
We had a discussion in the Japanese Slack. And I was pull requests the appropriate Japanese font style. #155 

```
font-family:'Hiragino Kaku Gothic Pro', Meiryo, sans-serif;
letter-spacing: normal;
```

h1,h2,h3,h4,h5,h6 +
`font-weight: bold;`

Thanks,  @waviaei @naokomc

**Comment by melchoyce** [comment]
For folks who read in any of the alphabets list in https://github.com/WordPress/twentyseventeen/issues/59#issue-176212195, what websites do you visit in those alphabets that you find professional looking and easy to read? Looking for font-stack inspiration.

**Comment by grappler** [comment]
I find that the BBC has good Local sites so does the Deutsche Welle.
- Urdu http://www.dw.com/ur/%D8%B9%D9%86%D9%88%D8%A7%D9%86%D8%A7%D8%AA/s-11933 http://www.bbc.com/urdu
- Hindi http://www.dw.com/hi/%E0%A4%96%E0%A4%AC%E0%A4%B0%E0%A5%87%E0%A4%82/s-11931
- Greek http://www.dw.com/el/%CE%B8%CE%B5%CE%BC%CE%B1%CF%84%CE%B1/s-10507
- Bulgarian http://www.dw.com/bg/%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D0%BE/s-10257
- Chinese http://www.dw.com/zh/%E5%9C%A8%E7%BA%BF%E6%8A%A5%E5%AF%BC/s-9058
- Vietnamese http://www.bbc.com/vietnamese
- Tamil - http://www.bbc.com/tamil

For Hebrew @yoavf or @illuminea may be able to help.

**Comment by NateWr** [comment]
The script for Urdu is very similar to that which would be used for Arabic, Farsi and Pashto, and I'd expect things like workable font sizes and line heights to be the same. The BBC has [font variations](http://www.bbc.co.uk/gel/web/building-blocks/non-latin-typography/arabic-scripts) available for each.

Another consideration for languages based on Arabic script is that `text-transform: uppercase` is meaningless. I'm not sure if this is used in TwentySeventeen but it's something worth noting.

**Comment by yoavf** [comment]
I've just checked a few of my favorite Hebrew sites. Most good ones use web fonts. An exception would be newspaper site [Haaretz](http://www.haaretz.co.il/) with  `"Open Sans Hebrew","Helvetica Neue",Helvetica,Arial,sans-serif`

(Note: Edited the section below after some feedback from ranh.)

Some personal  preferences for Hebrew (web) typography: 
- System serif fonts typically don't look good on the web, especially when combined with non-serif fonts. Matching serif/non serif requires some expertise.
- Italic text shouldn't be used, unless the font includes a native slanted weight with the Hebrew characters. One alternative for quotes is to use a cursive (i.e handwritten) font, or a monospaced font.

**Comment by melchoyce** [comment]
Unfortunately, Open Sans is a web font. :/ 

Of these three options, is one better looking and more legible than the other?

https://cloudup.com/cuLKAB2FjXl

Thanks @yoavf (and ranh)!

**Comment by ranh** [comment]
There are some artifacts at the top here, but otherwise Arial Hebrew is the best of the three: https://cloudup.com/iULLfSZpZPt

Here Helvetica is requested but since it doesn't have Hebrew characters, Arial is used for those chars as a fallback. However some chars are available in Helvetica, like double quotes, so Helvetica is still used for those. So mostly it's the same excpet for a few bad chars (and not having the artifacts at the top): https://cloudup.com/iaAoOKKjzeS

Incidentally, this is not the behavior I would expect for OS X, it should be Lucida Grande as the fallback Hebrew font. But maybe it varies between browsers and locale settings. Arial is probably the fallback under Windows. 

Tahoma is not commonly used in Hebrew: https://cloudup.com/iAVuX9tgBJu

AFAIK, Arial is the only "safe" font for Hebrew. 

Also AFAIK, it should be specified as `"Arial Hebrew", Arial`, to work correctly across macos and Windows.

**Comment by melchoyce** [comment]
Thank you @ranh! That's super helpful.

**Comment by melchoyce** [comment]
re: Vietnamese, Libre Franklin introduced support in https://github.com/impallari/Libre-Franklin/commit/b57e464c491caffa8a5659c93ef8498694296e33. I pinged the font designer on Twitter to ask if that support would be rolled out to Google Fonts, and he said yes, soon. 

So, what I'm wondering is — should we adjust the font-stack now and then un-adjust it later when the Google Fonts version updates, or should we leave it? 

Here's what it looks with the current Google version of the font:

<img width="801" alt="screen shot 2016-10-16 at 2 37 53 pm" src="https://cloud.githubusercontent.com/assets/2846578/19419853/257f74d0-93ae-11e6-88bb-d5493c102c56.png">

**Comment by davidakennedy** [comment]
@melchoyce Re: Vietnamese – any alternatives? Time is running out. 😞

**Comment by melchoyce** [comment]
@davidakennedy What are your opinions on the options I laid out?
1. Leave it and wait for the eventual Google Fonts update
2. Create an alternative font-stack, and then delete it when Google Fonts is updated (_if_ we notice 😕)

**Comment by melchoyce** [comment]
Chatted with @davidakennedy and decided to leave Vietnamese, pending the font update on Google Fonts. It'll be a much more tailored experience, and we won't have to worry about redoing anything afterwards. With that, I think we can close out this issue. If anyone thinks we should support additional languages, please make a new issue. :)

Thanks for everyone's help and input here! Please keep testing in other languages.

**Comment by mayukojpn** [comment]
Hi! I talked with @kientrong from @FameThemes, one of vietnamese theme distributor and he would like to help this issue. Can we make a ticket on trac? Or is it too late?

**Comment by melchoyce** [comment]
Can definitely make a trac ticket! Be sure to put it in the "Bundled Themes" with "4.7" as the milestone.

**Comment by impallari** [comment]
Hi Guys, sorry to arrive late to the party.
Some good news: Libre Franklin v1.015 was just released. It fixes a small bug in the italic double-quotes,  adds support and coverage to lots of languages (including Vietnamese), and the kerning was greatly improved. I'm very happy that you are using it for this awesome new theme. Thanks!
I will ping the guys at googlefonts so they can make it public asap.
@melchoyce

**Comment by melchoyce** [comment]
Thank you so much @impallari! Super excited to use Libre Franklin :)
