### ISSUE TITLE
Load Child Theme style.css in the Parent functions.php

### ISSUE THREAD

**Issue by superpoincare** [WordPress/twentyseventeen#67]
Right now, child themes need to load the parent style.css in the child functions.php. This is slightly odd. 

A nice way to load the parent theme style.css is in the parent functions.php itself. 

This can be done by using `is_child_theme()`

If this evaluates to true, both the parent style.css and child stye.css are loaded. Else only the default style.css is loaded.

**Comment by ahmadawais** [comment]
I think it would be redundant to do that. A child theme does that.

**Comment by superpoincare** [comment]
I understand. But my point was that it's better to enqueue it in the parent functions.php so that it's not needed in child theme. In one scenario, the user just needs to make a few changes in style and can have only one file in the child theme folder, which is child style.css.

**Comment by ahmadawais** [comment]
That will render this theme not usable for many cases. Case in point, what if I want to use my own Child Theme which has a different architecture?

**Comment by grappler** [comment]
At the moment you could not have a different location for the style.css in the child theme because of `get_stylesheet_uri()`

**Comment by superpoincare** [comment]
Yeah child theme style.css is loaded by the parent functions.php. 

If one needs a different architecture, the developer anyway has to dequeue the child theme style.css because the parent theme loads it. 

This is a good post arguing why it makes sense to enqueue child style.css from the parent functions.php. 

http://justintadlock.com/archives/2014/11/03/loading-parent-styles-for-child-themes

Code: 

```
add_action( 'wp_enqueue_scripts', 'my_enqueue_styles' );

function my_enqueue_styles() {

    /* If using a child theme, auto-load the parent theme style. */
    if ( is_child_theme() ) {
        wp_enqueue_style( 'parent-style', trailingslashit( get_template_directory_uri() ) . 'style.css' );
    }

    /* Always load active theme's style.css. */
    wp_enqueue_style( 'style', get_stylesheet_uri() );
}
```

**Comment by davidakennedy** [comment]
Thanks for the issue @vijayaraghavanramanan!

I like the idea of this, but feel like it borders on Core territory and goes against the current best practices for [child themes](https://codex.wordpress.org/Child_Themes). For something like this to land in a default theme, I'd like to see an official recommendation from the Theme Review team first and/or support on this from Core in some way.
