### ISSUE TITLE
Several Minor Documentation Issues

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/twentyseventeen#68]
Throughout the theme, there are several minor documentation issues as per the [WP PHP Documentation standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#6-file-headers). I plan to fix them with a PR.
- [x] FIX: There should be no period for file headers' summary 
- [x] FIX: More than two times a parameter has not been documented
- [x] FIX: Many files have no file DocBlock
- [x] NEW: @pacakge WordPress
- [x] NEW: @subpackage Twenty_Seventeen ( I'd opt for a new package name which should be a single word instead of two words.
- [x] NEW: @since (I'd opt for adding @since 1.0.0 to each and every file head)

Looking forward!

**Comment by davidakennedy** [comment]
Thanks for the issue and pull request @ahmadawais! This has been on my list, so happy to have help with it. I'll leave some specific feedback on the PR itself.

**Comment by ahmadawais** [comment]
@davidakennedy Great :)

I left some questions about the format for each file header in the PR. Do take a look. 

I'd like to contribute most of my time here with TwentySeventeen by keeping a check on each and every file to help it conform with the WP Docs/Coding standards. This will help us set the right expectations and example for new developers as well.
