### ISSUE TITLE
JavaScript review

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/twentyseventeen#7]
The JavaScript in the theme needs to be reviewed to make sure works as expected in the supported browsers, and that the code is optimized. 

Probably best to do once #4 is complete.

**Comment by tomjn** [comment]
As of https://github.com/WordPress/twentyseventeen/commit/69482880b4ae2ec145f60df417423665581a5653 the themes Javascript would pass a .com VIP theme review

**Comment by joshcummingsdesign** [comment]
See #277 as well. I know some of the functions in global.js that I saw can be optimized (i.e. jQuery selector caching). Happy to take a look.

**Comment by joshcummingsdesign** [comment]
Took a pass at optimizing global.js in #306

**Comment by davidakennedy** [comment]
Closing this, as the theme had several reviews. Of course, continued scrutiny when the theme merges to Core is welcome.
