### ISSUE TITLE
There Could Be a Better Architechture for Customizer

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/twentyseventeen#70]
I am a big fan of Customizer and building themes with a better thought out architecture. This is not an issue but rather a suggestion for improving the customizer's architecture in TwentySeventeen theme. 

I am proposing something like what I have created at [WPCustomize](https://github.com/ahmadawais/WPCustomize/tree/master/customizer). If you guys a open to something like that, I'd love to contribute.

**Comment by grappler** [comment]
You mean a better folder/file structure instead of code architecture?

**Comment by ahmadawais** [comment]
@grappler  Better folder/file structure, yes. Complicating the code architecture for a default theme would make lesser sense.

**Comment by trsenna** [comment]
Hi, +1 for better folder/file structure here :)

compared WPCustomize suggested by @ahmadawais with current twentyseventeen customizer.php, WPCustomize is much easier to read. It becomes a good structure for easy modifying and copy and pasting for other projects/themes :)

**Comment by ahmadawais** [comment]
Glad you agree with me @trsenna the folder structure is meant to be portable. I have even started to think about putting its JS files inside the same folder `customizer` so that this folder can act as a separate component.

**Comment by davidakennedy** [comment]
Thanks @ahmadawais for the issue.

I like the idea behind this, but I don't think it's necessary for two reasons:
- A default theme shouldn't have so many options that splitting up the architecture makes sense.
- This type of structure makes sense for more experienced developers, but for those new to theming or the Customizer, it can make connecting the dots harder.

With that in mind, I'm closing this one. Thanks again!

**Comment by ahmadawais** [comment]
@davidakennedy I understand. Keeping it simple and trying not to overcomplicate things here is the right step forward. Got the sense of it after going through several other issues and PRs. 

Glad you like the idea of having a good architecture though :) 

Cheers!
