### ISSUE TITLE
Gulp Based Build Process Proposal!

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/twentyseventeen#71]
I'd like to propose a `gulp` based build process for this theme. I have been maintaining a boilerplate called [WPGulp](https://github.com/ahmadawais/WPGulp) which is being used by 100+ WP projects already. I'd love to contribute to this theme by adding a gulp build process. 

If I can get a LGTM here then I can get started with it.

**Comment by grappler** [comment]
What tasks do you think we could use? My inital reaction is that we do not need it. Also WordPress core uses Grunt.

**Comment by joyously** [comment]
It seems to me that a default theme (that you want people to extend with child themes) should be simple enough that it doesn't need a build process.

**Comment by ahmadawais** [comment]
Using a build process doesn't mean the theme will become complicated. No, sir. Less advanced users will always modify the built theme instead of its pre-built state. With the build process, we can use Sass or PostCSS and some other stuff like mentioned in the boilerplate above. 

I know the core uses Grunt but that's coz core has a technical debt. Gulp has surpassed Grunt by a number of users, speed, ease, and efficiency for more than two years now.

**Comment by trsenna** [comment]
I agree that gulp, PostCSS and SASS are cool and many times needed. But I think better to keep twentyseventeen simple. I see wp.org default themes as a resource for learning, and files like package.json, composer.json, bower.json, gulp.js and a lot of others just make our life harder to understand all pieces of the theme development. For someone new for theming the unique thing we are sure is that they need PHP, HTML and CSS... so I would keep simple with PHP, HTML and CSS only always when possible.

**Comment by grappler** [comment]
> Twenty Seventeen will also use plain CSS — it won’t use preprocessors in the development of the theme. This will keep it simple, making the theme easier for everyone to understand, quicker for anyone to modify and better to maintain in the long run.

This is quoted from the announcement post. https://make.wordpress.org/core/2016/09/09/say-hello-to-twenty-seventeen-%F0%9F%91%8B%F0%9F%8F%BD/

**Comment by WPDevHQ** [comment]
Lets not complicate things here, not everyone uses build processors!

To include such mechanisim on a default theme may end up excluding a lot of contributors.

**Comment by ahmadawais** [comment]
@grappler I didn't read that. So, is there a hard NO to this suggestion?

**Comment by helen** [comment]
I think the takeaway is that solutions should not be looking for problems.

**Comment by ernilambar** [comment]
Lets keep it simple. Simple code is better code :smile:

**Comment by asathoor** [comment]
I'd prefer a "keep it simple stupid" solution. As soon as the theme is ready we can use Gulp, Grunt, Bower and similar according to taste. During development it's better to work on common grounds.

**Comment by davidakennedy** [comment]
Hey @ahmadawais! Thanks for the feedback and for starting this discussion.

As others have mentioned, having a build process in Twenty Seventeen is overkill. A default theme isn't just a theme, but a learning tool for those who want to learn not just WordPress, but HTML, CSS and JavaScript. So the barrier to entry should be as low as possible.

That said, this isn't something that makes sense for the theme now, or in the future. But there are other issues that need this type of thinking. Check out #29 if you're interested.
