### ISSUE TITLE
 Add version number for all single PHP files for better handling child themes

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/twentyseventeen#72]
I've made a plugin called child theme check to keep track of changes in the parent theme (See: https://wordpress.org/plugins/child-theme-check/)

This would prevent security holes / missing features through unchanged files in child themes after an (security/feature) update of the parent theme.

There are slides from my talk at WordCamp Cologne which are explaining the issue that is solved by the plugin:
http://de.slideshare.net/zodiac1978/the-child-theme-dilemma-en

WooCommerce has a similar system to show outdated plugin template files:
http://speakinginbytes.com/2014/02/woocommerce-2-1-outdated-templates/

There is Pull Request for the Theme Check plugin, too:
https://github.com/Otto42/theme-check/issues/115

I really would like to see this in Twenty Seventeen. :)

Already discussed here: https://core.trac.wordpress.org/ticket/36972

**Comment by 2ndkauboy** [comment]
+1

**Comment by Drivingralle** [comment]
+1

**Comment by dimbak** [comment]
+1

**Comment by christopherkurth** [comment]
+1

**Comment by davidakennedy** [comment]
@Zodiac1978 Thanks for the issue and pull request!

Just so I understand correctly, would these version numbers be updated only when a file is updated? Or updated every release?

**Comment by Zodiac1978** [comment]
@davidakennedy Thanks for asking! These version numbers would be updated only when the file is updated. With this information we can check if a file is outdated in a child theme.

**Comment by arkonisus** [comment]
+1

**Comment by davidakennedy** [comment]
@Zodiac1978 Cool, that makes sense. I'd like to merge the PR. Can you update it.

Just drop the new header below the last one in each file: https://github.com/WordPress/twentyseventeen/blob/master/404.php#L9

**Comment by Zodiac1978** [comment]
@davidakennedy Great to hear that. I've updated the PR. :)

**Comment by davidakennedy** [comment]
Left a comment on the PR. 😄
