### ISSUE TITLE
Use get_home_template()

### ISSUE THREAD

**Issue by justintadlock** [WordPress/twentyseventeen#73]
You probably want to use the core `get_home_template()` in `front-page.php` instead of this:

```
get_template_part( 'index' );
```

`index.php` is not a template part.  Rather, it's a top-level template with a function specifically designed for getting it.  I'd change the code to something like:

```
include( get_home_template() );
```

Ref: https://github.com/WordPress/twentyseventeen/blob/master/front-page.php#L14

See: https://developer.wordpress.org/reference/functions/get_home_template/

**Comment by trsenna** [comment]
Hi,

maybe I also would move the if/else that checks 'show_on_front' to a 'template_include' hook. So the logic of deciding what template to display is moved to a different location than the template file. IMHO would be nice if template files avoid deciding/changing the default WP template hierarchy. I think the correct place for overriding the default WP template hierarchy is within the template_include hook. What Do you think about?

Ref: https://codex.wordpress.org/Plugin_API/Filter_Reference/template_include

**Comment by justintadlock** [comment]
That's actually what I do in my themes, except I use the `frontpage_template` hook:

```
add_filter( 'frontpage_template',  'twentyseventeen_front_page_template' );

function twentyseventeen_front_page_template( $template ) {

    return is_home() ? '' : $template;
}
```

Not sure if it's default-theme material or not.  But, maybe if enough core themes done it, we could eventually get better logic in core WP for this mess.

**Comment by mor10** [comment]
Added the proposal from @justintadlock including a commented section explaining the ternary operator logic since it can be a bit opaque at first sight.
