### ISSUE TITLE
Update normalize.css to the latest version

### ISSUE THREAD

**Issue by ntwb** [WordPress/twentyseventeen#78]
The latest is v4.2.0 and includes various improvements to what is currently used.

https://github.com/necolas/normalize.css

Keeping all the comments and formatting would also make this easier to maintain.

The other option is to remove it from `style.css` and just include it, this option is currently under consideration for `press-this.css` in [#WP37596](https://core.trac.wordpress.org/ticket/37596)

**Comment by davidakennedy** [comment]
@ntwb Thanks for the issue!

I'm all for updating it, and keeping in `style.css`.

**Comment by ahmadawais** [comment]
@ntwb @davidakennedy I have added a PR to address this issue. Take a look.

**Comment by josephfusco** [comment]
Cross referencing #12 so this appear under it
