### ISSUE TITLE
Disable header picture, show smaller custom-header based on title

### ISSUE THREAD

**Issue by seraphyn** [WordPress/twentyseventeen#84]
When the header picture _custom-header-image_ is removed, it should have the option to display _custom-header_ in a smaller height based on the site-title

**Comment by MichDe** [comment]
Along this same line of thought, a way to just 'turn off' the section would be useful. As the default theme, it would serve a larger pool of sites if there was a way to go content first without the large branding area.

**Comment by davidakennedy** [comment]
@seraphyn Thanks for the issue!

This sounds a lot like #85. Please see #4 for the design mockups. The larger header section is only included on the homepage.

I'm closing this out, but feel free to comment if I've misunderstood.
