### ISSUE TITLE
 Performance review: Should a performance budget be set?

### ISSUE THREAD

**Issue by davidakennedy** [WordPress/twentyseventeen#9]
See this post: https://timkadlec.com/2013/01/setting-a-performance-budget/

Also, what else can be done to ensure that the theme is fast in all environments?

**Comment by grappler** [comment]
This would be an interesting Idea. I find following the best practices should be enough.

**Comment by superpoincare** [comment]
I discussed fonts in a separate issue here: https://github.com/WordPress/twentyseventeen/issues/45

**Comment by joshcummingsdesign** [comment]
I agree there should be testing around performance. #7 includes a question about JavaScript performance. Happy to help there.

**Comment by davidakennedy** [comment]
Closing this out. The normal reviews of code and using best practices should get the theme where it needs to be.
