### ISSUE TITLE
Theme is not translation ready

### ISSUE THREAD

**Issue by bappi** [WordPress/twentyseventeen#98]
I think we should make the theme translation ready

**Comment by ntwb** [comment]
See #96. 

If there are other issues not covered in that pull request please describe what they are, open new tickets or pull requests please.

**Comment by grappler** [comment]
@B-07 Could you elaborate? I did not see any major issues.

**Comment by bappi** [comment]
Sorry I didn't notice there's already a PR for that.. Closing
